### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by knownasilya** [offirgolan/ember-light-table#10]
Is sorting implemented by default? Seems like `{{t.head}}` has sort enabled by default, but nothing seems to happen. Here's my setup:

```hbs
{{#light-table table class='table table-striped table-hover' as |t|}}
  {{t.head multiColumnSort=true}}
  {{t.body onRowClick=(action 'onclick')}}
{{/light-table}}
```

Looking at the demo app, it looks like you implement sorting yourself by sending the params to the server..

**Comment by offirgolan** [comment]
Yeah all data handling is up to you. The component just sets up everything for you so it's as easy as possible.

**Comment by samsebastian** [comment]
On this topic, is it best practice to sort / filter at the route or within the component containing the light-table?

**Comment by knownasilya** [comment]
The controller/route (little more hassle on the route).

**Comment by samsebastian** [comment]
Hmm..

I'm trying the below on the controller, but it sorts it when referencing `sortedPortfolios` outside the component (ie when I do an `{{#each}}` in the template, but the sort order will not update even though I am passing `sortedPortfolios` in as `{{pg-tables/portfolios model=sortedPortfolios onSort=(action "sortPortfoliosBy")}} ?

Can you see anything I'm doing wrong?

```js

    sortedPortfolios: computed.sort('portfolios', 'sortDefinition'),
    sortBy:           'title', // default sort by title
    sortAsc:    true, // default sort in ascending order
    sortDefinition:   computed('sortBy', 'sortAsc', function () {
        let sortOrder = get(this, 'sortAsc') ? 'asc' : 'desc';
        console.log('sort recomputing');
        return [ `${get(this, 'sortBy')}:${sortOrder}` ];
    }),

  actions: {

        sortPortfoliosBy(property, ascending) {
            console.log('about to sort by ' + property + ' : ' + ascending);
            set(this, 'sortBy', property);
            set(this, 'sortAscending', ascending);
        },
        
  }

```

**Comment by samsebastian** [comment]
Nevermind, figured it out, needed to add an observer

```js
    modelChanged: observer('model', function () {
        let table = get(this, 'table');
        if (table !== null) {
            table.setRows(get(this, 'model'));
        }
    }),

```
