### ISSUE TITLE
init functionality within light-table

### ISSUE THREAD

**Issue by SirZach** [offirgolan/ember-light-table#11]
Hey all,

I was curious why the `init` functionality, like creating a new Table and such isn't handled within the `light-table` component? As a result, I'm creating a wrapper table that all it does is exactly that and it adds one more, seemingly unnecessary, level of indentation in the `hbs` file likeso:

```handlebars
{{#netuitive-table-new
       model=model
       as |table|
}}
            {{#light-table table as |t|}}
              {{t.head}}

              {{#t.body as |body|}}
                {{#body.expanded-row as |row|}}
                  Hello <b>{{row.name}}!!</b>
                {{/body.expanded-row}}

                {{#if isLoading}}
                  {{#body.loader}}
                    Loading...
                  {{/body.loader}}
                {{/if}}

                {{#if table.isEmpty}}
                  {{#body.no-data}}
                    No users found.
                  {{/body.no-data}}
                {{/if}}
              {{/t.body}}

              {{t.foot}}
            {{/light-table}}
{{/netuitive-table-new}}
```

```javascript
//netuitibe-table-new/component.js
import Ember from 'ember';
import Table from 'ember-light-table';

const computed = Ember.computed;

export default Ember.Component.extend({
  model: null,
  table: null,

  columns: [],

  init() {
    this._super(...arguments);
    this.set('table', new Table(this.get('columns'), this.get('model')));
  }
});
```

```handlebars
{{!-- /netuitive-table-new/template.hbs --}}
{{yield table}}
````

**Comment by offirgolan** [comment]
The reason we decided to separate the table creation from the table view is for modularity and for easy table mutations. In our apps we have tables that we define in the route, some in controllers, and some in components. Once they are created we can easily pass the tables around and add/remove rows, hide/show columns, add/remove columns depending on the user's permissions, etc. If we were to just create the table in the component space, you would have no way to do any of this.

**Comment by SirZach** [comment]
Oh interesting! I don't get a lot of table reuse in the app so I never thought about it from that perspective.
