### ISSUE TITLE
Hover information Action for the Column Headers

### ISSUE THREAD

**Issue by dulichan** [offirgolan/ember-light-table#113]
I would like to add an information box when I hover over a header column. Is this possible? If not - where do I have to customize to make this happen?

**Comment by buschtoens** [comment]
There are two ways. You could either create an [extra component](https://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_component) and set the `title` attribute (and bind it via `attributeBindings`) or create a new [column type](https://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_type) and do the same and for example, make `title` a computed property.

If you generally only need titles on hover and nothing more fancy, I'd suggest using the latter approach.

**Comment by offirgolan** [comment]
I believe @buschtoens answered this perfectly (thanks 😸). Im gonna go ahead and close this issue. @dulichan feel free to reopen if you have any more questions.

**Comment by knownasilya** [comment]
Do rows have a hover action?

**Comment by offirgolan** [comment]
@knownasilya no they do not but you can easily add one by overriding the [rowComponent](http://offirgolan.github.io/ember-light-table/docs/classes/t.body.html#property_rowComponent)

**Comment by knownasilya** [comment]
@offirgolan would you take a PR adding onhover?

**Comment by offirgolan** [comment]
@knownasilya yeah of course 😸
