### ISSUE TITLE
Fixed left column

### ISSUE THREAD

**Issue by bakerac4** [offirgolan/ember-light-table#114]
One of the requirements I was given was to implement the first column as a fixed column. Much like http://opensource.addepar.com/ember-table/#/overview. If you collapse the width of the page, you will see that you can scroll everything but the first column to the right. This gives a much better presentation on mobile/tablet. Can you guys think of a way that I might accomplish this?

**Comment by taras** [comment]
@bakerac4 we don't have horizontal scroll in this addon.

I'm working on a few large tables right now and we're implementing a different kind of responsive behaviour. Instead allowing horizontal scrolling, we're collapsing hidden columns into an accordion with rows. This feature will likely be quiet portable and we could add it to this table. 

Speaking for myself, I don't see horizontal scrolling as a feature that we should be investing into. It complicates the implementation considerably and having horizontal and vertical scroll is generally not a practical user experience.

If you absolutely have to build this, then I could give you some suggestions but I'd advice exploring alternative user experiences.

**Comment by bakerac4** [comment]
Hey @taras do you have an example I can view for the hidden/collapsable column tables your working? I would love to be able to play around with it to see how it feels? It sounds like an interesting idea.

**Comment by taras** [comment]
@bakerac4 I don't have one yet, but I'll have a finished implementation in about 1 month.
