### ISSUE TITLE
Problems specifying the cellComponent

### ISSUE THREAD

**Issue by aexmachina** [offirgolan/ember-light-table#119]
The docs don't make it clear that the component path must be `light-table/cells/my-component`.

If I provide a `valuePath` in the columns spec I get an error `Cannot set read-only property "value" on object`. The workaround is to define `value: null` on the Cell subclass, but the `valuePath` has no effect.

Also, the only way for me to get the value was from `row.content`.

**Comment by offirgolan** [comment]
Closing as this is a duplicate of #120
