### ISSUE TITLE
Add-on 'ember-in-viewport' uses deprecated Ember.merge

### ISSUE THREAD

**Issue by kieran-rocks** [offirgolan/ember-light-table#121]
When using onScrolledToBottom for infinite scrolling, the ember-in-viewport add-on is used which defines an isInViewport function containing the line:

`const tolerances = merge(defaultTolerance, tolerance);`

This is causing the following deprecation warning to flood the console:

> DEPRECATION: Usage of `Ember.merge` is deprecated, use `Ember.assign` instead. [deprecation id: ember-metal.merge] See http://emberjs.com/deprecations/v2.x/#toc_ember-merge for more details.

Either another method of determining whether or not the component is in the viewport needs to be implemented or the add-on itself should be updated to use Ember.assign. I believe the usage of Ember.merge was deprecated in Ember 2.5 but I am not positive.

**Comment by offirgolan** [comment]
Fix is in master. Ill issue a release sometime in the next day or two.

**Comment by kieran-rocks** [comment]
@offirgolan Do you think this will make it into the next release? Did not seem to make it into v1.1.0. Thanks
