### ISSUE TITLE
Hard to overwrite cell/column base classes in own project

### ISSUE THREAD

**Issue by djsegal** [offirgolan/ember-light-table#124]
+ I want to get into the cell template and add some classes to nested components
+ but the `namespace` + `single word without dash` component make this difficult

-------

Can you move the nested base components to the main directory and just dasherize it to make it two words?

**Comment by djsegal** [comment]
i just did this instead:

```
// app/components/light-table/columns/base.js (of own project)

import Ember from 'ember';
import Column from 'ember-light-table/components/columns/base';

export default Column.extend({
  classNames: ['header'],
  classNameBindings: ['sortAsc:headerSortUp', 'sortDesc:headerSortDown'],
  sortAsc: Ember.computed('column.sorted', 'column.ascending', function() {
    if ( !this.get('column.sorted') ) { return false; }
    return this.get('column.ascending');
  }),
  sortDesc: Ember.computed('column.sorted', 'column.ascending', function() {
    if ( !this.get('column.sorted') ) { return false; }
    return !this.get('column.ascending');
  })
});
```

**Comment by offirgolan** [comment]
@djsegal I think what you're looking for is creating a new [column type](https://github.com/offirgolan/ember-light-table/blob/master/addon/classes/Column.js#L80-L98)

**Comment by djsegal** [comment]
This was the answer. Thank you.
