### ISSUE TITLE
Way to select default column to be sorted on init

### ISSUE THREAD

**Issue by djsegal** [offirgolan/ember-light-table#125]
I know that sorting isn't directly baked in at the moment, but maybe there's a way to make a default column selected as `sort:asc` at the beginning

**Comment by offirgolan** [comment]
In your column definition, you can do the following:

```js
new Table({
  label: 'Foo',
  sortable: true, // Default is true
  sorted: true,  // This will mark the column as sorted
  ascending: true // Default is true
});
```

If you dont want to do it there, you can just do 

```js
table.get('columns').findBy('label', 'Foo').set('sorted', true);
```

**Comment by djsegal** [comment]
I can't get it to work that way. The class that says it's sorted up/down gets added, but the items are initially sorted the wrong direction

If I do it with a javascript click though, it works (not ideal because i want multiple tables)

**Comment by offirgolan** [comment]
This addon doesnt actually do the sorting. Just sets up the correct classes/icons/etc. You need to do the sorting on your own before you insert the rows into the table.

**Comment by djsegal** [comment]
Thank you. Closing this issue
