### ISSUE TITLE
Multiselect

### ISSUE THREAD

**Issue by samsebastian** [offirgolan/ember-light-table#13]
I've been reading through the docs and couldn't see any mention of how you might implement mutliselect?

I assume it's by adding selected rows to an array, but I'm not sure how to pass that back as a comparison for the table to keep track of which rows are selected.. 

I know it's designed for maximum flexibility for people to implement this sort of thing however best suits their app, but would it be possible to get a snippet as an example of how someone else has done it?

**Comment by offirgolan** [comment]
You can checkout the code for the [multi-select table](http://offirgolan.github.io/ember-light-table/#/selectable) (just click on the panel header to see the code snippets). 

What multi select does, is allow you to use ctrl, cmd for mac, and shift to select multiple rows. These rows can be accessed via `table.get('selectedRows')`.

**Comment by samsebastian** [comment]
Ah my bad I didn't notice you could expand the code for the demo app, that is awesome.

Not sure if this is correct in docs though: http://offirgolan.github.io/ember-light-table/docs/classes/Body.html#property_multiSelect

My issue is that I saw `multiSelect` was `true` by default so didn't set it. I think the docs need to be updated to say the default is `false`?

**Comment by offirgolan** [comment]
👍 Ill make the change in the next revision! Thanks for bringing it to my attention 😸

**Comment by offirgolan** [comment]
@samsebastian I have updated the docs and added some much needed descriptions for each property. Im gonna go ahead and close this issue. Feel free to reopen if you run into any more trouble.
