### ISSUE TITLE
Better way to share global options with sub-components?

### ISSUE THREAD

**Issue by nmcclay** [offirgolan/ember-light-table#134]
I'm a bit confused on how to add more shared options that can be available to sub-components?  I see that there is a 'sharedOptions' property that can hold values, but I'm not certain how to add new values to this to pass it downstream?  I considered overriding the light-table component itself, but that seems like it could be overkill relative to what I'm trying to do which is just add another property.  Alternatively I considered overriding the 'Table' class itself, but that seems even more tricky as I haven't figured out a good way to functional way to properly extend the Table class.

**Comment by nmcclay** [comment]
I did get this to work by reopening the light-table component class like so:
```
import Ember from 'ember';
import LightTable from 'ember-light-table/components/light-table';

// My custom table component
export default Ember.Component.extend({
	height: '65v',
	itemCount: 100,

	// pass this sharedOptions into the light-table component
	sharedOptions: Ember.computed('height', 'itemCount', function() {
		return {
			height: this.get('height'),
			fixedHeader: false,
			fixedFooter: false,
			totalCount: this.get('itemCount')
		};
	}).readOnly()
});

// Override sharedOptions so its not a readOnly
LightTable.reopen({
	sharedOptions: null
});
```
This works, is this the expected manner to override these sharedOptions?  One risk I can see with this is that if sharedOptions changes that it will cause upgrading my table component to break.  IMO It would be better if we had a public 'customOptions' object we could pass that would be merged with the computed sharedOptions and therefor get passed downstream.

**Comment by offirgolan** [comment]
@nmcclay `sharedOptions` is a private instance that should not be externally modified. 

If you want to pass around data, you can use the column definition

```js
new Table ({
  valuePath: 'foo',
  myCustomProperty: 'bar'
});
```

which can be accessed in the component via

```hbs
{{column.myCustomProperty}}
```

If you're trying to pass around state, I would highly recommend using a service which can then be easily inject into your component. Lastly, you can pass around actions via `tableActions`.

**Comment by nmcclay** [comment]
Ah, yeah I suppose I should have been more clear about what I am actually doing.  I am overriding the header and footer components to add new sub-components to them.  Specifically a manual pagination controller, result size selector, and an action bar to the header.  These work great but without completely overriding all the component controllers its difficult to pass the extra meta data I need down stream.  My thinking was it would make more sense to use the existing mechanisms for shared options rather than creating all these shell extended components.

**Comment by nmcclay** [comment]
The idea of a service is quite interesting, but one trick is I do have contexts where I have more than one table displayed at a time.  I guess I could make some sort of associative dictionary lookup in the service, but it strikes me that all I really want to do is pass downstream some shared component state.

**Comment by offirgolan** [comment]
@nmcclay I see what you are trying to do but again, I would not depend on overwriting private instances since they could change at anytime without notice or can be removed completely if we find a better solution. To be honest, the `sharedOptions` was to be a temporary solution since its not the most scalable nor the most viable solution. 

As I noted before, I would suggest using a service to hold the state of each table. You are welcome to use the [tableId](http://offirgolan.github.io/ember-light-table/docs/classes/t.body.html#property_tableId) property as a key. 

```js
// services/table.js
export default Ember.Service.extend({
  init() {
    this._super(...arguments);
    this.state = {};
  },

  setState(id, state = {}) {
    this.state[id] = state;
  }

  getState(id) {
    return this.state[id];
  }
});
```

Then in your header / footer you can inject this service and do

```js
this.get('tableService').setState(this.get('tableId'));
const state = this.get('tableService').getState(this.get('tableId'));
state.foo = 'bar';
```

**Comment by nmcclay** [comment]
Makes sense, I'll have to look into this idea of a cross component service.  Thanks!

**Comment by offirgolan** [comment]
No problem. Im gonna go ahead and close this issue. Feel free to reopen if needed.
