### ISSUE TITLE
Can we allow link-to for each row?

### ISSUE THREAD

**Issue by eguitarz** [offirgolan/ember-light-table#141]
If I'm building a menu with ELT, it will be nice to pass in a menu model and have {{link-to}} on each row. That way I don't have to worry about highlight problem, since {{link-to}} automatically parse current route and append `class="active"` to the corresponding link.

**Comment by offirgolan** [comment]
Im not exactly sure what you mean but I believe defining your own cellComponent is what you are looking for.

**Comment by eguitarz** [comment]
@offirgolan Let me explain more about my case:

I have a contact list, each row includes name, phone, address ...etc. When I click on one row, I wish the row will be highlighted. The route would be `/contacts` for this contact list. But when I click on any one row, the route will be transitioned to `/contacts/:id` (but the contact list still existed). Is it possible not adding extra js code to have highlight effect on the row? Which means when I visited `/contacts/:id`, the row of `:id` should be added with a class. (e.g. `.active`).

Ember's {{link-to}} can add `.active` to the link according to current route - https://guides.emberjs.com/v2.7.0/templates/links/#toc_the-code-link-to-code-helper

So I was wondering can we leverage {{link-to}] in ELT?

{{#link-to "contacts.edit" contact}}
<tr>
   <td> ... 
</tr>
{{/link-to}}
...

I'm not sure how to use cellComponent to replace the whole row template, will that be possible?

**Comment by offirgolan** [comment]
@eguitarz using the link-to helper like that is not supported. I suggest taking a different route. 

1. Use the `onRowClick` action to navigate the to the correct contact
2. Use the row's classNames property to add / remove the active class

```hbs
{{#light-table table as |t|}}
  {{t.body onRowClick=(action 'rowClicked')}}
{{/light-table}}
```

```js
export default Ember.Controller.extend({
    table: null,
    
    actions: {
        rowClicked(row) {
          this.transitionToRoute('contacts', row.get('id'));
          this.get('table.rows').setEach('classNames', '');
          row.set('classNames', 'active');
        }
    }
})
```

**Comment by eguitarz** [comment]
@offirgolan thanks. Was just wondering can we have the highlight code as less as possible. Your way is similar to what we are currently doing. But there's one other thing, we have to set up the highlight class when entering the route via direct url. (or trigger this rowClicked method)

If we can do it without managing classNames by ourselves would be great, but I'm fine with current solution. Thank you.
