### ISSUE TITLE
Option to allow row selection without `ctrl`/`cmd`

### ISSUE THREAD

**Issue by bargar** [offirgolan/ember-light-table#147]
Though I understand the logic behind the `ctrl`-click to toggle individual rows, this may not be intuitive to users in some scenarios. Gmail is one of many examples where no meta keys are required to select/deselect individual rows.

I've added a configuration option to permit this behavior on a fork at [/bargar/ember-light-table](https://github.com/offirgolan/ember-light-table/compare/master...bargar:758a55c).

The existing behavior of course remains the default, but this tweak enables overriding it by setting `lt-body` property `multiSelectRequiresKeyboard` to `false`. Note: the `shift` click to select several consecutive rows behavior is unchanged in any event.

If there is interest and amenability, I would be happy to add testing and make a proper PR here in **/offirgolan/ember-light-table**.

**Comment by offirgolan** [comment]
@bargar a PR with this is very much welcomed 😸

**Comment by bargar** [comment]
@offirgolan #160 submitted, now including testing. Sorry for the delay!

**Comment by offirgolan** [comment]
Thanks again for you contribution @bargar! I should release this sometime this week 😸

**Comment by bargar** [comment]
My pleasure! Looking forward to it 🐸

**Comment by offirgolan** [comment]
@bargar this has been released in `v1.2.0`!
