### ISSUE TITLE
Scrolling a row into view

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#148]
```js
 /**
  * @module Table
  * @class Table
  */
export default class Table extends Ember.Object.extend({

  // ...

  /**
   * Scrolls the row with the specified index to the top of the viewport.
   * @method scrollToRow
   * @param  {Number} index
   * @return {Row} target row
   */
  scrollToRow(index = 0) {
    // insert magic here
  }
});
```

I'd really like this feature and would be down to submit a PR, if you like it as well. :)

**Comment by taras** [comment]
Your PR will be welcome. You might want to define this action on the table component rather than the table object since the scroll position is a DOM concern rather than state concern.

**Comment by buschtoens** [comment]
Great!

You mean the `{{light-table}}` component? I dont know how I'd cleanly call that action, since they are supposed to flow up and not down.

Or would you prefer a data- / attribute-driven approach?

```hbs
{{one-way-input index update=(action (mut index))}}
{{#light-table table scrollTo=index as |t|}}
  {{t.head}}
  {{t.body}}
  {{t.foot}}
{{/light-table}}
```

In my use case, I need to select and scroll a row into view, that is defined by a query parameter.

**Comment by buschtoens** [comment]
@taras 🔔😉

**Comment by buschtoens** [comment]
I'd like to reheat this issue once more, since we need this feature in our app. :grinning: 

In addition to manually scrolling a row to the top of the table (setting), I would also wish for a way of getting the row that currently is at the top.

Revisiting @taras's [comment](https://github.com/offirgolan/ember-light-table/issues/148#issuecomment-241726398), my interpretation is that the logic for scrolling to and determining the topmost visible row should be put into the `{{light-table}}` component (and rightly so).

In accordance with the DDAU mantra, I propose the following API:

```hbs
{{one-way-input index update=(action (mut index)) type="number"}}

{{#light-table table
  scrollIndex=index
  updateScrollIndex=(action (mut index))
  as |t|
}}
  {{t.head}}
  {{t.body}}
  {{t.foot}}
{{/light-table}}
```

Questions I see left for discussion:

1. Should we expose the index (as a `Number`) or the actual `Row` proxy object?
  I'd say the index is easier to work with.

2. Are `scrollIndex` and `updateScrollIndex` fitting names?

3. Should we add convenience methods like `Table#scrollTo(index)` and `Row#scrollTo()`?

**Comment by buschtoens** [comment]
@offirgolan I would really love to implement this feature. I just need your or @taras's okay on the proposed API :smile:

**Comment by offirgolan** [comment]
@buschtoens really sorry for being AFK! Been super distracted the last couple of weeks. 

I do have a couple of suggestions:

```hbs
{{#light-table table as |t|}}
  {{t.head}}
  {{t.body scrollTo=row onScroll=(action (mut row))}}
  {{t.foot}}
{{/light-table}}
```

- I like dealing with a row instance a lot more than indices. It just feels a little more polished and you can easily get the index of the row via `table.get('rows').indexOf(row)`.
- The logic should be kept at the t.body level
- Because this may cause some performance problems due to the nature of the feature, I suggest only enabling events/ creating observers if the `onScroll` action is passed in. \
- I'm also not sure what the limitation are with ember-scrollable, so that might have to be investigated as you work on this. If you run into an issue here, ill see if @taras can jump in and help out. 

> Should we add convenience methods like Table#scrollTo(index) and Row#scrollTo()?

I dont think that should be necessary. You should have all you need within the component. The goal is to try to keep rendering and data as separate as possible

If you need some more direction, feel free to ping me on slack. I'll be a bit more responsive on there :)

**Comment by buschtoens** [comment]
No problem. Thanks a bunch! :heart: 
I'll probably get to work on it tomorrow. :grinning:

**Comment by buschtoens** [comment]
> Because this may cause some performance problems due to the nature of the feature, I suggest only enabling events/ creating observers if the `onScroll` action is passed in. 

Kind of related:

What if I want to use `scrollTo` to "reset" the scroll position to the first row (when pressing a button for example) and the user then scrolls down again. If the user then presses the button again, the `didReceiveAttrs` hook would not get fired, as `scrollTo` already points to the first row.

`scrollTo` *has* to stay in sync, otherwise we can't guarantee that we detect the intent to scroll to a row.
  I went into greater detail in the previously linked [post in the Ember Community Slack](https://embercommunity.slack.com/files/buschtoens/F2KBKMHV0/DDAU__performance_concerns_when__checking_back_with_the_parent____SSOT).

So, if the user decides to pass in `scrollTo`, they should be forced to keep track of the scroll position by at least also passing in `onScroll=(action (mut row))` as a minimum requirement.

The most performant way is probably debouncing `onScroll` and only checking `scrollTo` after the `onScroll` action synced. Except where `scrollTo` gets updated and actually changes.

**Comment by offirgolan** [comment]
> So, if the user decides to pass in scrollTo, they should be forced to keep track of the scroll position by at least also passing in onScroll=(action (mut row)) as a minimum requirement.

I think this is reasonable. It will just have to be well documented and explained. 

Another use-case is just setting an initial `scrollTo` row without needing to keep track of the current scroll state.

**Comment by buschtoens** [comment]
> Another use-case is just setting an initial `scrollTo` row without needing to keep track of the current scroll state.

True.

I've slept over this and came up with an alternative to the *single source of truth / check back with the parent* approach:

The only reason we needed this behavior in the first place, is when the user wants to `scrollTo` a row that already is the value of `scrollTo`, e.g. after manually scrolling and then wanting to reset the scroll position to the first row again.

Because in this edge case `{{t.body scrollTo=targetRow}}` could not detect a property update.

However, with a little "hack" the user can actually force an update:

```js
// in the user's code
scrollTo(row) {
  if (this.get('targetRow') === row) {
    this.set('targetRow', null);
    Ember.run.schedule('render', null, () => this.set('targetRow', row));
  } else {
    this.set('targetRow', row);
  }
}
```
```hbs
{{t.body scrollTo=targetRow}}
```

This way we can rely on `didReceiveAttrs()` again and don't need that overly complicated and inperformant logic.

I've made an [Ember Twiddle](https://ember-twiddle.com/0417b69a9a69b0432f38b8055fa4aa4c?openFiles=controllers.application.js) which illustrates this pattern.

When we put a code snippet like that in the docs and in the example app, we should be good to go. :smile: 

I'm gonna go ahead and start implementing this.

**Comment by buschtoens** [comment]
While trying to implement `onScroll` (which should provide the current topmost row) I found out that this actually is a very hard problem.

While I can easily get the current scroll offset in px (thanks to https://github.com/alphasights/ember-scrollable/pull/25), it's quite complicated to get the row that is closest to this position. I'd either have to...

1. traverse all rows and compare their offset with the scroll offset or...
2. use the `InViewportMixin` in every `Row` to keep track of which rows enter or exit the viewport.

I can imagine that both solutions are slow.

The first approach however could be sped up significantly by approximating the topmost row (using the row count, scroll offset and viewport size) and then traversing up or down until the correct row is found. Alternatively a binary search algorithm could be used.

But I'm not really sure, if this extra work for finding the row is actually worth it.

At least in my use case, I don't really care about the row that's at the top. I'm only interested in restoring the scroll position after navigating back to a route. I also can't really come up with a scenario in which I would want to know the topmost row.

I'm open for suggestions here.

But if we both can't come up with a good use case, I would propose a slightly different API:

##### `onScroll(scrollOffset: Number, event: Event)`

Called whenever the user scrolls (debounced).

- `scrollOffset` is the current scroll offset in px.
- `event` is the original scroll event.

##### `scrollTo`

- When set to a `Number` or `Number`-like `String`: scrolls to the specified position in px.
- When set to a `Row`: Finds the specified row and scrolls it to the center of the viewport.

This way we get the best of both worlds. It's now easy to serialize and restore the current scroll position, as well as scrolling a specific row into view.

**Comment by mohlek** [comment]
What iif the current scrollposition / top most row is not part of the initialy loaded data?

In that case only providing a `Row` interface for scrollTo wouldn't allow targeting that row.

**Comment by buschtoens** [comment]
@mohlek That's right.

When we additionally allow passing the scroll offset as a number (as proposed), we could instruct the component to keep fetching records until the specified scroll offset is reached. :upside_down_face:

**Comment by taras** [comment]
> At least in my use case, I don't really care about the row that's at the top. I'm only interested in restoring the scroll position after navigating back to a route. I also can't really come up with a scenario in which I would want to know the topmost row.

I think we should focus on `restoring the scroll position` use case. We can punt on tracking visible rows until we have a better rendering mechanism like `smoke-and-mirrors` or `ember-collection`. 

Is `scrollTo` going to be an action? If so, may I suggest 2 separate actions: `showRow` and `scrollTo`. `showRow` finds the specified row and scrolls it to the center of the viewport.. `scrollTo` scrolls to the specified position in px.

Thank you for taking this on :)

**Comment by buschtoens** [comment]
`scrollTo` is supposed to be an attribute / property of `{{lt-body}}`. Making it an action would mean that it can only be called from inside the context of the body or am I missing something?

I don't see a problem with breaking it up into two attributes, one for px offset and one for the row, as you suggested.

**Comment by offirgolan** [comment]
@buschtoens I think you're right, `showRow` and `scrollTo` should be properties of `{{lt-body}}`.
