### ISSUE TITLE
Problem scrolling with mouse

### ISSUE THREAD

**Issue by MarcoUmpierrez** [offirgolan/ember-light-table#155]
Dragging the scroll bar to go up or down in the table with the mouse has the problem that, when moving the mouse outside of the table area, the scroll bar gets glued to the mouse and will only be released after clicking again in one of the records.

**Comment by offirgolan** [comment]
@taras I am able to reproduce this on the demo page. 

Reproduction Steps:

1. Grab scrollbar with mouse
2. Scroll down
3. While still holding the mouse down, move the mouse outside of the table div and release 
4. Put the mouse back on the tbody and move it up and down (it should should still act as if you're holding the scrollbar)

**Comment by alexander-alvarez** [comment]
ember-scrollable has done the expected functionality since https://github.com/alphasights/ember-scrollable/commit/bbdd8a4d807d7128852d015c86daec0b0e91b14b and `v0.4.5` which is included if you install https://github.com/offirgolan/ember-light-table/releases/tag/v1.8.2 and up today (`^0.4.0`)
