### ISSUE TITLE
"elementResizeDetectorMaker is not defined" when `t.head fixed=true`

### ISSUE THREAD

**Issue by wilsonohyeah** [offirgolan/ember-light-table#158]
I'm seeing this in the latest version, 1.1.1. If I don't attempt to have the header render in a fixed position, everything is fine. Here's where I'm seeing that error occur from in my _vendor.js file:

```
  ...

  /* global elementResizeDetectorMaker */

  var error = _ember["default"].Logger.error;

  exports["default"] = _ember["default"].Service.extend({

    init: function init() {
      this._super.apply(this, arguments);
>>>>> this.detector = elementResizeDetectorMaker({
        strategy: "scroll"
      });
    },

  ...
```

Thanks in advance for any help with this!

**Comment by wilsonohyeah** [comment]
Also, this only seems to be happening when I use ember-light-table (ELT) from a custom addon that we're utilizing in our app; we have a wrapper component in our addon that has a number of functional and stylistic defaults for ELT which we then use in our other ember apps.

In our addon we've included ember-light-table as a normal dependency. However, if I add ELT as a dev-dependency in our app that consumes the addon, everything works great.

**Comment by offirgolan** [comment]
@wilsonohyeah this looks to be a problem with ember-scrollable. I have a PR for a possible fix
