### ISSUE TITLE
onScrolledToBottom is not triggered after replacing an empty result set

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#159]
In one case I use `ember-light-table` to display search results. When changing the search query, I first set the query and then reset the table like so:

```js
  resetTable(canLoadMore = true) {
    this.setProperties({
      pageNumber: 0,
      isLoading:  false,
      canLoadMore
    });
    this.get('table').setRows([]);
  }
```

This triggers `onScrolledToBottom` which in turn triggers `fetchRecords` which gets the query and performs the search.

```js
  fetchRecords() {
    this.set('isLoading', true);

    // ...

    this.get('store').query(modelName, request)
      .then((records) => {
        this.get('table').addRows(records);
        this.set('isLoading', false);
        this.set('canLoadMore', Ember.isPresent(records) && records.get('length') >= pageSize);
      });
  },
```

If the search does not yield any results, nothing much happens, as expected.

If the user then changes the search query, the whole process starts over and `resetTable` is called. However, `onScrolledToBottom` is *not* called again, because the `{{lt-infinity}}` does not re-enter the viewport.

Currently I manually issue the action with `this.send('onScrolledToBottom');` after resetting the table, but this feels clunky and potentially already triggers an uncalled for request for the second page.

Can I improve my logic or should `setRows` (etc.) always trigger the `onScrolledToBottom` action, if `{{lt-infinity}}` is in the viewport?

**Comment by offirgolan** [comment]
Hi there! 

I dont think you should depend on the `onScrollToBottom` action since it greatly depends on the current viewport. Instead, you should just call `fetchRecords` from `resetTable`.

One thing I would add as a precaution in `fetchRecords` is this:

```js
// Prevent multiple fetches from occurring
if(this.get('isLoading')) { return; }

... 
```

**Comment by offirgolan** [comment]
Im gonna go ahead and close this issue as it has been abandoned. Feel free to reopen.

**Comment by bargar** [comment]
@offirgolan my good sir, wrt:

> I dont think you should depend on the onScrollToBottom action since it greatly depends on the current viewport. 

Do you mean this specifically in this context of resetting the table or even for the general case of scrolling down and loading successive pages of data from the backend? If it's the latter, I would be very interested to hear the alternative to depending on `onScrolledToBottom`.

Thanks!
