### ISSUE TITLE
'Very-newbie' question on usage

### ISSUE THREAD

**Issue by suntrunda** [offirgolan/ember-light-table#161]
First of all I hope this is right forum for this question.  I have read the documentation and example several times, watched the video.  I must be making some fundamental newbie mistake that I could use some help.  Here is what I have done..

installed this component per the instruction

template:  app/template/application.hbs 

``` hbs
<h2>People Tracker</h2>
{{my-table table=model}}
{{outlet}}
```

created template-component:  app/templates/components/my-table.hbs:

``` hbs
{{#light-table table as t}}  <<I tried putting |t| but it did not help>>
  {{t.head}}
  {{t.body}}
  {{t.foot}}
{{/light-table}}
```

In Routes/application.js, I have:

``` js
import Ember from 'ember';
let myusers = [{
  head : 'XYZ', 
  body:['ee','ef'],
  foot:'ddd'}]
export default Ember.Route.extend({
  model(){   return myusers;   }    });
```

In //components/my-table.js:

``` js
// components/my-table.js
import Ember from 'ember';
import Table from 'ember-light-table';

const computed = Ember.computed;

export default Ember.Component.extend({
  model: null,
  table: null,

  columns: computed(function() {
    return [{
      label: 'First Name',
      valuePath: 'firstName',
      width: '150px'
    }];
  }),
  init() {
    this._super(...arguments);
    this.set('table', new Table(this.get('columns'), this.get('model')));
  }
});
```

Router.js - not changed since the tutorial demo

``` js
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('scientists');
  this.route('programmers');
});
export default Router;
```

I have installed all current versions.  The code compiles without any error - but nothing displays.

Please help..and Thank you

**Comment by angelomachado** [comment]
I hope it's not to late for an answer.
You are passing the model as table property and calling
```javascript
this.set('table', new Table(this.get('columns'), this.get('model')));
```
Just call {{my-table model=model}}. It should work

**Comment by suntrunda** [comment]
Thank you for response.  I am calling it {{my-table model=model}} in the application.hbs.  The above code is just in the my-table.js>init().  If i replace it there, it throw a lot of errors..  I will continue to try..thanks for the positive note that I am close :)  cheers..

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
