### ISSUE TITLE
Consuming ./addon/styles/addon.css

### ISSUE THREAD

**Issue by ChrisLincoln** [offirgolan/ember-light-table#179]
My tables are rendering, but in vanilla style. What is the general method for causing ember-cli to include your addon.css in my build?  I know how to import stuff using ember-cli-build.js. EmberApp has a 'bowerDirectory' property, but I don't see one for node stuff. For example, here is how I consumed the css for "bootstrap-editable:"

app.import(app.bowerDirectory + '/x-editable/dist/bootstrap3-editable/css/bootstrap-editable.css');

**Comment by offirgolan** [comment]
Are you trying to import the demo app's css? By default, ember-cli imports the `/addon/styles/addon.css` into your app.

**Comment by lypborges** [comment]
Hi, thanks for this addon. 

I'm also getting table without any style.

1. Do I need to import bootstrap for complete or just Tables etc...? 
2. Is there any doc about the style? 
3. Also, it's possible tu use it with https://emberobserver.com/addons/ember-css-modules or https://emberobserver.com/addons/ember-component-css for use with another addons that use semanticui or other frontend framework?

**Comment by offirgolan** [comment]
@lypborges are you trying to get the styles from the demo or just the base CSS styles?

**Comment by lypborges** [comment]
Sorry @offirgolan, I need to use with semantic ui. But with the same behaviour (responsive etc..) from de demo. So I think I should get only the base CSS style, right?

**Comment by offirgolan** [comment]
@lypborges the addon comes only comes with the base styles (not the ones found in the demo) needed for the table to be functional. If you want the demo styles, you can grab them from [here](https://github.com/offirgolan/ember-light-table/tree/master/tests/dummy/app/styles).
