### ISSUE TITLE
Resizeable Columns

### ISSUE THREAD

**Issue by dulichan** [offirgolan/ember-light-table#18]
Is there a way to drag and expand the size of a column? For example if the text of the column is too large to be seen?

Cheers~

**Comment by offirgolan** [comment]
You can set the `width` property when you define your columns

**Comment by Gaurav0** [comment]
I would like the user to be able to drag and resize the column. Thanks!

**Comment by offirgolan** [comment]
You would have to implement that yourself. Im not really sure how you would do that, but I can give you a starting point.

1. The width of table column is a bound property, meaning that if you change it programmatically, it will be rerendered automatically. 

    `table.columns.objectAt(0).set('width', '400px');`

    Maybe you can use an html5 slider type component that is bound to the width of the column to achieve this?

2. All header cells can be overwritten by custom components via the `headerComponent` property when you define your table.
