### ISSUE TITLE
multiple link-to per row

### ISSUE THREAD

**Issue by ChrisLincoln** [offirgolan/ember-light-table#181]
I think I can wrap my mind  around using onRowClicked to construct some complex transistionTo's. 
I think I can wrap my mind around using a cellComponent to construct a simple transitionTo. 
I am having a difficult time figuring out how to give the route that is consuming ELT the ability to build complex transitions: "/this-route/:this_id/that-rout/:that_id.

Using github's code explorer as an example, where one can click on  a file name or one can click on a commit comment, how would you do that in ELT?

**Comment by offirgolan** [comment]
@ChrisLincoln I would consider using [tableActions](http://offirgolan.github.io/ember-light-table/docs/classes/light-table.html#property_tableActions).

```hbs
{{#light-table table tableActions=(hash
  transitionTo=(route-action 'transitionTo')
) as |t|}}
```

That way you can handle all the transitions in the route instead of a cell component.

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned.
