### ISSUE TITLE
Error building app after installing addon

### ISSUE THREAD

**Issue by kcollignon** [offirgolan/ember-light-table#182]
After installing this addon I can't seem to get my app to build due to some compiling of stylesheets.

```
The Broccoli Plugin: [SassCompiler] failed with:
Error: File not found: /addon.sass
in any of the following include paths:
```

I am using version 1.1.0 on Ember 2.6.0

**Comment by offirgolan** [comment]
Are you installing this addon inside another addon?

**Comment by kcollignon** [comment]
@offirgolan No i am just installing it in an Ember CLI 2.6.2 app and importing light table in my component.

**Comment by offirgolan** [comment]
@kcollignon that's pretty weird. Did you do `ember install ember-light-table`? Or just `npm install`?

**Comment by kcollignon** [comment]
@offirgolan I did `ember install ember-light-table`. Not sure if this matters also but I am using `ember-cli-sass` with the `sass` extension option. I don't think that should conflict at all with the `addon.css` in this addon, but not sure. It seems maybe similar to #179

**Comment by offirgolan** [comment]
@kcollignon this is a fairly strange issue. Ill have to investigate this further. I believe `ember-scrollable` (a dep. of ELT) is using ember-cli-sass but I have never encountered such issues.

**Comment by offirgolan** [comment]
@kcollignon have you been able to replicate this issue? Any luck?

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
