### ISSUE TITLE
Need to bubble an action up to route/controller from a column's cellComponent...

### ISSUE THREAD

**Issue by romanchukenator** [offirgolan/ember-light-table#19]
...how does one do this? I've tried passing the action through the component, like so:

      {{#light-table table
        pickupTimeUpdated="pickupTimeUpdated"
        onScrolledToBottom=(action 'onScrolledToBottom')
        class="ui very basic table"
        scrollContainer='.table-scroll-container'
        as |t|
      }}

Nothing. I flailed and tried defining my action like onScrolledToBottom, too.

How'd I go about this?

**Comment by offirgolan** [comment]
I believe what you're looking for is [tableActions](http://offirgolan.github.io/ember-light-table/docs/classes/Light%20Table.html#property_tableActions)

**Comment by romanchukenator** [comment]
Awesome! Thanks man!

**Comment by offirgolan** [comment]
No problem! Im gonna go ahead and close this issue. Feel free to reopen if you run into any similar issues.
