### ISSUE TITLE
ember-composable-helpers addon incompatibility in 1.4.0

### ISSUE THREAD

**Issue by nmcclay** [offirgolan/ember-light-table#192]
I've described this issue in detail here:
https://github.com/DockYard/ember-composable-helpers/issues/231
https://github.com/martndemus/ember-font-awesome/issues/109

However I originally encountered the issue upgrading my ember-light-table dependency.  Considering that the addon only uses ember-composable-helpers in one place (that I can tell), would it be possible to remove its usage until the above issues are resolved?

Otherwise its not possible to include ember-light-table 1.4.0+ without breaking nested addons that require different included hook styles.

**Comment by offirgolan** [comment]
@nmcclay ember-composable-helpers was added as a dependency due to its need in future development of this addon. My suggestion is to not upgrade to 1.4 until this is resolved. I know that the developers at DockYard are pretty quick to respond and should get this issue resolved in a timely manner.

**Comment by nmcclay** [comment]
(fingers crossed)
