### ISSUE TITLE
Sorting performance

### ISSUE THREAD

**Issue by rhyek** [offirgolan/ember-light-table#195]
So, a basic way of sorting rows is having something like:
```js
rows: computed.sort('data', 'sortProps'),
table: computed('rows', function() {
  return new Table(this.columns, this.get('rows'));
})
```
The problem with that is every time rows is generated a new table is constructed and I've found this to be rather slow. 

I've tried other methods of sorting, and the one that makes most sense to me is have a static `rows` property with a separate observer that just does something like `this.rows.sort(...)`, but this doesn't fire observers on the array and the component will not update.

Any recommendations?

**Comment by offirgolan** [comment]
@rhyek this is where `enableSync` becomes handy 😜 

```js
rows: computed.sort('data', 'sortProps'),
table: computed(function() {
  return new Table(this.columns, this.get('rows'), { enableSync: true });
})
```
Note: This is only available in v1.4.0+
[See Docs](http://offirgolan.github.io/ember-light-table/docs/modules/Table%20Declaration.html#implicit-row-creation)

**Comment by rhyek** [comment]
Oh, damn. Sorry. Should've seen that. I'll try it out and close this in a bit. Thanks.

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned.
