### ISSUE TITLE
fetchRecords() does not work in component

### ISSUE THREAD

**Issue by MZein1292** [offirgolan/ember-light-table#197]
Hello

I see for the `fetchRecords()` function that you are using this.store.query('user')

```
  fetchRecords() {
    this.set('isLoading', true);
    this.store.query('user', this.getProperties(['page', 'limit', 'sort', 'dir'])).then(records => {
      this.get('model').pushObjects(records.toArray());
      this.set('isLoading', false);
      this.set('canLoadMore', !isEmpty(records));
    });
  },
```

this however does not work in a **component**, since I am passing the model into the component instead of injecting store.

what would the `fetchRecords()` function look like in a component where a model is passed to

`{{#light-table user=model}}{{/light-table}}`

```
  table: Ember.computed( function() {
    return new Table(this.get('columns'), this.get('user'), { enableSync: true });
  }),
```

**Comment by offirgolan** [comment]
In your component you would have to inject the store as a service.

```js
Ember.Component.extend({
  store: Ember.inject.service(),
  fetchRecord() {
    this.get('store'). query('user', ...)
  }
});
```

**Comment by MZein1292** [comment]
This has been done already. but it only made the model get repeated 3 times in the table, so if I had 2 rows and I add this, I will find 6 rows of the same first 2 rows repeated.

**Comment by angelomachado** [comment]
Are you using the onScrolledToBottom action? If so you must check canLoadMore property before fetching more records.
```javascript
    onScrolledToBottom() {
      if(this.get('canLoadMore')) {
        this.incrementProperty('page');
        this.fetchRecords();
      }
    },
```

**Comment by MZein1292** [comment]
The issue turned out to be that I needed to set some sort by and ordering on the Django side
