### ISSUE TITLE
Inconsistent Doc: lt-head

### ISSUE THREAD

**Issue by alexander-alvarez** [offirgolan/ember-light-table#198]
why are there three arguments being yielded here `|groups subColumns table|`,
https://github.com/offirgolan/ember-light-table/blob/master/addon/components/lt-head.js#L27

but only two here?
https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/lt-head.hbs#L5

**Comment by offirgolan** [comment]
@alexander-alvarez seems like I forgot to remove the table yield from the docs. My apologies. A PR with the fix is welcomed 😄

**Comment by alexander-alvarez** [comment]
np. wondering if there was something else that was intended
