### ISSUE TITLE
Exposing model for #link-to in each row.

### ISSUE THREAD

**Issue by snewcomer** [offirgolan/ember-light-table#2]
Great project by the way!  So much more I can get out of a grid with this add on.

So I am trying to figure out how each row could be wrapped with a link-to (if there already isn't one!). Not exactly sure, but does the row variable contain the model instance?  If so, would exposing the row variable in hash be one solution to this?

https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/lt-body.hbs#L7

**Comment by offirgolan** [comment]
You can use the `onRowClick` action which passes you the row that was clicked. From there you can do a transitionToRoute. Is that what you are looking for?

**Comment by snewcomer** [comment]
Yep!  I guess if I extend from the component class rather than the controller class, then I might run into some problems.  That's why a template link-to helper might be nice to expose.  

But now that I think about it, I probably shouldn't declare the table with a component class if I want some query params in the url as well.

**Comment by offirgolan** [comment]
You can always use the `tableActions` property to effectively propagate your actions.

See docs [here](http://offirgolan.github.io/ember-light-table/docs/classes/Light%20Table.html#property_tableActions)

**Comment by snewcomer** [comment]
Thx!
