### ISSUE TITLE
Show multiple model fields in one column

### ISSUE THREAD

**Issue by TraceSecuritySeanM** [offirgolan/ember-light-table#20]
Is there a way to show multiple model fields in one column? I don't want to use grouped columns but would rather show multiple model fields stacked in one column for each table row.

**Comment by offirgolan** [comment]
You can create a template under `templates/components/multiple-fields.hbs` and put whatever content you need to display

```hbs
{{row.field1}}
{{row.field2}}
{{row.field3}}
```

and in your column definition just add `cellComponent: 'multiple-fields'`

**Comment by TraceSecuritySeanM** [comment]
Thanks for the quick reply. I had the component defined in cellComponent but was failing to use row.content to refer to the field.
