### ISSUE TITLE
Doesnt know how to instantiate this addon!

### ISSUE THREAD

**Issue by talhaobject90** [offirgolan/ember-light-table#21]
Sorry to say that the documentation is not giving any idea how to use this in real project.

after installing the addon, i generate a custom component 'inventory-table'

put the template in some index.hbs
```
// inventory/index.hbs
 {{#light-table table onScrolledToBottom=(action 'onScrolledToBottom') as |t|}}
     {{t.head
       onColumnClick=(action 'onColumnClick')
       iconAscending='fa fa-sort-asc'
       iconDescending='fa fa-sort-desc'
       fixed=true
     }}

     {{#t.body canSelect=false height='64vh' as |body|}}
       {{#if isLoading}}
         {{#body.loader}}
           {{table-loader}}
         {{/body.loader}}
       {{/if}}
     {{/t.body}}
   {{/light-table}}
```

pasted this content in the newly created component 
```
//app/components/inventory-table.js
import Ember from 'ember';
import Table from 'ember-light-table';

const { isEmpty } = Ember;

export default Ember.Component.extend({
  page: 1,
  limit: 20,
  dir: 'asc',
  sort: null,
  table: null,
  isLoading: false,
  canLoadMore: true,

  columns: [{
    label: 'Avatar',
    valuePath: 'avatar',
    width: '60px',
    sortable: false,
    cellComponent: 'user-avatar'
  }, {
    label: 'First Name',
    valuePath: 'firstName',
    width: '150px'
  }, {
    label: 'Last Name',
    valuePath: 'lastName',
    width: '150px'
  }, {
    label: 'Address',
    valuePath: 'address'
  }, {
    label: 'State',
    valuePath: 'state'
  }, {
    label: 'Country',
    valuePath: 'country'
  }],

  init() {
    this._super(...arguments);
    this.set('table', new Table(this.columns));
  },

  fetchRecords() {
    this.set('isLoading', true);
    this.get('store').query('user', this.getProperties(['page', 'limit', 'sort', 'dir'])).then(records => {
      this.table.addRows(records);
      this.set('isLoading', false);
      this.set('canLoadMore', !isEmpty(records));
    });
  },

  actions: {
    onScrolledToBottom() {
      if(this.get('canLoadMore')) {
        this.incrementProperty('page');
        this.fetchRecords();
      }
    },

    onColumnClick(column) {
      if (column.sorted) {
        this.setProperties({
          dir: column.ascending ? 'asc' : 'desc',
          sort: column.get('valuePath'),
          page: 1
        });
        this.table.setRows([]);
        this.fetchRecords();
      }
    }
  }
});
```

initially it thrown 
```
ember.debug.js:16628Uncaught Error: An action named 'onScrolledToBottom' was not found in <zahid-staging@controller:dashboard/inventory/index::ember930>.
```
The i removed this function from component helper

but dont know where to put the instantiation code 
```
import Table from 'ember-light-table';
const table = new Table(columns, rows);
```
Tried in index controller , inventory-table.js(component file) , but it throws

```
ember.debug.js:16628Uncaught Error: Assertion Failed: [ember-light-table] table must be an instance of Table
```

May i get a clear picture of where to put these codes and how? I love this addon, but couldn't figure out how to use. please help

**Comment by offirgolan** [comment]
Im sorry you're running into some issues. To get a better understanding of how this table works, I suggest looking at the demo code for the demo page which can be found [here](https://github.com/offirgolan/ember-light-table/tree/master/tests/dummy/app). That will have working examples that you can use. If you have some more specific questions, please feel free to comment back and I can help you to the best of my ability.

**Comment by talhaobject90** [comment]
Thanks brother i will check the demo code

**Comment by roger-russel** [comment]
Someone should correct the documentation https://offirgolan.github.io/ember-light-table/docs/modules/Table%20Declaration.html  ...

**Comment by buschtoens** [comment]
@roger-russel where do you see a mistake?

**Comment by eliasabebe** [comment]
@talhaobject90  I am having the same issue. Did you resolve this? How? I looked at the demo page per the suggestion but couldn't find the solution. Thanks in advance for the help.

**Comment by edwinevans** [comment]
@offirgolan the problem is the demo page snippets only contain partial code so if you don't know how to use it already it's difficult to figure out how to put it all together. Is there any self contained fully working, simple example? (The examples in the tests for the project is close but I still can't figure out how to extract the parts needed to make a standalone version.)
