### ISSUE TITLE
Add summary/footer rows API [enhancement]

### ISSUE THREAD

**Issue by tibibud** [offirgolan/ember-light-table#212]
Hi,

if possible would a summary/footer row (that has a special custom component and is not subjected to sorting) make sense? It would give the possibility to use the Tables as financial tables out of the box. This is of course a feature/enhancement request. Would it make sense for you guys in terms of time/effort?

One can hack it with custom row components and row types and then sort without considering the summary row, however, is a clean solution (via the API) for this somewhere at some point in your development pipeline?

Thanks for the effort thus far!
Cheers,
T.

**Comment by offirgolan** [comment]
@tibibud you can easily override the table footer component with your own component. 

```hbs
{{#light-table table as |t|}}
  {{#t.foot as |columns|}}
    {{my-custom-summary-footer table=table columns=columns}}
  {{/t.foot}}
{{/light-table}}
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
