### ISSUE TITLE
Column ascending always true

### ISSUE THREAD

**Issue by Luisetelo** [offirgolan/ember-light-table#218]
Hi guys,

I'm having a problem ordering by columns, `column.ascending` is always `true`:

```
table: computed('model', function () {
    return new Table(this.get('columns'), this.get('model'), { enableSync: true });
  }),

  actions: {
    onColumnClick(column) {
      if (column.sorted) {
        const order = {
          order_sort: column.ascending ? 'asc' : 'desc',
          order_field: column.get('valuePath'),
        };
        this.get('onColumnClicked')(order);
      }
  }
```
The API is called on the route. I think when `model` is updated, a new table is created and the values of previous columns are lost.

**Comment by offirgolan** [comment]
> I think when model is updated, a new table is created and the values of previous columns are lost.

You are prolly right on this one. I would remove the table creation out of a CP and into `init`.

**Comment by Luisetelo** [comment]
I also tried to put the table creation only at `init`. However, the table is not updated when it receives the models from the route :(

**Comment by offirgolan** [comment]
What about something like this:

```js
init() {
 this._super(...arguments);
 this.set('table', new Table(this.get('columns');
},

onModelChange: observer('model', function() {
  this.get('table').setRows(this.get('model') || []);
})
```

**Comment by Luisetelo** [comment]
`setRows` doesn't update the table with the new rows. It uses a `setObjects` method from Ember.Array which I'm not sure it's KVO-compliant. I added a quick fix which works fine:
```
  setRows(rows = [], options = {}) {
    this.set('rows', []);
    return this.get('rows').setObjects(Table.createRows(rows, options));
  }
```
In the next days I will try to create a better solution with a PR ;)

**Comment by offirgolan** [comment]
@Luisetelo from some initial research, `setObjects` calls `replace` which is exactly what `pushObjects` does. The `replace` method then notifies the observing dependents. 

Try this instead and let me know if it works out:

```js
onModelChange: observer('model', function() {
  Ember.run.next(this.get('table'), 'setRows', this.get('model') || []);
})
```

**Comment by Luisetelo** [comment]
Yes, it works fine!

**Comment by offirgolan** [comment]
Fantastic! 😺
