### ISSUE TITLE
Tables responsive?

### ISSUE THREAD

**Issue by mmahalwy** [offirgolan/ember-light-table#219]
Can the tables be response for mobile optimized?

**Comment by offirgolan** [comment]
@mmahalwy as of right now, we dont have a good way of creating a responsive table. This is something that is on our backlog though so hopefully we should come up with a good solution sooner rather than later.

**Comment by offirgolan** [comment]
@mmahalwy there is PR open to support this 😺! I would love it if you gave it a test run before I merge it in.
