### ISSUE TITLE
Row component binding

### ISSUE THREAD

**Issue by haqllo** [offirgolan/ember-light-table#22]
Is there a concept to bind a different row component? I want to create different tables with different row components (one row component per table).

The Text within the row should be highlighted by classbinding.

Is there a different solution to realize this?

**Comment by offirgolan** [comment]
Im not sure I follow what you are trying to achieve. Can you give me a real world example?

**Comment by haqllo** [comment]
Of course. I want to set `color: red` via `classNameBindings`. The use case is to highlight a specific row depending on the content, for excample if the content is very important.

**Comment by offirgolan** [comment]
Ive added the ability to add custom class names in rows, columns and cells, as well as the ability to hide/show rows. Changes have been released to `v1.0.0-beta.3` 😺 (docs should be updated as well)

**Comment by haqllo** [comment]
Thanks!!
