### ISSUE TITLE
Custom attributes?

### ISSUE THREAD

**Issue by trumb1mj** [offirgolan/ember-light-table#225]
Is there a way to append custom attributes to a table, a row or a cell?

I'd like to do something like this:

```
  columns: computed(function() {
    return [
      {
        label: 'ID',
        valuePath: 'id',
        _blah: "12345"
      }
    ]},
    ...
```

with the resulting table html:

```<td blah="12345"></td>```

**Comment by trumb1mj** [comment]
So looking a little deeper, I guess I'd use a cell-type for this.  Now that I've established that, is there anyway to pass a model value into a cell-type component?

**Comment by buschtoens** [comment]
Not sure, if I understood you correctly, but besides`value` cells also get a [`row` property](https://offirgolan.github.io/ember-light-table/docs/classes/Base%20Cell.html#property_row) which allows you to access all model properties.

**Comment by lc4377** [comment]
row property is useful to get row data. But how to access that table like {{#light-table data=someObject}}{{/light-table}}. How to access 'data' in cell
