### ISSUE TITLE
CI: coverage job always fails

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#229]
You most likely noticed this yourself already, but just so we track this properly.

The coverage job always fails, as the process doesn't appear to terminate properly.

I don't know why this happens, but for now we could just disable this job, so we have working CI again.

**Comment by offirgolan** [comment]
👍 I'll turn off coverage until its working again. Its a know issue with ember-cli-code-coverage

**Comment by offirgolan** [comment]
Resolved in #234
