### ISSUE TITLE
Table cut with columns > screen width

### ISSUE THREAD

**Issue by HenryVonfire** [offirgolan/ember-light-table#23]
When the columns of the table are all set up with a fixed width and the sum of them is bigger than the screen width size, the table becomes scrollable on the x axis but the hidden content (the content of the columns that are out of the visible part of the table) is not rendered when scrolling on it.

**Comment by offirgolan** [comment]
Hmmm thats pretty weird. Any chance you can attach a screenshot?

**Comment by HenryVonfire** [comment]
Sure, here it is: 

![table](https://cloud.githubusercontent.com/assets/10612765/15537541/557b4fae-2277-11e6-83eb-e28ab890c9cb.png)

**Comment by offirgolan** [comment]
Thats odd. Are you sure this isnt some CSS issue?

**Comment by HenryVonfire** [comment]
I don't think so, I've created a new project without any CSS and I got the same result:
![table2](https://cloud.githubusercontent.com/assets/10612765/15603495/5d297408-23fb-11e6-9eb3-9cdb7b749e85.png)

**Comment by offirgolan** [comment]
Any chance you can share the source? That would make my debugging a little
easier 😁

On Friday, May 27, 2016, HenryVonfire <notifications@github.com> wrote:

> I don't think so, I've created a new project without any CSS and I got the
> same result:
> [image: table2]
> <https://cloud.githubusercontent.com/assets/10612765/15603495/5d297408-23fb-11e6-9eb3-9cdb7b749e85.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/offirgolan/ember-light-table/issues/23#issuecomment-222098326>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAjJwqT1LYx1ANgyhKH5jzWDw1baLqCDks5qFrTMgaJpZM4IlPdF>
> .
>


-- 
Thanks,
Offir Golan

**Comment by HenryVonfire** [comment]
Here it is (https://github.com/HenryVonfire/table-example). Hope it helps.

**Comment by offirgolan** [comment]
@HenryVonfire I released a fix with the latest version (`v1.0.0-beta.4`). Turned out to be some css `overflow` issue. This table (because of the way its structured) does not support x-axis scrolling. In your situation above, you would have to add a wrapper div with the following css to get it to work.

```css
.wrapper {
  overflow: auto;
  width: 1800px; /* 200px * numColumns */
}
```

**Comment by eddiesholl** [comment]
@offirgolan Just to clarify, does this mean if you have a 'dynamic' set of columns, there's no way the component can respond itself to the extra need for width? There's no way to just 'let it grow'? I guess you could simulate that effect by widening the wrapper width directly whenever the column set changes

**Comment by offirgolan** [comment]
@eddiesholl this issue is when all your columns have a fixed width (via the `width` property in the column definition) and the total width exceed the width of the parent container. If a column isnt given a `width` it will "just grow" just like if you were to write a standard html5 table.
