### ISSUE TITLE
Issue when sorting (column is always a new instance?)

### ISSUE THREAD

**Issue by corrspt** [offirgolan/ember-light-table#237]
Hi,

I just started experimenting with `ember-light-table` and I like it a lot, thanks for the effort on this 👍 

I have an issue that I cannot reproduce outside of my app, hoping that someone has an idea. I'm using Ember 2.8.2 and Ember Data 2.8.0 and Ember-cli 2.8 (happens in Chrome & Firefox, didn't test others) on OSX 10.10 (Yosemite)

I've setup a route with ember-light-table and I've enabled sorting on a column, which calls an action `onColumnClick` which is basically the same as the example (just calls a different data loading function).

```javascript
onColumnClick(column) {
      if (column.sorted) {
        this.setProperties({
          dir: column.ascending ? 'asc' : 'desc',
          sort: column.get('valuePath')
        });
        this.loadData(this.buildFilters());
      }
    }
```

When I click the column the value of `column.ascending` is *always* `asc`. I've tried digging in ember-light-tables source code and debug it, And i've found the following:

Whenever this code is called in `mixins/table-header.js` 

```javascript
onColumnClick: function onColumnClick(column) {
        if (column.sortable && this.get('sortOnClick')) {
          if (column.sorted) {
            column.toggleProperty('ascending');
          } else {
            if (!this.get('multiColumnSort')) {
              this.get('table.sortedColumns').setEach('sorted', false);
            }
            column.set('sorted', true);
          }
        }
        _emberLightTableUtilsCallAction['default'].apply(undefined, [this, 'onColumnClick'].concat(_slice.call(arguments)));
      },
```

The `column` argument is *always* a new instance with a new id (say `ember-756` then `ember-879`), but If I try to checkout the code for ember-light-table and run the example app, the instance is always the same, e.g `ember-650`) and everything works as I expected.
When I click the column, the sort icon appears briefly but then disappears, making it consistent with the "new column" instance.

Anyone has an idea what could be happening here?

**Comment by offirgolan** [comment]
I believe this to be a duplicate of #218

**Comment by corrspt** [comment]
Ah, damn... I did go through the issues and searched, but apparently with the wrong keywords. I'll check this out and report back (hopefully closing the issue). 

Thanks for such a quick reply :)

**Comment by offirgolan** [comment]
No worries. I honestly need to fix the demo / docs!

**Comment by corrspt** [comment]
@offirgolan, I confirm that this was the problem, thanks a lot for the help.

The demo/docs is the dummy app in tests directory, or do you have a different repo for that?
I'd like to help, but since I can't be sure when I'll be able to help, I would just like to know where to find the places that need fix.

Once again, thanks

**Comment by offirgolan** [comment]
No worries at all. Glad that fixed your issue. I believe @buschtoens is going to refactor the demo. Maybe he can add this in there as well? If not, I can do it later this week.
