### ISSUE TITLE
Make example app align with default ember-responsive breakpoints

### ISSUE THREAD

**Issue by corrspt** [offirgolan/ember-light-table#239]
Hi,

I know the responsive feature has just been released (I've been trying it out). One thing that caught me off-guard is that the example in the demo, uses the break points `xs, md, lg` but the default breakpoints generated by `ember-responsive` in the `app/breakpoints.js` file are named `tablet, mobile, desktop`.

I think that the demo app should also use these `tablet, mobile` so that when a user tries to setup their responsive table by copying parts of the demo it will work flawlessly 👍 

The example of the responsive table is very cool by the way.

**Comment by offirgolan** [comment]
Hi @corrspt! Thanks for opening this issue (glad you like the demo 😸). A PR is very welcomed in fixing this inconsistency. If not, I can take a go at it later this week.

**Comment by corrspt** [comment]
Might as well help out, [here it is](https://github.com/offirgolan/ember-light-table/pull/240)
