### ISSUE TITLE
height or max-height for the table height?

### ISSUE THREAD

**Issue by HenryVonfire** [offirgolan/ember-light-table#24]
`max-height` allows the table to get reduced if the rows don't fill the specified height. I don't know if someone would be interested on having their tables filling always the same height independently of the number of rows. Maybe would be interesting to have both options?

**Comment by offirgolan** [comment]
Although height is needed for fixed header/footer, it is not a required property. You can just add `height` and/or `max-height` via CSS by targeting the `lt-body-wrap` class.

**Comment by offirgolan** [comment]
@HenryVonfire Im gonna go ahead and close this issue. Feel free to reopen if needed.

**Comment by HenryVonfire** [comment]
Yes, I forgot to say anything. It worked without any problems, thanks!
