### ISSUE TITLE
Multi-row layout

### ISSUE THREAD

**Issue by csetera** [offirgolan/ember-light-table#242]
I'm trying to switch to ember-light-table to take advantage of the excellent API around paging and infinite scrolling.  We have a current HTML table implementation that uses two HTML row's for each "logical" model object row.  Within one of the columns, there is a "rowspan=2" setting and within one of the two rows, there is a colspan attribute.  Given the flexibility of this table, it seems like it should be possible to build something like this, but I'm struggling to figure out how to do it.  Are there any examples anywhere?  Are there any pointers you can offer to put something like this together?

Thanks,
Craig

**Comment by offirgolan** [comment]
@csetera any chance you can post a code snippet and maybe a screenshot of what this is actually supposed to look like?

**Comment by csetera** [comment]
Here's a snippet of the Handlebars template driving the layout.  

`<tr>
    <td rowspan="2">
      <input type="checkbox" checked={{selected}} onclick={{action "selectionChanged" value="target.checked"}}>
    </td>
    <td>{{row1col2value}}</td>
    <td>{{row1col3value}}</td>
    <td>{{row1col4value}}</td>
    <td>{{row1col5value}}</td>
    <td>{{format-date thedate timeZone='UTC'}}</td>
</tr>
<tr>
    <td class="filename" colspan="4">{{row2title}}</td>
    <td>
        <a {{action 'previewAttachment' document.uid document.file}} class="icon preview"/>
        <a {{action 'downloadAttachment' document.uid document.file}} class="icon download" />
    </td>
</tr>`

And here's a chunk of the output:

<img width="723" alt="screen shot 2016-10-26 at 9 18 27 am" src="https://cloud.githubusercontent.com/assets/270739/19750091/f2011bbe-9bb3-11e6-8388-716a9854736f.png">

Let me know if this helps to better explain and what we can do to render something like this in Ember Light Table.

Thanks!

**Comment by csetera** [comment]
I was able to find a way to set up the HTML and CSS to achieve the same look/feel within a single HTML row, so this is no longer a necessity for me.
