### ISSUE TITLE
Problem with tableActions and expandable rows

### ISSUE THREAD

**Issue by Eusse** [offirgolan/ember-light-table#247]
Hey guys, have a table template defined as:
````
{{#light-table table
  height='65vh'
  tableActions=(hash
    callContact=(action 'callContact')
    editContact=(action 'editContact')
    deleteContact=(action 'deleteContact')
  ) as |t|}}
  
  ...

  {{#t.body
    classNames='table-responsive'
    tableClassNames='table table-bordered table-condensed'
    canExpand=true
    multiRowExpansion=false
    onScrolledToBottom=(action 'onScrolledToBottom') as |body|
  }}
    
    {{#body.expanded-row as |row|}}
      {{contact-row row=row}}
    {{/body.expanded-row}}

    {{#if isLoading}}
      {{#body.loader}}
        {{table-loader}}
      {{/body.loader}}
    {{/if}}

  {{/t.body}}

{{/light-table}}
````
And it's controller contains this actions:
````
  actions: {
    onScrolledToBottom() {
      ...
    },
    onColumnClick(column) {
       ...
    },
    deleteContact(id){
       console.log('deleting: ' + contact);
    },
    editContact(id){
       console.log('editing: ' + contact);
    },
    callContact(id){
       console.log('calling: ' + contact);
    }
  }
````
The expandable component template is
````
<button class="btn btn-info" type="button" {{action 'tableActions.callContact' row.id}}>Call</button>
<button class="btn btn-default" type="button" {{action 'tableActions.editContact' row.id}}>Edit</button>
<button class="btn btn-warning" type="button" {{action 'tableActions.deleteContact' row.id}}>Delete</button>

````
I followed the documentation [here](http://offirgolan.github.io/ember-light-table/docs/classes/light-table.html#property_tableActions) but i get several erros. 

It says specifically the action with no quotes, but i get `Error: Assertion Failed: You specified a quoteless path to the {{action}} helper which did not resolve to an action name (a string). Perhaps you meant to use a quoted actionName? (e.g. {{action 'save'}}).`.

If i add the quotes, i get `Error: <Ember.Component:ember987> had no action handler for: tableActions.callContact`.

Does it works only for a `cellComponent`? Any advise is appreciated.

Wow, that was a lot of text! Thank you beforehand for taking your time reading this and helping me out.

**Comment by offirgolan** [comment]
Hi @Eusse,

Looks like your problems are in the code below

```hbs
<button class="btn btn-info" type="button" {{action 'tableActions.callContact' row.id}}>Call</button>
<button class="btn btn-default" type="button" {{action 'tableActions.editContact' row.id}}>Edit</button>
<button class="btn btn-warning" type="button" {{action 'tableActions.deleteContact' row.id}}>Delete</button>
```

The actions should not be wrapped in quotes. It should be this instead:

```hbs
<button class="btn btn-info" type="button" {{action tableActions.callContact row.id}}>Call</button>
<button class="btn btn-default" type="button" {{action tableActions.editContact row.id}}>Edit</button>
<button class="btn btn-warning" type="button" {{action tableActions.deleteContact row.id}}>Delete</button>
```

**Comment by Eusse** [comment]
Hi @offirgolan, i tried that at first, but i get this error: `Error: Assertion Failed: You specified a quoteless path to the {{action}} helper which did not resolve to an action name (a string). Perhaps you meant to use a quoted actionName? (e.g. {{action 'save'}}).` when i click the row, the expandable component is not even appearing.

**Comment by offirgolan** [comment]
Oh I think I misread your initial post that this is regarding the **expanded** component. Since the expanded component is declarative we have no way to pass the tableActions to it / nor do we need to since all your actions are within the same scope. 

```hbs
{{#light-table table
  height='65vh'
  tableActions=(hash
    callContact=(action 'callContact')
    editContact=(action 'editContact')
    deleteContact=(action 'deleteContact')
  ) as |t|}}
  
  ...

  {{#t.body}}
    
    {{#body.expanded-row as |row|}}
      {{contact-row row=row callContact=(action 'callContact')  editContact=(action 'editContact') ... }}
    {{/body.expanded-row}}

  {{/t.body}}

{{/light-table}}
```

If you dont want to rewrite the actions, you can use the `with` helper.

```hbs
{{#with  (hash
    callContact=(action 'callContact')
    editContact=(action 'editContact')
    deleteContact=(action 'deleteContact')
  )  as |tableActions|}}

{{#light-table table tableActions=tableActions}}
   {{#t.body}}
    
    {{#body.expanded-row as |row|}}
      {{contact-row row=row tableActions=tableActions}}
    {{/body.expanded-row}}

  {{/t.body}}
{{/light-table}}
{{/with}}
```

**Comment by Eusse** [comment]
You sir, you are the best. I tested both solutions and both works. We may close this issue.

**Comment by offirgolan** [comment]
Haha glad to help 😸 !
