### ISSUE TITLE
Column.ascending get reseted when the model changes

### ISSUE THREAD

**Issue by karellm** [offirgolan/ember-light-table#248]
I would like to support sorting on the server. It basically means I need to overwrite the `model` every time a new column is selected for sorting. Here are reproduceable steps:

1/ Click a column, `column.ascending` is true, triggers a `model` fetch (via queryParams) > `model` is being replaced
2/ Click same column, `column.ascending` is still true, does not trigger a model fetch (because queryParams didn't change)
3/ Click same column, `column.ascending` is false, triggers a model fetch.

The issue is at step 2/. When I overwrite the `model` at step 1/, it looks like `column.ascending` gets reseted. 

Is that by design? Would you mind fixing this or would you accept a PR?

**Comment by corrspt** [comment]
You may want to check out if issues #218 or #237 help you out.

**Comment by karellm** [comment]
This indeed fixed my issues. My bad for the duplicate and thanks for the prompt support!

**Comment by corrspt** [comment]
Happy to help! Not part of the addon team though (in case you thought that), just a user that happened to encounter that bug a few days ago (and I'm subscribing the project, so I got the email with the new issue)
