### ISSUE TITLE
scrollBottom event when empty table

### ISSUE THREAD

**Issue by basz** [offirgolan/ember-light-table#255]
I'm getting events indicating I hit the bottom when the table is empty. This results in an incorrect page (initially it will load page 2). But also every time I clear the with `this.get('model').clear();`.

In you example I couldn't discover an initial load either, so... this might be expected behaviour?

**Comment by offirgolan** [comment]
> I'm getting events indicating I hit the bottom when the table is empty

This is expected behavior


> This results in an incorrect page (initially it will load page 2). But also every time I clear the with this.get('model').clear();

When you clear your model, you should also reset your page to its default value. [See here](https://github.com/offirgolan/ember-light-table/blob/master/tests/dummy/app/mixins/table-common.js#L59-L65)

**Comment by basz** [comment]
I get all of that, but how can these two scenarios be right?

1. component inits, page = 1
2. table is empty, so bottom event is triggered
3. page is incremented to 2
4. content is fetch for page 2

1. table is sorted, page is reset to 1 and content cleared
2. table is empty, so bottom event is triggered
3. page is incremented to 2
4. content is fetch for page 2

**Comment by offirgolan** [comment]
@basz has no correlation as to how you fetch data. All its doing is calling events when it needs to (i.e. onScrolledToBottom). If you look at the example I shared with you, after I reset the page to 1, I also call `fetchRecords` which will fetch page 1 and set the component in the loading state. 

If you want to stop it from fetching page 2 after that, you can add another safeguard in your `onScrolledToBottom` actions:

```js
if (this.get('canLoadMore') && !this.get('isLoading')) {
 // get more records ...
} 
```

**Comment by basz** [comment]
My point is that; that on init the page is incremented to 2 because of the bottom event *before* the fetchRecords method is called with page = 2, so on init you would miss page 1.

// mixins/table-common.js
```
import Ember from "ember";
import Table from "ember-light-table";

const {
  inject,
  computed,
  isEmpty,
  isPresent
} = Ember;

export default Ember.Mixin.create({
  store: inject.service(),

  page: 1,
  limit: 25,
  offset: computed('page', 'limit', function () {
    return Math.max(0, (this.get('page') - 1) * this.get('limit'));
  }),
  dir: 'asc',
  sort: null,
  filter: null,

  isLoading: false,
  canLoadMore: true,

  model: [],
  modelName: null,

  columns: null,
  table: null,

  init() {
    this._super(...arguments);

    let table = new Table(this.get('columns'), this.get('model'), {enableSync: true});
    let sortColumn = table.get('allColumns').findBy('valuePath', this.get('sort'));

    // Setup initial sort column
    if (sortColumn) {
      sortColumn.set('sorted', true);
    }

    this.set('table', table);
    console.log('init method page :', this.get('page'));
  },

  fetchRecords() {
    Ember.assert(Ember.isPresent(this.get('modelName')), 'Specify modelName property');
    console.log('fetchRecords for page: ', this.get('page'));
    this.set('isLoading', true);

    let query = {
      page: {
        offset: this.get('offset'),
        limit: this.get('limit')
      }
    };

    if (isPresent(this.get('sort'))) {
      query['sort'] = (this.get('dir') === 'desc' ? '-' : '') + this.get('sort');
    }

    if (isPresent(this.get('filter'))) {
      query['filter'] = {};

      if (Ember.$.isNumeric(this.get('filter'))) {
        query['filter']['accountNumber'] = this.get('filter');
      } else {
        query['filter']['name'] = this.get('filter');
      }
    }

    this.get('store').query(this.get('modelName'), query).then((records) => {
      this.get('model').pushObjects(records.toArray());
      this.set('canLoadMore', !isEmpty(records));
    }).catch(() => {
      this.set('canLoadMore', true);
    }).finally(() => {
      this.set('isLoading', false);
    });
  },

  actions: {
    onScrolledToBottom() {
      console.log('onScrolledToBottom');

      if (this.get('canLoadMore') && !this.get('isLoading')) {
        console.log(' - incrementingPage');
        console.log(' - call fetchRecords');
        this.incrementProperty('page');
        this.fetchRecords();
      } else {
        console.log(' - cant load more or still loading');
      }
    },

    onColumnClick(column) {
      console.log('onColumnClick');
      if (column.sorted) {
        console.log(' - call setProperties(page:1)');
        this.setProperties({
          dir: column.ascending ? 'asc' : 'desc',
          sort: column.get('valuePath'),
          page: 1
        });
        console.log(' - call model.clear()');
        this.get('model').clear();
        console.log(' - call fetchRecords');
        this.fetchRecords();
      }
    },

    onAfterResponsiveChange(matches) {
      if (matches.indexOf('jumbo') > -1) {
        this.get('table.expandedRows').setEach('expanded', false);
      }
    },

    onFilter() {
      if (this.get('isLoading')) {
        return;
      }

      this.setProperties({page: 1});
      this.get('model').clear();
      this.fetchRecords();
    },

    onClearFilter() {
      if (this.get('isLoading')) {
        return;
      }

      this.setProperties({filter: '', page: 1});
      this.get('model').clear();
      this.fetchRecords();
    }

  }
});
```

console output
```
init method page : 1
table-common.js:84 onScrolledToBottom
table-common.js:87  - incrementingPage
table-common.js:88  - call fetchRecords
table-common.js:46 fetchRecords for page:  2
```

unless you can find an obvious mistake on my part, I'll work around it by setting page to -1 for now...

**Comment by offirgolan** [comment]
OHHH okay I see what you mean. This is happening on the demo page as well (nice catch). Before I updated the demo app, I had the initial page come from the route so that's why it was working fine. Honestly the easiest fix is to just set the initial page to 0. 

1. Page is set to 0
2. onScrolledToBottom is called
3. Page incremented to 1 and fetchRecords is called
4. ...

Then when you sort:

1. Clear rows
2. reset page to 0
3. onScrolledToBottom will get called
4. Page incremented to 1 and fetchRecords is called
5. ...

**Comment by basz** [comment]
Yep, sounds sane. 
Thanks
