### ISSUE TITLE
Tables with fixed headers can't be scrolled horizontally

### ISSUE THREAD

**Issue by hoboman313** [offirgolan/ember-light-table#264]
Consider that you have a large table that's both wide ( lots of columns ) and tall ( lots of rows ). The optimal way to display this table would be with a fixed header. However, setting fixed on t.head seems to disable the horizontal scrollbar so that not all the columns may be seen if the table's width isn't large enough.

**Comment by alexander-alvarez** [comment]
https://github.com/offirgolan/ember-light-table/pull/222

**Comment by offirgolan** [comment]
Resolved in #222.
