### ISSUE TITLE
Is it possible to create expandable rows with additional table data?

### ISSUE THREAD

**Issue by Gaurav0** [offirgolan/ember-light-table#27]
Example:

    Region           First Name      Last Name    Sales
    ---------------------------------------------------
    - All            Offir           Golan          100
    + All            Gaurav          Munjal         125
    -  N America     Gaurav          Munjal          25
    -  Europe        Gaurav          Munjal         100

**Comment by offirgolan** [comment]
As of right now, this sort of feature has not been implemented. One thing you can do is nest another table in the `expanded-row` and use some CSS to do the indentation. This feature is on the backlog so hopefully I'll get some time soon and make this happen. 

```hbs
{{#light-table table as |t|}}
  {{t.head }}

  {{#t.body canExpand=true multiRowExpansion=false as |body|}}
    {{#body.expanded-row as |row|}}
      {{#light-table table as |t|}}
        {{t.body}}
     {{/light-table}}
    {{/body.expanded-row}}
  {{/t.body}}
{{/light-table}}
```

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned.

**Comment by jamesjhedley** [comment]
I have to second that this would be a great feature. Not sure why it was abandoned. Subset rows seems like the natural use case for expandable rows. Is there no way to accomplish this today without trying to mimick the current table inside the expandable row? @offirgolan

**Comment by buschtoens** [comment]
#243 😉
