### ISSUE TITLE
sorting bug in examples

### ISSUE THREAD

**Issue by jamesdixon** [offirgolan/ember-light-table#271]
Hi again,

I discovered a small bug in the examples with regards to sorting. 

If all results have been loaded and you attempt to sort, the table goes blank. You can reproduce this by scrolling to the very end on one of the demo tables and then attempting to sort.

The issue appears to be the fact that after the model is cleared in the `onColumnClick` action, the `canLoadMore` flag is never toggled to `true` to allow the data to be reloaded.

Working version:

```js
    onColumnClick(column) {
      if (column.sorted) {

        this.setProperties({
          sort: column.ascending ? column.get('valuePath') : `-${column.get('valuePath')}`,
          offset: 0
        });

        this.get('model').clear();
        
        this.set('canLoadMore', true);
      }
```

**Comment by offirgolan** [comment]
Thanks for bringing this to my attention. Good catch 😄
