### ISSUE TITLE
Drag and drop doesn't work on IE

### ISSUE THREAD

**Issue by lonelyghost** [offirgolan/ember-light-table#273]
Tested on IE 11 latest on Windows 10. When you drag a column you see a circle with a line through it, and dropping has no effect.

**Comment by offirgolan** [comment]
Thanks for reporting this issue @lonelyghost, I am currently on vacation and wont be very responsive for the next two weeks or so. I will tackle this once I'm back 😄

**Comment by lonelyghost** [comment]
Okay! Let me know if you need help testing it against IE. I have a BrowserStack account.
