### ISSUE TITLE
onRowDoubleClick no longer fires when using Ember 2.10-beta.3

### ISSUE THREAD

**Issue by jamesdixon** [offirgolan/ember-light-table#274]
I was just testing my app with the latest Ember beta and I noticed that the `onRowDoubleClick` event no longer functions. There are no errors thrown in the console.

I realize it's a beta, but wanted to bring it up.

Also, I have not tested with other events, such as `onRowClick`.

Thanks again for a great addon!

_Note: I'm running ELT 1.6.1_

**Comment by offirgolan** [comment]
Thanks for reporting this issue @jamesdixon, I am currently on vacation and wont be very responsive for the next two weeks or so. If you're up for it, feel free to open up a PR or I can tackle this once I'm back 😄

**Comment by jamesdixon** [comment]
@offirgolan enjoy your vacation! 

I'll try and take a look once we transition to 2.10.

**Comment by offirgolan** [comment]
👍 sounds good thank you!

**Comment by offirgolan** [comment]
@jamesdixon is this still an issue after the official 2.10 release?

**Comment by jamesdixon** [comment]
@offirgolan yes, it does still seem to be an issue. I'm sorry I haven't had a chance to investigate further or create a test case

**Comment by offirgolan** [comment]
No worries. I'll see what I can do in the next week or two 😄

**Comment by offirgolan** [comment]
@jamesdixon I'm not able to recreate this issue in the demo app after upgrading it to Ember 2.10. The onRowDoubleClick fires correctly... any chance you can create a reproduction of this?

**Comment by jamesdixon** [comment]
@offirgolan thanks for the update. I'm going to make another attempt to upgrade my app over the weekend, so I'll see if I can't track down the source of the issue and attempt to reproduce. Thank you!

**Comment by jamesdixon** [comment]
No longer running into this :)
