### ISSUE TITLE
Horizontal Scroll instead of the current vertical Scroll.

### ISSUE THREAD

**Issue by iballack** [offirgolan/ember-light-table#275]
Is there already a build in feature to tackle horizontal scroll? I can see that currently the vertical /unlimited scroll had been implemented.

**Comment by alexander-alvarez** [comment]
it's dependent on `ember-scrollable` which currently does either/or, but not both.
in my down time I'm messing around with maybe getting it to do both horizontal and vertical scroll

there's a rudimentary PR out for horizontal scrolling
https://github.com/offirgolan/ember-light-table/pull/222

**Comment by offirgolan** [comment]
Resolved in #222.
