### ISSUE TITLE
Improve the UX for multiselect

### ISSUE THREAD

**Issue by karellm** [offirgolan/ember-light-table#289]
Hi,

I believe that multi-select the way it is shown in the docs is not very intuitive for non power users. Few people know about cmd+click or shift+click. In our product we implemented checkboxes:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/3J2v0w0i2W210X232C1j/Image%202016-12-15%20at%208.54.08%20AM.png?v=441f0e7a)

Beside adding a visual clue that rows are selectable, it offers the standard UI of "select all" that most people are used to. The issue now is that the user will select rows via the checkboxes but as soon as they click (by mistake or not) on anything, the entire selection is lost. It makes the UX very frustrating:

![](https://d3vv6lp55qjaqc.cloudfront.net/items/27081C1p2Y3c1A2K1a00/Screen%20Recording%202016-12-15%20at%2008.56%20AM.gif?v=95afd464)

I was wondering if you would consider more granular options for the multiselect. Basically I would like to avoid that clicking actually select or unselect anything. Clicking should not do anything. But I would like to keep cmd+click and shift+click for power users. Is that something you are willing to consider?

**Comment by offirgolan** [comment]
@karellm I think thats a good idea. I can see that sort of behavior being pretty useful. Feel free to create a PR or I can look into it in a couple days.

**Comment by jamesdixon** [comment]
@karellm do you have any code you could share for how you got the checkboxes to function like that? It's really nice and def a better implementation than the example

**Comment by buschtoens** [comment]
@jamesdixon I did something similar in my company's app. If I can squeeze it in, I'll extract the code into an addon.

**Comment by jamesdixon** [comment]
@buschtoens thank you! much appreciated!

**Comment by karellm** [comment]
@jamesdixon I cannot publish all the code but can give you a pointer:

- The select on each row relies on a simple select component that modifies the selection:

```hbs
{{input
  type="checkbox"
  checked=row.selected
  click=(action "click")
  doubleClick=(action "click")
}}
```

```js
import Component from '@ember/component';

export default Component.extend({
  actions: {
    click(event) {
      // NOTE so it does not trigger the click event on the row (which also
      //      manage row selection)
      event.stopPropagation();
    }
  }
})

```

- The select all is slightly more complex:

```hbs
{{input
  type="checkbox"
  checked=isChecked
  indeterminate=isIndeterminate
  change=(action "toggleSelection")
}}
```

```js
import { observer } from '@ember/object';
import Component from '@ember/component';

export default Component.extend({
  isChecked: false,
  isIndeterminate: false,

  selectionChanged: observer(
    'table.rows.[]',
    'table.selectedRows.[]',
    function () {
      const rows = this.get('table.rows.length');
      const selectedRows = this.get('table.selectedRows.length');
      this.set('isChecked', (rows === selectedRows) && rows);
      this.set('isIndeterminate', (rows !== selectedRows) && selectedRows);
    }
  ),

  selectAll() {
    this.get('table.rows').setEach('selected', true);
  },

  deselectAll() {
    this.get('table.selectedRows').setEach('selected', false);
  },

  actions: {
    toggleSelection() {
      if (this.get('isChecked')) {
        this.deselectAll();
      }
      else {
        this.selectAll();
      }
    }
  }
})
```

I hope this helps.

**Comment by jamesdixon** [comment]
@karellm thank you! This is fantastic. Going to give it a try this week. 

@buschtoens is this any different than your implementation?

**Comment by buschtoens** [comment]
I'm not using observers, but actions, and have a configurable `valuePath` as opposed to always watching `selected`. But other than that, it's pretty much the same.

```js
// light-table/columns/checkbox/component.js
import Column from 'ember-light-table/components/columns/base';
import { computed } from '@ember-decorators/object';
import mapBy from 'ember-awesome-macros/array/map-by';
import layout from './template';
import styles from './styles';

export default class CheckboxColumnComponent extends Column.extend({
  layout,
  styles,
  localClassNames: 'column'
}) {
  values = mapBy('table.rows', 'column.valuePath');

  @computed('values.[]')
  indeterminate = v => v.some((e, i, arr) => i > 0 && e !== arr[i - 1]);

  @computed('values.[]') value = v => v.every(Boolean);
}
```

```hbs
{{!-- light-table/columns/checkbox/template.hbs --}}
{{one-way-checkbox value
  local-class="checkbox"
  update=(action (get tableActions column.actionName) null column)
  disabled=(get row columnd.disabledPath)
  indeterminate=indeterminate
}}
```

```hbs
{{!-- light-table/cells/checkbox/template.hbs --}}
{{one-way-checkbox value
  local-class="checkbox"
  update=(action (get tableActions column.actionName) row column)
  disabled=(get row columnd.disabledPath)
}}
```

`{{one-way-checkbox}}` is deprecated, but swapping it with a native `<input>` shouldn't be much of a problem.
