### ISSUE TITLE
Pass multiple valuePath or entire object

### ISSUE THREAD

**Issue by rwwagner90** [offirgolan/ember-light-table#29]
Is it possible to pass multiple valuePaths or the entire object? I currently need two values to pass to my component for computing things.

**Comment by offirgolan** [comment]
In this situation, I would suggest creating a separate component and taking advantage of the `cellComponent` option in the column definition. You will have access to the entire `row` object in your template.

**Comment by rwwagner90** [comment]
@offirgolan thanks for the quick response! I did create a `cellComponent`, but I'm not sure how to get the value after that? Inside that `cellComponent` If I do `this.get('value')` it is undefined. Do I need to do `this.get('row')` or something? Is this documented?

**Comment by rwwagner90** [comment]
Looks like accessing `row.id` in my component works. I don't think I saw this documented anywhere though

**Comment by offirgolan** [comment]
@rwwagner90 better documentation is needed 😢 

In your custom cell component, you have access to `row`, `column`, and `value`. So you can do something like `this.get('row').get(this.get('column.valueINeedToGrab'))`

**Comment by rwwagner90** [comment]
@offirgolan perhaps I could help with some documentation?

**Comment by offirgolan** [comment]
Help is always welcomed! Feel free to open a PR 😺

**Comment by rwwagner90** [comment]
@offirgolan do the docs generate themselves based off of the JSDoc comments in the code? Not sure how to update them.

**Comment by offirgolan** [comment]
Yeah its YUIDoc that is auto generated. You can modify it directly in the source.

Use `ember s --docs` to build + run then navigate to `localhost:4200/docs` to view

**Comment by rwwagner90** [comment]
@offirgolan I added a little bit of clarification to the docs, not sure if the format I did works or not. Let me know. I put up a PR
