### ISSUE TITLE
Cookbook Page

### ISSUE THREAD

**Issue by offirgolan** [offirgolan/ember-light-table#292]
This issue is here to track what kind of examples to add to the cookbook docs page. Feel free to comment with suggestions 😄 

- [ ] Client side sorting (#288)
- [ ] Custom action bubbling via `tableActions`
- [ ] Paginated data (#299)
- [ ] Custom row implementations via `rowComponent`

**Comment by herzzanu** [comment]
Can we see an example of using custom actions when you click on a row and also having buttons with custom actions in a row's cell?

**Comment by offirgolan** [comment]
@herzzanu great idea!

**Comment by lypborges** [comment]
Hi, tks for this addon. It would be good if we have in the cookbook how to change a class conditional in a row. I read this https://github.com/offirgolan/ember-light-table/issues/62 but couldn't figure out  here to put this code and where the row came from.

**Comment by schickm** [comment]
Yeah, I'm a little confused about the hints mentioned in #62....I'm wondering how to make the row class computed from the row's model.  

I'm guessing you have to subclass `Row` so it computes  `classNames` based on the model...and then override `Table.createRow(..)` to create rows of your subclass?

Or is there some easier way that doesn't involve mucking about in private areas of the code?

**Comment by offirgolan** [comment]
> I'm wondering how to make the row class computed from the row's model.

@schickm not sure what you mean by this.

**Comment by schickm** [comment]
sorry @offirgolan, that was a pretty piss-poor explanation.  What I'm looking to do is something like this...

So when a given row is rendered with a content object like:
```
{ id: 3, name: 'Foo', status: 'active'}
```

It would look like:
```
<tr class='lt-row is-active>
    ...
</tr>
```

Vs. a row rendered with content like:
```
{ id: 3, name: 'Foo', status: 'deceased'}
```

It would look like:
```
<tr class='lt-row'>
    ...
</tr>
```

So to do that I figured you'd be using `classNameBindings` somehow.  My initial thought is to subclass the row component like so:
```
import Row from 'ember-light-table/components/lt-row';

export default Row.extend({
    classNameBindings: ['isActive'],

    isActive: Ember.computed('row.content.status', function() {
        return this.get('row.content.status') === 'active';
    }),
});
```

But what I can't figure out how to do is get a single instance of ember-light-table to use my custom row component.  I'm aware that I could just drop my component in `compontents/lt-row`, but then all instances of ember-light-table would be using my custom row for my entire application, which isn't desirable.  Ideally I'd like to opt-in for a single given table.

Hopefully that makes more sense 😉

**Comment by offirgolan** [comment]
@schickm you're on the right track with the javascript but you dont need to overwrite the current implementation since this is supported as public api via the [rowComponent](http://offirgolan.github.io/ember-light-table/docs/classes/t.body.html#property_rowComponent) option. 

```js
// component/my-row
import Row from 'ember-light-table/components/lt-row';

export default Row.extend({
    classNameBindings: ['isActive'],

    isActive: Ember.computed('row.content.status', function() {
        return this.get('row.content.status') === 'active';
    }),
});
```

```hbs
{{#light-table table as |t|}}
  {{t.body rowComponent=(component 'my-row')}}
{{/light-table}}
```

**Comment by schickm** [comment]
Ahhhh, totally missed `rowComponent`.  Thank you so much for the quick response!

**Comment by offirgolan** [comment]
@schickm no problem at all 😸

**Comment by SnehaSingh** [comment]
Thanks for this great add-on.

I am looking forward to the pagination example, to get ideas for my project where I am using Ember-light-table.

May I please request you to also include information about doing pagination where the data source is other than Ember-data  (like jQuery AJAX in my case)?

**Comment by offirgolan** [comment]
The cookbook page is now live! Thank you all for your great ideas 😸
