### ISSUE TITLE
width of table 140px after update 1.4.4 to 1.8.0

### ISSUE THREAD

**Issue by blset** [offirgolan/ember-light-table#293]
Hello,

the exact same code after upgrade to 1.8.0 truncates the table to a specified width coming from nowhere

here is the starting div with 1.4.4
`<div id="ember717" style="height: 1200px" class="ember-view ember-light-table">  `

here is the starting div with 1.8.0 with no change in code (except addon version substitution)
`<div id="ember2053" style="height: 1200px; width: 280px; overflow-x: auto" class="ember-view ember-light-table"> `

how is it possible to remove the  width: 280px; overflow-x: auto

PS I did an upgrade because version 1.4.4 does not work on IE 11

thanks

**Comment by offirgolan** [comment]
@blset the reason why you are getting `width: 280px; overflow-x: auto` is because thats the total width of all your columns. To remove this, you need make one of the columns have no set width so that it can grow / shrink when needed. What you are noticing is actually a fix that was added in v1.7.

**Comment by blset** [comment]
ok having removed the width of one of the columns let the table occupy all width but the free column gets all the space while others are shrinked to a minimum regardless of their width property which is expressed as for instance 
` {
                label:'Date',
                valuePath: 'updated_at',
                width:'30px',
                sortable: true,
                cellComponent: 'date-from-now'
            },
`


should the width be expressed in % maybe ?

**Comment by offirgolan** [comment]
@blset its really up to you on how you want to handle the column widths. If all the width are the same unit (i.e. px, em, %), then and only then ELT will sum the width and add the width + overflow style attributes. I would say play around with it and see what fits best. You can totally have some widths as px and others as % 😄

**Comment by blset** [comment]
ok thanks a lot

**Comment by offirgolan** [comment]
Np. Im gonna go ahead and close this issue, feel free to reopen it 😺
