### ISSUE TITLE
Tests die on `ember-scrollable` calling set on destroyed object

### ISSUE THREAD

**Issue by patrickberkeley** [offirgolan/ember-light-table#294]
I have [a PR open for this on `ember-scrollable`](https://github.com/alphasights/ember-scrollable/pull/30). It would be awesome if you could update `ember-scrollable` and cut a new release when/if that gets merged and released.

**Comment by offirgolan** [comment]
@patrickberkeley 👍 . Just let me know when a new version with your fix gets published.

**Comment by patrickberkeley** [comment]
Will do, thanks!

**Comment by offirgolan** [comment]
Fixed and released with `v1.8.2`.

**Comment by patrickberkeley** [comment]
👍
