### ISSUE TITLE
Pagination support 

### ISSUE THREAD

**Issue by sivakumar-kailasam** [offirgolan/ember-light-table#299]
Great plugin, will there ever be a pagination support out of the box with some configuration? Or can it be shown in the cookbook? It would be a great addition to have the page no captured as a query parameter if there was first class support for it.

**Comment by offirgolan** [comment]
@sivakumar-kailasam pagination will not be supported "out-of-the-box" as it is already pretty easy to implement. I can add an example in the cookbook though 😄 . 

Closing in favor of #292

**Comment by sivakumar-kailasam** [comment]
That would be sweet. Thanks for the awesome add-on 😎

**Comment by offirgolan** [comment]
@sivakumar-kailasam cookbook page is now live 😄

**Comment by sivakumar-kailasam** [comment]
@offirgolan Awesome 👍 Thanks for the followup notification.
