### ISSUE TITLE
Sticky Headers

### ISSUE THREAD

**Issue by knownasilya** [offirgolan/ember-light-table#3]
Any plans to implement sticky headers, so when you scroll you still see the column/group headings?

**Comment by offirgolan** [comment]
Hopefully yes! Ill keep this open for now as a reminder that I need to implement this :smile_cat:

**Comment by offirgolan** [comment]
This has been release with `v1.0.0-beta.0`. Feel free to test it out 😸  

Please note that there have been some structural changes and there might be even more in the near future (hence the `beta`)
