### ISSUE TITLE
Table doesnt work in ember-paper-dialog?

### ISSUE THREAD

**Issue by Moedav** [offirgolan/ember-light-table#301]
I am using the new Version of Ember-light-table and i am trying to create a selectable table in a ember-paper-dialog but it doesnt work. The body doesnt have the same size. In the background you can see the same component with the same properties and there it works fine.

![ember-light-table-issue](https://cloud.githubusercontent.com/assets/21080217/21567265/4355de94-ceab-11e6-9945-4028c7111793.PNG)

**Comment by buschtoens** [comment]
Are you using a fixed header? Can you post the relevant CSS that is
supposed to style the table?

**Comment by Moedav** [comment]
Ah ok the problem was the fixed header. I tried something and forgot to disable it. Thanks!
