### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by seawatts** [offirgolan/ember-light-table#304]
I'm getting a segmentation fault after installing ember-light-table

It looks like the issue might be with node sass.

I'm using the following versions

ember-cli: v2.10.0
node: v7.3.0

```
$ ember serve
Livereload server on http://localhost:49152
Serving on http://localhost:4200/
[1]    21186 segmentation fault  ember serve
```

**Comment by offirgolan** [comment]
@seawatts I dont think ember-cli fully supports node v7. I would downgrade to either node 6 or node 4.

**Comment by srjpfc** [comment]
i had a segfault just now after 'installing ember-light-table' and restarting ember:

ember-cli: 2.10.0
node: 6.8.1
os: darwin x64

**Comment by offirgolan** [comment]
@seawatts @srjpfc could this be a `node-sass` issue? Can you guys upgrade to the latest `node-sass` version on your machines and try again?

**Comment by srjpfc** [comment]
as i really needed to use ember-light-table i opted to do 'the other around'.
so i've removed all the non-default ember libs and introduced the others one by one.
ember-light-table is working so far and these are the libs that are not yet introduced.
maybe this can help @seawatts.

> "eonasdan-bootstrap-datetimepicker": "4.17.43",
> "emberx-file-input": "1.1.1",
> "ember-pop-over": "0.4.2",
> "ember-power-select": "1.0.3",
> "ember-profile-upload": "1.3.0",
> "ember-radio-button": "^1.1.1",
> "ember-remodal": "2.0.0",
> "ember-new-computed": "^1.0.3",
> "ember-modal-dialog": "^0.9.0",
> "ember-models-table": "1.11.0-beta.2",
> "ember-drop": "1.0.0",
> "ember-composability": "^0.3.7",
> "ember-cli-sass": "6.0.0",
> "ember-cli-foundation-sass": "2.0.0",
> "ember-cli-autoprefixer": "0.6.0",
> "ember-array-contains-helper": "1.3.1",
> "ember-bootstrap": "1.0.0-alpha.1",
> "ember-bootstrap-datetimepicker": "1.0.4",
> "broccoli-clean-css": "1.1.0",
> "ember-image-drop": "0.2.3",
> "ember-infinity": "0.2.8",
> "ember-key-responder": "^0.4.2",
> "ember-legacy-views": "0.2.0",

thanks for you help.

**Comment by Luiz-N** [comment]
I'm also having this issue with ember 2.10.2, node 6.3, and mac os 10.12.2

**Comment by offirgolan** [comment]
Are you guys still having this issue with Ember 2.11?

**Comment by Luiz-N** [comment]
I'm still on 2.10 and after basically doing a full purge and fresh install it seemed to have "fixed itself". I haven't tried deploying though so the bug may still exist.

**Comment by offirgolan** [comment]
Okay thats good to hear. Im gonna go ahead and close this issue, feel free to reopen if needed.
