### ISSUE TITLE
Fixed, scrollable header width does not match td in body

### ISSUE THREAD

**Issue by trumb1mj** [offirgolan/ember-light-table#305]
![image](https://cloud.githubusercontent.com/assets/928274/21621363/439a253e-d1be-11e6-9775-d1bfc7b6c267.png)

The really odd thing about this is, it's only present in firefox and not in every firefox browser...  Where does the code live that matches the fixed header column width?

**Comment by offirgolan** [comment]
Any chance you can recreate this in a twiddle or in a dummy app so I can attempt to debug this?

**Comment by trumb1mj** [comment]
I can't even recreate this on my machine.  A co-worker running osx sees this in firefox only.  Could be some sort of custom  font or something?  Where is the code that calculates these widths?

**Comment by trumb1mj** [comment]
So two of my co-workers were able to reproduce this behavior in your demo here:  http://offirgolan.github.io/ember-light-table/#/grouped

![image](https://cloud.githubusercontent.com/assets/928274/21650088/81cba1b0-d269-11e6-8d38-1a500766278c.png)

They both had the latest OSX and FireFox version.

OSX version:  10.12 (16A323)
FireFox:  48 and 50.1.0


I should note that I am NOT seeing this on the latest FireFox and an older OSX (10.11.6).

**Comment by offirgolan** [comment]
@trumb1mj I was able to track down this issue! It looks like this is actually an issue with ember-scrollable and its width detection algorithm. I opened up an issue on their end so we can track this. 

alphasights/ember-scrollable#34

**Comment by offirgolan** [comment]
Fixed and released with `v1.8.2`.

**Comment by trumb1mj** [comment]
Woot!  We just covered this today...  We're gonna have some happy managers!

**Comment by offirgolan** [comment]
Sweet! Glad to help out 😸 . Thanks for reporting this issue... I'm honestly unsure as to how this has gone unnoticed for so long.
