### ISSUE TITLE
Recommended approach for changing table header component?

### ISSUE THREAD

**Issue by SirZach** [offirgolan/ember-light-table#310]
I like that I can use `cellComponent` in the column definition to use my custom component for presentation and action handling. I need to replicate the same behavior in one of the `th`'s but I don't see as smooth of an approach.

It's recommended in the docs to make `t.head` a block component and taking care of everything yourself. That unfortunately involves reproducing a lot of code starting at https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/lt-head.hbs#L21.

How would you feel about being able to pass in a `headerCellComponent` instead?

**Comment by alexander-alvarez** [comment]
http://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_type for `<th>`
http://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_component for content of column header

@offirgolan  do you have the slides from the global ember meetup posted anywhere? This graphic is really helpful to augment the docs
![image](https://cloud.githubusercontent.com/assets/11779993/21894899/d71bb7c2-d8ae-11e6-80b5-95cbb8c6e79d.png)

**Comment by offirgolan** [comment]
@alexander-alvarez here is the [link to the slides](https://docs.google.com/presentation/d/1NYb-sVwpDio9Jo8W1Z-Ew10h6EPxuRFDmRgA25Mvxtw/edit?usp=sharing) 😄

**Comment by SirZach** [comment]
Thanks so much!
