### ISSUE TITLE
allow columns property to wait for promise to resolve

### ISSUE THREAD

**Issue by jaredgalanis** [offirgolan/ember-light-table#316]
I'm attempting to return the columns array in a promise in my columns computed property and it seems that ember-light-table won't allow that to happen. Is there a way to access the array returned by the computed property that I'm not seeing?

**Comment by buschtoens** [comment]
So basically you have something like this?

```js
{
  columns: computed(function() {
    return new Promise(/* ... */);
  }),

  table: computed('columns', 'data', function() {
    return new Table(this.get('columns'), this.get('data'));
  })
}
```

I'd consider handling promises out of scope for this addon.

I'd do something like this:

```js
{
  columns: null,

  table: computed('columns', 'data', function() {
    const columns = this.get('columns');

    return isArray(columns) ? new Table(this.get('columns'), this.get('data')) : null;
  }),

  fetchColumns() {
    yourPromise.then((columns) => this.set('columns', columns));
  }
}
```

And then call `fetchColumns()` appropriately, for example in `didReceiveAttrs()`.

In the template wrap the `{{#light-table table}}` in an `{{#if table}}`.

**Comment by jaredgalanis** [comment]
@buschtoens, thank you! I don't think I'm calling the fetchColumns properly because it's not being run. This is my didReceiveAttrs hook:

```  didReceiveAttrs() {
    this._super(...arguments);
    this.get('fetchColumns');
  },```

**Comment by buschtoens** [comment]
I assume you're doing something like this:

```js
columns: computed(function() {
  return this.get('store')
    .findRecord('table', 'my-table')
    .then((table) => table.get('columns'));
}
```

Instead you have to do this:
```js
columns: null,

didReceinveAttrs() {
  this._super(...arguments);
  this.fetchColumns();
},

fetchColumns() {
  return this.get('store')
    .findRecord('table', 'my-table')
    .then((table) => {
      this.set('columns', table.get('columns'))
    });
}
```

**Comment by jaredgalanis** [comment]
@buschtoens, I now have something a bit different. It's pretty much inline with your original suggestion:
```
  columns: null,

  table: computed('columns', 'data', function() {
    const columns = this.get('columns');

    return isArray(columns) ? new Table(this.get('columns'), this.get('data')) : null;
  }),

  fetchColumns() {
    yourPromise.then((columns) => this.set('columns', columns));
  }
```

**Comment by jaredgalanis** [comment]
So I needed to specify "this." before calling the fetchColumns function. Now the fetchColumn function is at least being called and there are no more assertions. Something strange is happening with my promise. This isn't part of the addon I realize.

I start with a set of statically set columns in the columns array and then I'm attempting to dynamically add columns using a chain of promises. 

```
fetchColumns() {

    var columnsArray = [{
     label: 'ID',
     valuePath: 'id'
    }, {
     label: 'Title',
     valuePath: 'description',
     width: '150px',
     resizable: true,
     minResizeWidth: 75
    }, {
     label: 'UOM',
     valuePath: 'unitofmeasure',
     resizable: true
    }, {
     label: 'QTY',
     valuePath: 'quantity',
     resizable: true
    }];

    var dynamicallyAddColumns = DS.PromiseArray.create({
      promise: this.get('requisition.items').then(function(items){
            items.forEach((item) => {
              item.get('responses').then(function(responses) {
                responses.forEach((response, index) => {
                  var response = response
                  response.get('user').then(function(user){
                    var columnObject = {
                      label: user.get('company_name'),
                      valuePath: 'quantity'
                    }
                    columnsArray.pushObject(columnObject)
                  })
                })
              })
            })
          })
    });

    dynamicallyAddColumns.then(() => {
      this.set('columns', columnsArray);
      console.log(columnsArray);
    });
  }
```
Only the 4 static columns show up in the table. When I log the columnsArray to the console it prints an array that has 8 objects, but it does seem to indicate only 4 in the initial specification:

![screen shot 2017-01-26 at 1 42 57 pm](https://cloud.githubusercontent.com/assets/6305935/22345254/6f689f3a-e3cd-11e6-825c-7d9927e0f397.png)

**Comment by offirgolan** [comment]
@jaredgalanis in your `table` CP you are creating a new table instance every time your data or columns change. I would advise to create your table instance on init and use `setRows` and `setColumns` to do what you want to do. For an example, please check out the dummy app code.

**Comment by jaredgalanis** [comment]
Thanks @offirgolan. I'm now creating the table instance on init and I start with the columns, table, and model properties all as null. Now, however, I'm getting an assertion when the table is being built:

```Uncaught TypeError: Cannot read property 'map' of null```

**Comment by jaredgalanis** [comment]
One further update is that I moved the table back into a CP because I need to be able to dynamically update the data source of the table based on input from the user (a select element). I am now finding that I have the same problem with the array when I first load the table, but as soon as I select another record to update the data source of the table any dynamically generated columns load correctly and the arrays that are logged do not have the same mismatch between their apparent contents and inspected contents.

**Comment by jaredgalanis** [comment]
Closing because I realize that this an issue with serially resolving the promises involved, not anything to do with ember-light-table itself.
