### ISSUE TITLE
Component integration tests failing in phantomjs

### ISSUE THREAD

**Issue by Syzygy24** [offirgolan/ember-light-table#329]
Any word on [this TODO here](https://github.com/offirgolan/ember-light-table/blob/b8fe4073593b2614ac9ba78d931c2450ca107598/tests/integration/components/light-table-test.js#L25)?

I'm trying to create component tests for my project using phantomjs and the test runs fine in the Chrome browser, but fails with phantom. The error is "TypeError: undefined is not a function (evaluating 'Number.parseInt(offset, 10)')" from [this](https://github.com/alphasights/ember-scrollable/blob/f956d5076077a1032b5306ffbffd4da8512b189e/addon/components/scroll-content-element.js#L156) function call in ember-scrollable

**Comment by offirgolan** [comment]
@Syzygy24 please check out #343
