### ISSUE TITLE
Double Render error with Ember 2.11 while scrolling

### ISSUE THREAD

**Issue by d-navas** [offirgolan/ember-light-table#331]
I'm getting a double render error using `Ember 2.11` and Latest version of `Light-Table` while scrolling with mouse click + scrollbar.

`Assertion Failed: You modified "targetScrollOffset" twice on <fsol@component:lt-body::ember9116> in a single render. It was rendered in "component:lt-scrollable" and modified in "component:ember-scrollbar". This was unreliable and slow in Ember 1.x and is no longer supported. See https://github.com/emberjs/ember.js/issues/13948 for more details.`

**Comment by offirgolan** [comment]
@d-navas can you try re-installing ELT (a new version of ember-scrollable was released to fix this issue)

**Comment by d-navas** [comment]
@offirgolan Thanks. I'll see if that works.

**Comment by d-navas** [comment]
Update: upgraded to LT 1.8.3. Problem fixed 🙂
