### ISSUE TITLE
Horizontal scrolling not working with fixed header

### ISSUE THREAD

**Issue by KeithClinard** [offirgolan/ember-light-table#335]
Horizontal scrolling works as expected without a fixed header.
When the header is fixed, the table will not scroll horizontally.

I've thrown together a quick example of what I am experiencing.
https://ember-twiddle.com/e47894f66485a28f54a4043b4720664d

**Comment by offirgolan** [comment]
@KeithClinard that is because you are overwriting the `totalWidth` property which is private. 

Do something like this instead:

```hbs
<div style="width:800px; overflow:auto">
  {{#light-table model.table2 height='400px' as |t|}}
    {{t.head fixed=true}}
    {{t.body}}
  {{/light-table}}
</div>
```

**Comment by KeithClinard** [comment]
That works.
Thanks for your time.

**Comment by offirgolan** [comment]
Great. No problem at all 😸
