### ISSUE TITLE
Foot row

### ISSUE THREAD

**Issue by karellm** [offirgolan/ember-light-table#339]
I would like the last row of my table to be a form to add a new entry to the table.

I started playing with the `foot` component and something like:

```hbs
{{#t.foot as |columns table|}}
  {{t.row newRecordRow columns
    elementId=newRecordRow.id
    table=table
  }}
{{/t.foot}}
```

where `newRecordRow` is defined in the component:

```js
import Table, { Row } from 'ember-light-table';

const newRecord = this.get('newRecord');
if (newRecord) {
  this.set('newRecordRow', new Row(newRecord));
}
```

That said, I have no luck so far. I would greatly appreciate a pointer if you have any idea how to render an extra row from a new record. Thanks!

**Comment by offirgolan** [comment]
@karellm the `t.foot` doesnt provide a `t.row` component. That is currently internal api. It is up to you to create the footer on your own with basic html. 

```hbs
{{#t.foot as |columns|}}
  <td>{{input value=newRecord.foo}}</td>
  <td>{{input value=newRecord.bar}}</td>
  <td>{{input value=newRecord.baz}}</td>
{{/t.foot}}
```

If you want to do it dynamically, you can iterate over the columns and use the `column.valuePath` attribute.

**Comment by karellm** [comment]
@offirgolan Thanks, I figured I was pushing my luck a bit. I will keep this open and post my solution when I have it running.

**Comment by karellm** [comment]
I realize that all the complication came from my attempts to abstract that into a component. I have a `base-table` component I wanted to add an option `footForm=true` to it. That's why I wanted to access the columns and row component.

In the end, I'm happy with hard coding it whenever I need it based on what @offirgolan suggested. Closing this for now
