### ISSUE TITLE
Error: Could not find module `ember-concurrency` imported from `bai-ui/mixins/table-common`

### ISSUE THREAD

**Issue by meliborn** [offirgolan/ember-light-table#349]
After installation getting error. Comes from table-common.js `import { task } from 'ember-concurrency';`

**Comment by offirgolan** [comment]
The demo depends on ember-concurrency to handle async tasks. Just run `ember install ember-concurrency`.

**Comment by alexander-alvarez** [comment]
or just `npm install` since it's in the `package.json` : https://github.com/offirgolan/ember-light-table/blob/master/package.json#L48

**Comment by meliborn** [comment]
@alexander-alvarez I did npm install, but without any luck, what is weird for me. Even with rm -rf node\bower\tmp. Only ember install helped.

**Comment by alexander-alvarez** [comment]
`rm -rf node_modules bower_components tmp dist && npm install && bower install` 
generally fixes anything related to fles and caches if everything is set up correctly.
I heard this referenced as a `nombomb` somewhere.. ember's version obviously.
https://www.npmjs.com/package/nombom
