### ISSUE TITLE
Access table object from column header component

### ISSUE THREAD

**Issue by eduardoweiland** [offirgolan/ember-light-table#35]
I want to create a table that has a checkbox in the first column for selecting/deselecting each row. This works fine since the `lt-row` component passes `row` object to the cell component.

However, I also need to have a checkbox in the header that selects/deselects all rows in the table. But for this I need to have access to the `table` object and all rows in it. The biggest problem is that the header checkbox should be updated as the rows are being selected by the user, e.g., if the user selects all rows in the table one by one, the header checkbox should also be checked.

There doesn't seem to be a way to know what rows are selected in the table from the header component. As a workaround, I am passing the table object inside the `tableActions` parameter, but I hope there is a better way for doing this.

This is my checkbox-header component:

``` js
// components/checkbox-header.js
export default Ember.Component.extend({
    tagName: 'i',
    classNameBindings: ['icon'],

    iconChecked: 'fa fa-check-square-o',
    iconUnchecked: 'fa fa-square-o',

    table: Ember.computed.alias('tableActions.table'),
    notSelectedRows: Ember.computed.filterBy('table.rows', 'selected', false),
    allSelected: Ember.computed.empty('notSelectedRows'),

    icon: Ember.computed('allSelected', function() {
        return this.get('allSelected') ? this.get('iconChecked') : this.get('iconUnchecked');
    }),

    click() {
        this.get('table.rows').setEach('selected', !this.get('allSelected'));
    }
});
```

**Comment by offirgolan** [comment]
This makes sense. Ill add a reference to the table in the next release
