### ISSUE TITLE
dynamic cellComponents 

### ISSUE THREAD

**Issue by JensNordenbro** [offirgolan/ember-light-table#356]
We have a solution with cellComponents. 

When a property is set on these components the idea is that the hbs will render a different content. 
In order to accomplish this I need to have direct access to the rendered cell components. I cannot find this in the documentation. Neither can I add bindings to my cellComponents since I only specifiy the "component-type-name". 
Is this possible or is there another path to take?

**Comment by offirgolan** [comment]
@JensNordenbro I'm not sure what you mean here. Are you trying to switch out the cell component to a different one on property change or just change the the cell component template?

**Comment by alexander-alvarez** [comment]
I think @JensNordenbro is asking what's the proper way to control changing the content of what's rendered in the cell... @JensNordenbro would expect to control what attributes go into the component, but from my understanding you can't control what is passed to a cell.

@JensNordenbro are you expecting certain values, and depending on the value you want to change something? You should be able to make your own column and cell types that do most if not all customization you need to show different data in a cell

**Comment by JensNordenbro** [comment]
@offirgolan It is the change of cell component template I was trying to acheive. I managed to solve it with a hack, then just redesigned the ui completely instead. 
I basically wanted to change the templete of the cell component on a complete row when clicking one of the cells in the row. Would be nice to know if there are more ways to do it other than switching data like @alexander-alvarez. However, l am not blocked. Thanks for your support!

**Comment by offirgolan** [comment]
> but from my understanding you can't control what is passed to a cell

You can add any property to your column definition and access it from your cell component.

```js
new Table([{
  cellComponent: 'my-c',
  foo: 'bar'
}]);
```

And then in your cell component you can access foo via `this.get('column.foo')`. 

@JensNordenbro if you can give me a concrete example of what you're trying to specifically do, I can help out more.

**Comment by JensNordenbro** [comment]
I'll try: 
Let one  cellComponent A-definition render a label if its foo property is true, but  an input box if it is false. 
Let one cellComponent b-definition trigger a (table)Action upon click on it. 
Let four columns on the table be of cellComponentA-type and the fifth one cellComponentB-type

In the tableAction change the foo to false on all cellComponents on the same row as the cellComponent clicked. ( preferrably by binding mechanism. )

**Comment by offirgolan** [comment]
@JensNordenbro were you able to solve your issue?

**Comment by JensNordenbro** [comment]
Let's close this one; I ended up redesigning the ui and I think I actually found a better phrased and answered question to the same problem somewhere among the issues. Thanks!
