### ISSUE TITLE
Upgrade to ember-cli 2.12 gives Error: Attempting to inject an unknown injection: 'service:media

### ISSUE THREAD

**Issue by rbkn** [offirgolan/ember-light-table#367]
Following attempted upgrade to ember-cli 2.12, ember-light-table causes the following on pages in which it worked with a previous cli version:
```
Error: Attempting to inject an unknown injection: 'service:media'
    at Registry.validateInjections (ember.debug.js:2574)
    at ember.debug.js:1696
    at runInDebug (ember.debug.js:6095)
    at Object.runInDebug (ember.debug.js:17757)
    at instantiate (ember.debug.js:1690)
    at DeprecatedFactoryManager.create (ember.debug.js:1839)
    at Proxy.create (ember.debug.js:1405)
    at CurlyComponentManager.create (ember.debug.js:12905)
    at OpenComponentOpcode.evaluate (ember.debug.js:47779)
    at VM.execute (ember.debug.js:54370)
```

Please remove this if this is already covered in the [Greenkeeper report for 2.12 - issue 364](https://github.com/offirgolan/ember-light-table/issues/364).

**Comment by pjcarly** [comment]
I have the same issue

**Comment by rbkn** [comment]
@pjcarly yep have done this too

**Comment by jamesdixon** [comment]
@offirgolan I can also confirm this issue w/ 2.12

**Comment by offirgolan** [comment]
Sorry for the delayed response. Been super busy the last couple of weeks. 

Is this an ember-responsive issue?

**Comment by rbkn** [comment]
It looks like ember-responsive throws the error as it's unable to initialize media service, but this only happens when it is created through the ember-light-table blueprint.  

As mentioned by @pjcarly, a workaround is adding the ember-responsive addon directly to the base project.

**Comment by offirgolan** [comment]
That's pretty weird. Has there been a change in API for installing an addon via init blueprint? 

Are you guys getting an error when doing `ember install ember-light-table`?

**Comment by rbkn** [comment]
Weird, I was unable to replicate this problem when setting up a new project in ember-cli 2.12.1  with a very basic ember-light table on a route (not the same as in the problem application within nested components).

I went back to the problem app I originally found it in after the upgrade (now on ember-cli 2.12.1) and tried removing the `ember-responsive` addon and refreshing all the addon libs
`npm uninstall ember-responsive --save-dev
npm cache clean
 rm -rf node_modules bower_components dist tmp
bower install
npm install;
` 
and the error returns.

It definitely only happened after upgrade to ember-cli 2.12.

**Comment by offirgolan** [comment]
@rbkn on your problem app, can you do the following:

```
npm rm ember-light-table
npm rm ember-responsive
ember install ember-light-table
```

**Comment by rbkn** [comment]
@offirgolan Boom, that has solved it.  I can't believe I didn't try this!  Thanks!

**Comment by Juraci** [comment]
@offirgolan I can confirm, I also have the same problem, ember-cli 2.12.1.
The following service
```@javascript
import Ember from 'ember';

export default Ember.Service.extend({
  ajax: Ember.inject.service(),
  
  authenticate(email, password) {
    return this.get('ajax').request('/some-uri', {
      method: 'POST',
        data: {
          email,
          password
        }
      });
  }
});
```
When I try to run the following unit test. 

```@javascript
import Ember from 'ember';
import { moduleFor, test } from 'ember-qunit';

moduleFor('service:authenticator', 'Unit | Service | authenticator', {
});

test('it delegates the post request to ajax service', function(assert) {
  const fakeAjax = Ember.Object.create({
    uri: null,

    request(uri) {
      this.set('uri', uri);
      return Ember.RSVP.Promise.resolve({ success: true });
    }
  });

  let service = this.subject();
  service.authenticate('foo', 'bar')
    .then(() => {
      assert.equal(fakeAjax.get('uri'), 'some-uri');
    });
});
```
I have this problem mentioned here:

```
http://localhost:7357/assets/test-support.js:5127:22: Attempting to inject an unknown injection: 'service:ajax'
        validateInjections@http://localhost:7357/assets/vendor.js:13816:93
        http://localhost:7357/assets/vendor.js:13116:54
        runInDebug@http://localhost:7357/assets/vendor.js:17337:9
        runInDebug@http://localhost:7357/assets/vendor.js:28999:43
        create@http://localhost:7357/assets/vendor.js:13108:29
        defaultSubject@http://localhost:7357/assets/test-support.js:6725:30
        http://localhost:7357/assets/test-support.js:6760:43
        http://localhost:7357/assets/tests.js:642:31
        runTest@http://localhost:7357/assets/test-support.js:1441:34
        run@http://localhost:7357/assets/test-support.js:1427:13
        http://localhost:7357/assets/test-support.js:1603:15
        advance@http://localhost:7357/assets/test-support.js:1112:26
        begin@http://localhost:7357/assets/test-support.js:2762:27
        http://localhost:7357/assets/test-support.js:1970:11
```
The solution proposed by @offirgolan did not work for me.
