### ISSUE TITLE
Don't show all page numbers at once

### ISSUE THREAD

**Issue by meliborn** [offirgolan/ember-light-table#370]
![](https://monosnap.com/file/PW1bcwZUtxnhenUlok7qhF1Eqf01yD.png)

**Comment by offirgolan** [comment]
@meliborn that was just a demo page showing how to paginate your records. It is up to you on how you want to display the page number on your app. You are totally welcomed to open up a PR with a more elaborate solution 😄

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
