### ISSUE TITLE
Updating to Yarn Issue

### ISSUE THREAD

**Issue by donaldwasserman** [offirgolan/ember-light-table#395]
Hello - 

Long time listener, first time caller. 

I updated to ember-cli 2.13 beta, and installed yarn as my package manager. I'm not sure why, but `ember-responsive` was removed as a dependency of my project during that conversion, so the media service was no longer available to ember-light-table. 

I resolved this issue with a `ember install ember-responsive.`

I don't personally understand really how the `this.addAddonToProject('ember-responsive');` part of blueprints work, but wanted to report this issue.

**Comment by buschtoens** [comment]
Sorry, but I can't seem to reproduce this. And even if, this would most likely be an issue with ember-cli / yarn itself.

You probably can't recall how you have performed the upgrade, can you? I would assume, that while diffing the `package.json`, you accidentally removed `ember-responsive`. :sweat_smile: 

Closing this for now, but if you (or anyone else) happens to stumble upon this again, feel free to leave a comment, ideally with the exact steps to reproduce this hiccup! :slightly_smiling_face:
