### ISSUE TITLE
Support `valuePath` leading to a promise

### ISSUE THREAD

**Issue by sergafts** [offirgolan/ember-light-table#401]
In one of my cells I am trying to display a value from a function that returns a promise, but it seems like
the object being displayed is the promise object.

Related code:

```
export default Ember.Component.extend({
  
  model: null,

  columns: Ember.computed(function() {
    return [
     ...
      {
        label: 'Price',
        valuePath: 'calculatedPrice',
        format: function(param){
          return param.then(function (data) {
            return data;
          });
        }
      },
    ];
  }),

  table: Ember.computed('row.servicebillings', function() {
    return new Table(this.get('columns'), this.get('row.servicebillings'));
  }),
});
```

and `calculatedPrice` is computed as

``` 
calculatedPrice: Ember.computed('customerservice', 'price', function() {
    let that = this;

    return this.get('customerservice.service.latestPricing').then(
      function(pricing){
        let price = null;
        if (that.get('price')){
          price =  that.get('price');
        }
        else if (pricing){
          price = pricing.get('price');
        }
        return price;
      }
    );
  })
```

In the rendered table I see `[object Object]` which I am assuming is the promise object. If I try changing `calculatedPrice` to return an arbitrary value (and the code in the cell's `format` function) I can see the content correctly in my cell.

If I understand correctly this means that the promise is not resolved, and I think I've done "my part".
Am I missing something?

**Comment by alexander-alvarez** [comment]
What you're observing is the default / expected behavior
```js
format: function(param){
          return param.then(function (data) {
            return data;
          });
```
since you're returning a promise here, as you've mentioned, and format isn't promise aware, then you get the promise object itself.

I could probably suggest some things you should do, but I don't think they'd be pretty. any reason you cant just block the table from loading until the data is resolved. Or similarly use the body loader?
http://offirgolan.github.io/ember-light-table/docs/modules/Component%20Declaration.html

**Comment by sergafts** [comment]
Blocking the table from loading would perhaps be the best solution. I am also thinking of using a custom 'cellComponent', wrapping the promise in `DS.PromiseObject` and resolving it there.

Any possible examples on how I could block the table? I am not sure how this is implemented..

**Comment by alexander-alvarez** [comment]
> Blocking the table from loading would perhaps be the best solution. I am also thinking of using a custom 'cellComponent', wrapping the promise in DS.PromiseObject and resolving it there.

That was one of the alternatives I was thinking. I would go this route if I were loading column data asynchronously and wanted to display loading indicators on columns, but show the data per each column as soon as it is available.

I would use the body-loader if I had one promise for the whole table or didn't want to show data until everything was loaded.

There's several ways to get the state of a promise ranging from lo-fi to hi-fi:
- Keep track of the state manually a la `.then((data) => { this.set('value', data); this.set('loading', false); })` :-1: 
- https://www.emberjs.com/api/classes/Ember.PromiseProxyMixin.html
- http://ember-concurrency.com/#/docs

**Comment by sergafts** [comment]
Thank you @alexander-alvarez. I will take a look at those. I will close this since it is not actually an ember-light-table issue. Or an actual issue, for that matter.
