### ISSUE TITLE
How to show indicator which columns are sortable

### ISSUE THREAD

**Issue by roberkules** [offirgolan/ember-light-table#403]
Hi,

I need to show a muted icon on each column that is sortable, how would I do this? (I think that's a fair requirement from a UX perspective)

Would I need to override some template?

Any help appreciated

**Comment by alexander-alvarez** [comment]
you can leverage the css classes
https://github.com/offirgolan/ember-light-table/blob/master/addon/styles/addon.css#L83
similarly if you can't achieve it in only css you can make a custom column type that leverages the `isSortable` property to do more complex things:
https://github.com/offirgolan/ember-light-table/blob/548cbf46350d243f1f8db25d15bc8403a4f3ec7c/addon/components/columns/base.js#L30

**Comment by offirgolan** [comment]
@roberkules this is how we do it in the demo app. Pretty straight forward 😄 

https://github.com/offirgolan/ember-light-table/blob/master/tests/dummy/app/mixins/table-common.js#L36-L38

**Comment by roberkules** [comment]
you pushed me in the right direction... used a bit of styling to make it work...

```
th.is-sortable {
  &:after {
    content: '\f0dc';
    font: normal normal normal 12px/1 FontAwesome;
    color: $text-muted;
    float: right;
    opacity: 0.3;
  }

  &:hover:after {
    opacity: 1;
  }

  &.is-sorted {
    &:after {
      content: '';
    }
  }
}
```

**Comment by offirgolan** [comment]
@roberkules thats great to hear! Im gonna go ahead and close this issue. Feel free to reopen if needed.
