### ISSUE TITLE
Cannot read property 'getProperties' of null

### ISSUE THREAD

**Issue by Gorzas** [offirgolan/ember-light-table#404]
I've just upgraded ember-light-table on my project and I've found that the tests of my projected have started to fail. After some searching I've found that the error is thrown at the [base cell component](https://github.com/offirgolan/ember-light-table/blob/v1.8.6/addon/components/cells/base.js#L29-L31):

```
style: computed('column.width', function() {
    return cssStyleify(this.get('column').getProperties(['width']));
  }),
```

This computed property breaks when the attribute column is set to null (as it is by default). It's a minor issue but it breaks the code and I thing that we can avoid these situations very easy. We have two options:
- Setting the attribute `column` to a default `Column` object instead null.
- Checking if `column` exists before resolving the computed property `style`.

What do you think?

**Comment by offirgolan** [comment]
@Gorzas why is the column being set to `null` in the first place?

**Comment by Gorzas** [comment]
@offirgolan The column is set to `null` by default.

I've been thinking that where it fails is in the cell tests, so maybe it would be better to improve the [blueprint](https://github.com/offirgolan/ember-light-table/blob/master/blueprints/cell-type-test/files/tests/integration/components/light-table/cells/__name__-test.js#L10-L13). 

```
test('it renders', function(assert) {
  this.render(hbs`{{light-table/cells/<%= dasherizedModuleName %>}}`);
  assert.equal(this.$().text().trim(), '');
});
```

The `it renders` is going to fail always because it doesn't pass a column to the component. :/

**Comment by buschtoens** [comment]
@Gorzas In the best case scenario `it renders` provides as minimal input to the component as possible. Even though it does not make any sense to invoke a cell without `column` and `row`, it could theoretically happen in some weird edge-case scenario, possibly crashing the whole Glimmer VM.

Therefore, instead of changing the test case, I would rather "fix" the getter in the actual implementation of `BaseCell`.
