### ISSUE TITLE
I need a simple tutorial

### ISSUE THREAD

**Issue by Jeorch** [offirgolan/ember-light-table#407]
I just started learning Ember,and I don't know how to use the ember-light-table,can you give me a simple tutorial,to help beginners.

**Comment by buschtoens** [comment]
Welcome to Ember.js!

Did you get a chance to take a look at the [demo page](https://offirgolan.github.io/ember-light-table/)?  
When you click then `</>` button in the top right, you can see the code that produces the table you're seeing.

![image](https://cloud.githubusercontent.com/assets/834636/26189354/8e22c2aa-3ba4-11e7-83b2-960563ba0426.png)
 
On that demo page, you'll also find a cookbook for more advanced problems. And last but not least, there's a great [API documentation](https://offirgolan.github.io/ember-light-table/docs/).

**Comment by Jeorch** [comment]
@buschtoens Thank you！Haha , I hadn't noticed it before.
