### ISSUE TITLE
Add a "hideable" option to configure if column can be hidden

### ISSUE THREAD

**Issue by eduardoweiland** [offirgolan/ember-light-table#41]
The `Column` class has the `sortable` option to configure if it can be sorted or not. It would be nice to also have an option to configure if the column can be hidden or not.

Having this option in the `Column` class will be useful to create a generic component for the user to choose the columns visible in the table, something like a list with a checkbox for each column in the table that can be hidden.

**Comment by offirgolan** [comment]
Hi @eduardoweiland, I think this would be a good addition. In the mean time, you can actually add whatever you want to the Column instance. Meaning any property you define will stick.

```js
const table = new Table([{ hidden: false, hideable: true, foo: true}]);
const hideableColumns = table.columns.filterBy('hideable', true);
const fooColumns = table.columns.filterBy('foo', true); 
```

**Comment by eduardoweiland** [comment]
Thanks @offirgolan, I didn't know this was possible.

Still, having a default value of `true` for all the columns and just set `false` for those columns that cannot be hidden would be better. I can test if the value is `undefined` and assume `true` in my component, but it will be easier to have a default value.
