### ISSUE TITLE
Reload Table and scroll to top

### ISSUE THREAD

**Issue by dmtask** [offirgolan/ember-light-table#412]
Hi,

i have a question. If I triggere the onScrolledToBottom action, the complete table reloads itself and scrolls again completely up (just because of the reload of the table). What do I have to do so that this does not happen and only the new elements are hung down?

(I have implemented the whole as described in the documentation.)

Thanks for your helps. :)

Daniel

**Comment by buschtoens** [comment]
Sounds like you're recomputing you `table` property upon model change. Could you share your code please?

Also, did you have a look at the demo page? The code snippets there are a great starting point. :)

**Comment by dmtask** [comment]
My Controller Code:
```
fetchRecords: task(function*() {
        const demModel = this.get('model').toArray();
        let offset = this.get('offset') + 100;

        let m = yield this.get('store').query('MODELNAME', { limit: 100, offset: offset });

        demModel.pushObjects(m.toArray());
        this.set('model', demModel);
        this.set('offset', offset);
    }).restartable()

onScrolledToBottom() {
            this.get('fetchRecords').perform();
        }
```

**Comment by buschtoens** [comment]
How's your `table` property defined?

**Comment by dmtask** [comment]
```
table: Ember.computed('model', function() {
        return new Table(this.get('columns'), this.get('sortedModel'), { enableSync: true });
    }),
```

sortedModel is the model for the Table.

**Comment by buschtoens** [comment]
You are defining `table` as a computed property in dependence of the `model` array property. That means, that when you replace the `model` array with a different array (`this.set('model', demModel);`) `table` property gets recomputed.

Please refer to the `table-common.js` code snippet on the [demo page](https://offirgolan.github.io/ember-light-table/) for the recommended way of setting up a table. :slightly_smiling_face:

**Comment by dmtask** [comment]
Ok, thanks for your help. :)
