### ISSUE TITLE
enableSync support for setRows

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#414]
Currently it's not possible to replace a table's synced array with a different synced array.

I suggest that when `{ enableSync: true }` is passed to the `Table` constructor, `setRows` should create a new `RowSyncArrayProxy`.

**Comment by buschtoens** [comment]
Use case: I have a component that displays a light-table, but does not manage the rows itself. Instead they are passed as an attribute. The passed rows array sometimes gets mutated (i.e. rows are added or removed) and sometimes is replaced with a new array (sorting, etc.).

**Comment by offirgolan** [comment]
@buschtoens using `setRows` to replace the sync array isnt ideal since that is not the expected behavior. Instead we should create a new method on the table instance such as `replaceSyncArray` which will create a new `RowSyncArrayProxy`.

**Comment by buschtoens** [comment]
While we're at it: do the row mutation methods (`addRow`, `insertRowAt`, `removeRow`, ...) all work as intended when `{ enableSync: true }` or (if not) are they intended to do so?

Maybe `setRowsSynced` would be a better suited name. On the one hand it would mirror `Ember.MutableArray#setObjects` and on the other it would make clear that `setRowsSynced` may be called even if the table was not initialized with `{ enableSync: true }`. What is your opinion?

I'm up for a PR. :)
