### ISSUE TITLE
Full source for examples ?

### ISSUE THREAD

**Issue by thornomad** [offirgolan/ember-light-table#415]
Hi there - sorry if it's obvious but is the full source for the example site available somewhere ?  Am new to Ember and wanted to read through the whole thing (rather than just the source code from the parts).

Thanks.

**Comment by alexander-alvarez** [comment]
@thornomad Welcome to Ember.
The full source is in the dummy app in this repo (as with most ember addon's with demos)
see:
https://github.com/offirgolan/ember-light-table/tree/master/tests/dummy/app
https://github.com/offirgolan/ember-light-table/blob/master/tests/dummy/app/mixins/table-common.js
the routes and templates folders will be helpful.
let us know how we can help

**Comment by thornomad** [comment]
Thank you!  I swear I check every folder except `test`.  I will walk through that.  Appreciate it.
