### ISSUE TITLE
table.isEmpty calculation is wrong.

### ISSUE THREAD

**Issue by mani-mishra** [offirgolan/ember-light-table#419]
I'm following the snippet from docs, for table's empty state,
```
{{#if table.isEmpty}}
      {{#body.no-data}}
        No users found.
      {{/body.no-data}}
    {{/if}}
```
But it doesn't seem to be working.
On debugging further, I noticed that even when there are no rows, ```table.isEmpty``` is not returning true.

This is how empty state is being calculated.
``` isEmpty: computed.empty('rows').readOnly(),```

but, rows are set as an ember object,
<img width="835" alt="screen shot 2017-06-02 at 11 05 31 am" src="https://cloud.githubusercontent.com/assets/3315240/26712154/f1e927cc-4782-11e7-8b6e-ed8ef0d75fd9.png">

```this.get('rows.content')``` is actually empty, not ```this.get('rows')```

Maybe the  ```table.isEmpty``` calculation needs to be modified to check ```rows.content``` emptiness.?

**Comment by buschtoens** [comment]
Thank you for reporting this issue. But I am afraid that you're having a different problem.

Based on the screenshot you provided, I assume that you have set `enableSync = true` and that we see [this piece of code](https://github.com/offirgolan/ember-light-table/blob/867b9803667c16842773c28bda6557afbcac1495/addon/classes/Table.js#L164-L167):

```js
  /**
   * @class Table
   * @constructor
   * @param  {Array} columns
   * @param  {Array} rows
   * @param  {Object} options
   *    - enableSync ( _Boolean_ ): If true, creates a two way sync between the table's rows
   *                                and the passed rows collection
   */
  constructor(columns = [], rows = [], options = {}) {
    super();

    let _columns = emberArray(Table.createColumns(columns));
    let _rows = emberArray(Table.createRows(rows));
    let _options = mergeOptionsWithGlobals(options);

    if (_options.enableSync) {
      _rows = RowSyncArrayProxy.create({
        syncArray: rows,
        content: _rows
      });
    }

    this.setProperties({
      columns: _columns,
      rows: _rows
    });
  }
```

> but, rows are set as an ember object, [...] `this.get('rows.content')` is actually empty, not `this.get('rows')`

This is incorrect. When you `enableSync`, `rows` is an [`Ember.ArrayProxy`](https://www.emberjs.com/api/classes/Ember.ArrayProxy.html). For Ember, an `ArrayProxy` appears as a regular array and all methods / properties are proxied.

You can actually verify this if you step into that constructor with the debugger and run:

```js
Ember.isEmpty(_rows);
Ember.isArray(_rows);
```

I've also created extra unit tests (#440) to assert this.

Can you please make sure that `rows` actually is empty, even though `table.isEmpty` is not? And if it is, please share the steps necessary to reproduce this.

Thank you.
