### ISSUE TITLE
Access params on table in cell Component

### ISSUE THREAD

**Issue by lc4377** [offirgolan/ember-light-table#420]
`{{#light-table table applications=applications tableActions=(hash edit=(action 'editApplication') }} {{/light-table}}`

`columns: computed(function(){
        return [ {
            cellComponent: 'expActions-cell'
        }];
})`

I am passing 'applications' property on table and i am using a component for cell. How to access that applications property in cell Component. When i see the cell in Ember Inspector, it doesn't have applications property' on it.

**Comment by alexander-alvarez** [comment]
if you set it as an attribute on the table technically it can be read by the cell.
https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/lt-row.hbs#L2

You could also add the data to the rows and read the `row`.

What exactly is the use case so we can give you better direction?

**Comment by lc4377** [comment]
When i look at Ember inspector, i can see 'applications' on light-table view but not on cell. 
<img width="636" alt="screen shot 2017-06-07 at 7 38 56 pm" src="https://user-images.githubusercontent.com/9434550/26910078-9c69f520-4bb9-11e7-87ac-92cd4d556746.png">
<img width="610" alt="screen shot 2017-06-07 at 7 40 20 pm" src="https://user-images.githubusercontent.com/9434550/26910079-9c6c87fe-4bb9-11e7-8303-1827ca7d7529.png">

i am passing rows like this const table = new Table(columns, rows, options); i got rows rendered in the table. A certain column should contain a link. the href of that link is contained in the application object of above 'applications' property. so i placed 'application' on {{#light-table table applications=applications}}{{/light-table}}

**Comment by alexander-alvarez** [comment]
In the column of links, does each row link to the same thing or are they different?

you're not going to be able to pass the attribute to `light-table` and have it propogate down.

**Comment by lc4377** [comment]
each row object (of type Test) has an appId (Test is created for an application). basing on the appId, i will take url from corresponding application Object with that appId. It links can be different for each row

**Comment by lc4377** [comment]
If i cannot propagate it down, could you suggest a way to achieve that

**Comment by alexander-alvarez** [comment]
> each row object (of type Test) has an appId (Test is created for an application). basing on the appId, i will take url from corresponding application Object with that appId. It links can be different for each row

ok this is good :smiley: 

can you add the applications data to the row objects themselves?
```js
const columns = [{valuePath: 'appId'}].map(o => Column.create(o));
const rows = [{appId: 123}, {appId: 456}];
new Table(column, rows, options);
```
then your row value would be `123` for the first row and `456` for the second row, etc.
You could generate the links before or do it in the cell if you like.

**Comment by lc4377** [comment]
could explain this line `const columns = [{valuePath: 'appId'}].map(o => Column.create(o));`

**Comment by alexander-alvarez** [comment]
@lc4377  I'm creating columns. same as 
`[Column.create({valuePath: 'appId'}), Column.create({valuePath: 'otherAttribute'})]`

**Comment by lc4377** [comment]
i am sorry i didn't understand where you added application data to row. Let me show you how data looks like. 
tests = [{id:1, appId:1}, {id:2, appId:2}]
applications = [{appId:1, url:'xyz.com'}, {appId:2, url: 'pqr.com'}].

I am using tests as rows. In the last column of row, instead of appId from test, i will show url corresponding to that appId from application object. Did you do the same?

**Comment by alexander-alvarez** [comment]
if you merge both objects like so:
```js
tests = [{id:1, appId:1, url:'xyz.com'}, {id:2, appId:2, url: 'pqr.com'}]
```

then you'll have access to the url by configuring the `valuePath` of the last column to be `url`
