### ISSUE TITLE
Implement "Smoke&Mirrors" (or similiar) in your ember-light-table

### ISSUE THREAD

**Issue by nelnico** [offirgolan/ember-light-table#425]
Previously I solved my slow rendering using smoke&mirrors  (since my tables can have quite a number of rows and columns)

However, with Ember Light Table  I could (and did) implement all the functionality (and more) that was requested (it's a truly awesome plugin!), but I'm back with my rendering problem.

I thought it's because of slow data retrieval, parked the "Issue" and looked at it today, only to realize the data "get there" pretty quick, but then there is a few seconds delay before the table appear.

Excuse any stupid questions (I'm not good at EmberJs), but is it possible to implement something like smoke&mirrors or "vertical-collection" inside one's light table?

**Comment by buschtoens** [comment]
This is already being discussed in https://github.com/offirgolan/ember-light-table/issues/12 :wink:

**Comment by alexander-alvarez** [comment]
Yes, definitely something we're trying to work towards. I updated that thread.
