### ISSUE TITLE
Demo doesn't work in IE11

### ISSUE THREAD

**Issue by mastastealth** [offirgolan/ember-light-table#427]
Just go to: http://offirgolan.github.io/ember-light-table/ in IE11 and you'll get...
![image](https://user-images.githubusercontent.com/1221228/27154931-d7cc7cee-5124-11e7-88c3-075ff5c5dd5d.png)

**Comment by buschtoens** [comment]
https://github.com/offirgolan/ember-light-table/issues/343#issuecomment-281059309
