### ISSUE TITLE
Performance (from a different angle)

### ISSUE THREAD

**Issue by nelnico** [offirgolan/ember-light-table#429]
I know there a few (one started by me also) questions regarding performance, but this is a bit of a different take.
 
Using the “performance” tools in chrome dev tools, we noticed the js heap/nodes and listeners keep climbing as one go from one view to another (all using ember-light-table), never comes down and there is a very noticeable decrease in performance as one go back and forth through the app (nearly *all* pages uses ember-light-table)
 
I noticed this seems to be an Ember thing, since a simple route getting data (same used in above), and rendering a plain table shows the same thing in the performance monitors, however not nearly as much nodes, etc get created and I guess that’s why not have such a huge impact on performance.
 
Isn’t there something one should do to “ditch” whatever was created on a page before transitioning to the next route?

**Comment by buschtoens** [comment]
Have you identified exactly which kinds of objects and listeners get created?

One thing I can recommend right away is unloading Ember Data records when you see fit. For example when they are removed from the table, or when you leave the route. 

Ember Data currently has no notion of garbage collection and will keep all records in the store until you explicitly unload them.

**Comment by nelnico** [comment]
I used the performance tab in Chrome Dev Tools

I'm trying to replicate all in a demo (since cannot share actual application publically)
I was wondering if the following not contribute to poor performance:
Users need to be able to copy the contents of cells, something ELT does not allow.
So I created a component that copies the content to a temporary dom element and from there to the clipboard.
Now ALL my columns are configured to use this component (cellComponent: 'grids/grid-contextmenu')

Guessing that was a bad idea to start with?  But how am I going to allow users to copy table cell contents  (like a normal html rendered table)

**Comment by buschtoens** [comment]
> Users need to be able to copy the contents of cells, something ELT does not allow.

ELT does not prohibit selecting and **Ctrl + C** / context menu copy.

I assume you want to implement a sort of *click to copy* to enhance UX?

> So I created a component that copies the content to a temporary dom element and from there to the clipboard.

You're possibly leaking here. We can't know without looking at the source code. Can you share the code of the `{{grids/grid-contextmenu}}` component?

> Now ALL my columns are configured to use this component 
 
Depending on what you're doing in that component, this can be a bad idea and negatively impact performance.

Just for kicks, use the default `cellComponent` by default again and see if your problems persists.

---

General tip regarding analyzing Ember.js render performance: If you have installed the [Ember Inspector](https://chrome.google.com/webstore/detail/ember-inspector/bmdblncegkenkacieihfhpjfppoconhi?hl=en) you can click on **Render Perfomance** which will give you detailed analytics of which components take how long to render.

This screenshot shows a rather slow tabe, taking a whopping `543.44 ms` to render initially.

![image](https://user-images.githubusercontent.com/834636/27331650-a8f25d78-55be-11e7-87b5-ffe7fef9ca8f.png)

**Comment by nelnico** [comment]
Thanks so much Jan, I'm doing a comparison first before continue with the sample app.  (first need to finish then deploy)

Not fancy to post so much code, but here is the code of my context menu component
 (it uses this jquery plugin: http://swisnl.github.io/jQuery-contextMenu/index.html)

```
import Ember from 'ember';

export default Ember.Component.extend({

    didInsertElement() {
        this._super(...arguments);
        Ember.$.contextMenu({
            selector: '.context-menu-one', 
            callback: (key, options) => {
                if(key === 'copyCell') {
                    let cellValue = options.$trigger.attr("data-value");
                    this.copyCell(cellValue);
                }            
            },
            items: {
                "copyCell":     {name: "Copy"},
                //"another":     {name: "Some Thing", icon: "copy"}
            }
        });
    }, 

    copyCell : function(cellValue) {
        var tempElement = document.createElement("textarea");
            tempElement.innerHTML = cellValue;
            document.body.appendChild(tempElement);
            tempElement.select();
            document.execCommand("copy");
            document.body.removeChild(tempElement);
    },

});
```

**Comment by nelnico** [comment]
I might have done this all for nothing!  
"ELT does not prohibit selecting and Ctrl + C / context menu copy."
In my case it does not allow that (which is all the users wanted), but IDIOT I am just assumed it's a ELT thing and did what I posted above.
It was my theme and it's css that caused that.....uurgh, sorry wasting your time!  Now just need to figure where I set that CSS in the first place (few late nights on this got me braindead)

**Comment by buschtoens** [comment]
Regarding your original issue of leaking listeners: you're calling `$.contextMenu({ ... })` *every single time* a cell is initially rendered. I don't know what this jQuery plugin does under the hood, but my guess is that it's registering some event listeners and whatnot.

Besides leakage, this is probably what's killing your render performance.

You're also not removing these context menus when a cell is destroyed. Again, I don't know whether `$.contextMenu` requires this, but your current code feels very wrong. But I feel that way whenever I see jQuery plugins mingled into Ember.js. :stuck_out_tongue: 

> It was my theme and it's css that caused that [...]

CSS properties that might be of interest to you:

- [`user-select`](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select)
- [`pointer-events`](https://developer.mozilla.org/en-US/docs/Web/CSS/pointer-events)

**Comment by nelnico** [comment]
@buschtoens , thanks so much man!

 I had some css overriding the default css for the table, and got it sorted there.

For what it matter, the same problem in the demo if multiselect=true

I just removed these from my css
```
.ember-light-table .lt-column.is-sortable {
  cursor: pointer;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}```

**Comment by buschtoens** [comment]
You're welcome.

Actually you mean [these styles](https://github.com/offirgolan/ember-light-table/blob/7e98dc6bd3f1c288537037a0fc8edd2def40ae5c/tests/dummy/app/styles/table.less#L9-L16) in the dummy CSS:

```css
.ember-light-table .multi-select {
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -moz-user-select: none;
  -ms-user-select: none;
  user-select: none;
}
```

As they are only part of the dummy stylesheet, they don't affect user's apps.

The [code sample you included in your comment](https://github.com/offirgolan/ember-light-table/blob/548cbf46350d243f1f8db25d15bc8403a4f3ec7c/addon/styles/addon.css#L82-L89) is responsible for preventing the selection of columns in table headers:

```css
.ember-light-table .lt-column.is-draggable,
.ember-light-table .lt-column.is-sortable {
  cursor: pointer;
  -webkit-user-select: none;
     -moz-user-select: none;
      -ms-user-select: none;
          user-select: none;
}
```

**Comment by nelnico** [comment]
Sorry yes
