### ISSUE TITLE
Example for server-side searching and sorting

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#433]
The cookbook currently only features an example for client-side searching. 

#423 shows that users can benefit from an example, where the filtering and sorting is done remotely by the server (API) and the rows are loaded in an infinite scroll fashion. 

Changing the search or sort parameters​ would replace the table's rows with the new results.

**Comment by offirgolan** [comment]
@buschtoens the demo page sorting is done via an API:

```
Mirage: [200] GET /ember-light-table/api/users?dir=asc&limit=10&page=1&sort=firstName
```

**Comment by buschtoens** [comment]
Oh yes, of course. :see_no_evil: 

As searching / filtering works analogous to sorting, do you think an additional example featuring a simple search form could still help users?

**Comment by offirgolan** [comment]
Haha no worries! And no, I think there are too many different stories around server/client side sort/search. 

If it's a simple case, there is no reason to add an example
If it's a complicated case, then it belongs on the server side (usually) which is beyond the scope of this project 😄

**Comment by buschtoens** [comment]
Got ya! :smile:
