### ISSUE TITLE
Add `cookbook.index` route to dummy app

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#443]
#441 introduces a link to https://offirgolan.github.io/ember-light-table/#/cookbook, but there's no index route yet.

A simple but neat list and maybe a few explanatory paragraphs will do just fine.

**Comment by bravo-kernel** [comment]
@buschtoens is this intended to be the page that shows a lot of examples, basically solving most "basic/newbie/starter" questions still open in this issue tracker? If so, I am willing to create a starting point (might need some help though).

I think this could be the ideal place to drop my end-user notes like "how to create a cell with a link", "how to get this damn table up-and-running" etc.

**Comment by bravo-kernel** [comment]
Looking at the index right now but I must say I am a bit confused and wondering if I interpreted this request correctly. Could you clarify what is expected here?

![image](https://user-images.githubusercontent.com/230500/37302679-80f66c30-262c-11e8-8265-40836c237617.png)

**Comment by buschtoens** [comment]
Just for the record, we spoke on Slack, but are there questions left? :)

**Comment by bravo-kernel** [comment]
No questions, expect a PR very soon.
