### ISSUE TITLE
Error trying to use table actions

### ISSUE THREAD

**Issue by wayne-o** [offirgolan/ember-light-table#447]
`You specified a quoteless path, `notifyUser`, to the {{action}} helper which did not resolve to an action name (a string). Perhaps you meant to use a quoted actionName? (e.g. {{action "notifyUser"}}).`

Ive copied the code verbatim from the cookbook to my app and I get the above - what would be the reason for that?

**Comment by yashprit** [comment]
@wayne-o Could you please tell me how you have resolved above issue, I am facing similar issue.

**Comment by alexander-alvarez** [comment]
@yashprit In ember if you have `{{action 'myAction'}}` in your hbs, then it looks for an action in your controller to link to said DOM element. If you copy and paste our demo examples' templates, you may need some JS in the controller or component where you use this table to acompany it (or get rid of the callbacks altogether)

**Comment by dcharles525** [comment]
I'm having a similar issue on 3.0.0-beta0. I have set everything up exactly how the cookbook showed but still no dice. 

simple-table.hbs
```
{{#light-table table height='65vh' tableActions=(hash
  deleteUser=(action 'deleteUser')
  openModal=(action 'openModal')
) as |t|}}
  {{t.head
    iconSortable='fa fa-sort'
    iconAscending='fa fa-sort-asc'
    iconDescending='fa fa-sort-desc'
    fixed=true
  }}
  {{#t.body
     canSelect=false
     as |body|
  }}
    {{#if isLoading}}
      {{#body.loader}}
        {{table-loader}}
      {{/body.loader}}
    {{/if}}
  {{/t.body}}
{{/light-table}}
```

user-actions.hbs
```
<div class="btn-group">
	<div      
		class="btn btn-primary" 
		{{action tableActions.openModal row bubbles=false}}
	>
		{{fa-icon "edit"}}
	</div>
	<div 
		class="btn btn-danger" 
		{{action tableActions.deleteUser row bubbles=false}}
	>
		{{fa-icon "trash-alt"}}
	</div>
</div>
```
