### ISSUE TITLE
Need `tableData` along with `tableActions` to pass down data to custom components

### ISSUE THREAD

**Issue by veberle-CSD** [offirgolan/ember-light-table#453]
Hi!

I am building out a custom component to use to display my column headers, so that I can filter table results by each column with an additional `{{input}}`.  I am able to successfully pass down an action to handle filtering on `key-up` for my filter input by doing:

```
{{#light-table table tableActions=(hash filterColumn=(perform filterColumn)) as |t|}}
```

I am using the `tableActions` approach, instead of the "curried components" approach laid out in [issue 405](https://github.com/offirgolan/ember-light-table/issues/405).  So I am also passing the initial filter values and state through `tableActions` as a workaround to have that information available to use in my custom column component (say that fast 5 times...).  It may be helpful in the future to split it out into actions and data so it could be done like this:

```
{{#light-table table 
    tableActions=(hash filterColumn=(perform filterColumn)) 
    tableData=(hash filters=filters) as |t|}}
```

Thanks for all your hard work!

**Comment by buschtoens** [comment]
IMHO this is a great addition as it mirrors / complements `tableActions`. However, users must be aware, that they need to [properly diff `tableData`](https://github.com/workmanw/ember-diff-attrs), if they want to react to state changes. Pure computed properties shouldn't require any diffing though. 

I can't think of any other performance implications as of now. 

@alexander-alvarez your opinion?

A PR will be greatly appreciated. 😊

**Comment by alexander-alvarez** [comment]
So kind of like the `extra` argument in `ember-power-select`?
> Object to store any arbitrary configuration meant to be used by custom components

I think it would be a :+1: feature

**Comment by buschtoens** [comment]
Exactly. 

@veberle-CSD up for a PR including tests? 😊 If you don't have the time, that's alright. I'll probably get around to it next week then.

**Comment by alexander-alvarez** [comment]
If we want to talk semantics: I think we should use `extra` instead of `tableData`, so we can organize around similar APIs to what people may be familiar with, that and in my mind I associate the rows as being the table's data.

**Comment by veberle-CSD** [comment]
@buschtoens Yeah, I can make a note to try and put together a PR with tests over the weekend and post it by next week.

@alexander-alvarez That sounds good!
