### ISSUE TITLE
classNameBindings to provide background color on cellComponent doesn't take up full cell

### ISSUE THREAD

**Issue by teddycoleman** [offirgolan/ember-light-table#455]
hello - first of all, I've been using ember-light-table and it's been super helpful. Thanks a bunch!

One use case that I've run into on a single cell is that I want to color the background under certain conditions.  I'm using classNameBindings to apply the class if the given condition is met.  However, because a cellComponent is wrapped in a div inside of the td tag (the class in the image below is 'exact-match'), it doesn't highlight the whole cell.

Is there a way to do this easily within ELT?  I can make it work if I have the div take up the whole cell, but it's a bit hacky.  Let me know if there's a way - thanks!

```
export default Ember.Component.extend({
  classNameBindings: ['testClass'],

  testClass: computed('row', function() {
    if (get(this, 'row.match')) {
      return 'exact-match';
    } else if (get(this, 'row.partialMatch')) {
      return 'partial-match';
    } else {
      return '';
    }
  }),
});
```

![image](https://user-images.githubusercontent.com/15386324/28134265-517c834e-66f7-11e7-87f8-6da529f08863.png)
![image](https://user-images.githubusercontent.com/15386324/28134521-1081a62a-66f8-11e7-96c3-0db2098e0b9e.png)

**Comment by buschtoens** [comment]
[Column.cellType](http://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_cellType) is what you're after. 😉

**Comment by alexander-alvarez** [comment]
@buschtoens  keeps beating me to the punch.

the images/slides linked to in https://github.com/offirgolan/ember-light-table/issues/310 give good context to this

**Comment by teddycoleman** [comment]
thanks a bunch! will close this issue
