### ISSUE TITLE
Call action when column is dragged

### ISSUE THREAD

**Issue by rennomarcus** [offirgolan/ember-light-table#459]
Hi,
I was wondering if it's possible to identify or to add an action when a column has it's position changed. (draggable set to 'true')

**Comment by buschtoens** [comment]
https://github.com/offirgolan/ember-light-table/pull/258

Do the `onColumnDrag` and `onColumnDrop` actions satisfy your needs? :slightly_smiling_face:

**Comment by rennomarcus** [comment]
Yup, I looked on the doc on the table session and column session. This can be found in the t.head session. Really sorry and thank you so much!

**Comment by buschtoens** [comment]
Absolutely no problem! Glad you're happy with ELT. :)
