### ISSUE TITLE
Browser shows vertical-scrollbar and I cannot figure out why

### ISSUE THREAD

**Issue by wuarmin** [offirgolan/ember-light-table#465]
Hello!
Thank you for this great addon! 👍  The table works great in our ember-applications, but now I have a case, where the browsers-default scrollbar is shown at table-body. If that happens width calculation fails and two scrollbars are shown. Here's a screenshot:

![grafik](https://user-images.githubusercontent.com/9987680/28456603-3875fad4-6e03-11e7-8b29-fbecbd4e14a3.png)

Maybe somebody can help!
Thank you!

**Comment by buschtoens** [comment]
Possibly a duplicate of: https://github.com/offirgolan/ember-light-table/issues/396

Can you please make sure that you are using the latest version of ember-light-table and ember-scrollable?

**Comment by wuarmin** [comment]
I use "ember-light-table": "^1.9.0".
ember-scrollable version is 0.4.9.

**Comment by buschtoens** [comment]
Ok, that is very weird. Which browser, version and OS are you on?

Does the [ember-scrollable demo](https://alphasights.github.io/ember-scrollable/) also look wrong?

**Comment by wuarmin** [comment]
Firefox 54.0.1 (64-Bit), Ubuntu 16.04.2 LTS 64-Bit

If I'm in fullscreen mode and the table is small enough, the second scrollbar isn't shown. After resize of the window the second sb is shown, although there'a a lot of space.

Do you understand following screenshot:
![grafik](https://user-images.githubusercontent.com/9987680/28457945-3e855a3c-6e08-11e7-9e66-acef6b1bcfa2.png)
Why can one scroll so far down?

**Comment by wuarmin** [comment]
Here's my code:

```javascript
import Ember from 'ember';
import Table from 'ember-light-table';
import { task, timeout } from 'ember-concurrency';

const {
  inject,
  computed,
  get
} = Ember;

export default Ember.Component.extend({
  model: Ember.A([]),
  isLoading: computed.or('fetchRecords.isRunning', 'setRows.isRunning').readOnly(),

  init() {
    this._super(...arguments);

    let table = new Table(this.get('columns'), this.get('model'), { enableSync: false });
    this.set('table', table);
  },

  columns: computed('', function() {
    return this.get('data.header').map((header) => {
      let selectionField = this.get('data.headerFields')[header];
      let width = get(selectionField, 'width');
      return {
        label: get(selectionField, 'label'),
        valuePath: header.toString(),
        sortable: false,
      };
    });
  }),

  fetchRecords: task(function*() {
    this.get('model').setObjects(this.get('data.rows'));
    yield this.get('setRows').perform(this.get('model'));
  }).on('init'),

  setRows: task(function*(rows) {
    this.get('table').setRows([]);
    yield timeout(100); // Allows isLoading state to be shown
    this.get('table').setRows(rows);
  }).restartable()
});
```
```
{{#light-table table
  height=height as |t|}}

  {{t.head
    iconAscending='fa fa-sort-asc'
    iconDescending='fa fa-sort-desc'
    fixed=true
  }}

  {{#t.body
    canSelect=false
    as |body|
  }}
    {{#if isLoading}}
      {{#body.loader}}
        {{table-loader}}
      {{/body.loader}}
    {{/if}}
  {{/t.body}}

{{/light-table}}


```

**Comment by buschtoens** [comment]
As far as I can see this isn't an issue with your JS / HBS code (though it has some minor unrelated issues).

The problems comes from `ember-scrollable` and / or CSS. Could you please post your CSS?

Ideally, could you whip up a demo app?

**Comment by wuarmin** [comment]
I'm using semantic ui as css-framework. I don't set any scss explicitly on ember-light-table. The style in my screenshots, is the out-of-the-box style of smui.

Yes, I'm going to provide a dummy-app, if necessary. But I cannot do it today.

**Comment by buschtoens** [comment]
Thank you. My guess is that Semantic UI somehow interferes with our styling. The template excerpt above is complete? You're not setting any further classes?

A demo app will be helpful. :)

**Comment by wuarmin** [comment]
Hey, you were right!! It was a well hidden css-class(with overflow-y: auto;) applied to a higher-ranking container.

Now my problem is solved. Thank you for your time and help. You guided me into the right way. 

**For future-readers:** If you have scrolling-problems, look at your browser's dev-tools to investigate your css-rules.

**Comment by buschtoens** [comment]
Thank you for the update! Glad you could solve it.
