### ISSUE TITLE
Migrate to RFC 176 style ES6 module imports

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#469]
https://github.com/offirgolan/ember-light-table/pull/467#discussion_r128832463
https://github.com/ember-cli/ember-rfc176-data

**Comment by rwwagner90** [comment]
I can do this, if no one has picked it up already?

**Comment by buschtoens** [comment]
Not that I am aware of. I would love that! <3

**Comment by rwwagner90** [comment]
@buschtoens should that PR that the comment was linked from be merged first?

**Comment by buschtoens** [comment]
#467 is almost purely cosmetical. IIRC I have not changed any imports. You can go ahead and base your PR off of master. :relaxed: 

I'll rebase mine, should we decide to enable Prettier.

**Comment by rwwagner90** [comment]
PR is up!
