### ISSUE TITLE
Revisit skipped tests

### ISSUE THREAD

**Issue by buschtoens** [offirgolan/ember-light-table#472]
We have some skipped tests. If I recall correctly, all were disabled because of PhantomJS quirks. Since #462 swapped PhantomJS for Chrome, we can give re-enabling these tests a try. :blush: 

Should they still fail, there's probably something wrong with the tests and we can attempt to fix these.

**Comment by baljeet03** [comment]
I am not able to find any skip tests. I am new to this so wanted to give a try on the test case fixed. Is it present in different branch?

**Comment by buschtoens** [comment]
Thanks for your commitment!

Yes, you are right. There are no skipped tests any more.
