### ISSUE TITLE
Customizable sort icon component

### ISSUE THREAD

**Issue by RedTn** [offirgolan/ember-light-table#478]
It would be nice if there were some properties we can pass into the content of this element here:
[https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/columns/base.hbs#L6](https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/columns/base.hbs#L6)
Materialize expects the element to be defined like this:
`<i class="material-icons">add</i>`
[http://materializecss.com/icons.html](http://materializecss.com/icons.html)

**Comment by RedTn** [comment]
- [ ]

**Comment by alexander-alvarez** [comment]
Should be able to accomplish this leveraging
http://offirgolan.github.io/ember-light-table/docs/classes/t.head.html#property_iconAscending
http://offirgolan.github.io/ember-light-table/docs/classes/t.head.html#property_iconDescending
and
http://offirgolan.github.io/ember-light-table/docs/classes/t.head.html#property_iconSortable

see the examples in the example app:
![image](https://user-images.githubusercontent.com/11779993/29539300-4427b23a-8697-11e7-875d-20298287a5a6.png)

**Comment by RedTn** [comment]
Right, but materialize also requires the content in that **i** tag in order to determine the icon to use.
So in my example, it requires:
`<i ...>add</i>`.
Ideally, we could do something like:
`{{t.head
...
iconSortable="material-icons"
iconSortableValue="add"}}`

**Comment by alexander-alvarez** [comment]
got it, now I understand.. I've never heard of anything like that, but I understand how it works.

In the meantime you can define your own column component that gets called [here](https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/columns/base.hbs#L2).
You can generate it with `ember g column-type <your_column_type>`
and set the http://offirgolan.github.io/ember-light-table/docs/classes/Column.html#property_type property on your columns passed into to light table.

I'm not sure if we would want to yet another property for icons or maybe make the icon component customizable all together. 

@buschtoens  any thoughts?

**Comment by buschtoens** [comment]
> I've never heard of anything like that, but I understand how it works.

Count me in. :smile: 

> I'm not sure if we would want to yet another property for icons or maybe make the icon component customizable all together.

I'm on the same page. We should rather add an `iconComponet` to the `TableHeaderMixin` and render it instead of the `<i>` tag, that was already getting a bit too complex anyways.

Absolutely in favor! :+1:

**Comment by RedTn** [comment]
PR Created: [#489](https://github.com/offirgolan/ember-light-table/pull/489)
