### ISSUE TITLE
cursor: col-resize for lt-column-resizer

### ISSUE THREAD

**Issue by Techn1x** [offirgolan/ember-light-table#480]
Currently it seems to be getting a `cursor: pointer;` applied to it, which isn't as UX friendly as a proper resize cursor is.

I've applied my own style to `.lt-column-resizer` to add the `cursor: col-resize` and it seems fine. I might get a chance to do a PR for it this week before I go on holiday, but if someone else beats me to it that would be great ;)

**Comment by buschtoens** [comment]
*In theory* that should already [be the case](https://github.com/offirgolan/ember-light-table/blob/master/addon/styles/addon.css#L95-L107). :thinking:

**Comment by buschtoens** [comment]
Do you have ember-hammertime installed by any chance? I would assume that it accidentally adds these styles: [Using Touch-action as a fastclick](https://github.com/html-next/ember-hammertime#using-touch-action-as-a-fastclick)

**Comment by Techn1x** [comment]
Looks like I do! It was installed as a dependency for ember-toggle. Now to figure out how to make it work nicely with ELT... :)

**Comment by Techn1x** [comment]
Closing this because it's a pretty niche issue and isn't really to do with ELT. Thanks for the tip about ember-hammertime

For anyone else reading this, there is more discussion here https://github.com/html-next/ember-hammertime/issues/31
