### ISSUE TITLE
Cells missing when table loaded in small window then expanded

### ISSUE THREAD

**Issue by stevenwu** [offirgolan/ember-light-table#49]
When I load the table in a small window,
![screen shot 2016-06-11 at 11 34 09 am](https://cloud.githubusercontent.com/assets/312446/15986850/a5361caa-2fc8-11e6-99cb-f4bcd9989b11.png)
then resize the window,
![screen shot 2016-06-11 at 11 34 26 am](https://cloud.githubusercontent.com/assets/312446/15986852/b3d2e4dc-2fc8-11e6-949c-32ef31e1509e.png)
cell values are missing.

**Comment by offirgolan** [comment]
@stevenwu I believe this issue has been resolved with the latest beta release.
