### ISSUE TITLE
[RFC] Allow to at row at specific index and let it return itself afterwards 

### ISSUE THREAD

**Issue by steffenbrem** [offirgolan/ember-light-table#5]
I came across a use-case where I needed to add a row to the beginning of the array. I've solved it by doing:

```js
let row = Table.createRow(attribute);
this.get('table.rows').insertAt(0, row);
```

It may be a good idea to make a proper public API to do this. I was thinking about `this.get('table').addRowAt(0, someObject)`. Or maybe change the argument signature of the `addRow` method by adding `idx` at the end, so you could do `addRow(object, 0)`.

As a side note, it might also be a good idea to return the created `Row` after calling `addRow`. This way you can manipulate `selected` and `expanded` directly after you've added it.

Thoughts?

**Comment by offirgolan** [comment]
Released in `v0.1.4` :smiley_cat:
