### ISSUE TITLE
Wait for table render to finish for printing

### ISSUE THREAD

**Issue by Techn1x** [offirgolan/ember-light-table#503]
So my current setup is I have a large set of records (lets say 500), which are paginated by the server so that I receive 50 per page, and I have these 50 records displayed in an ELT. There is a pagination bar to change pages and load the new page into ELT - this all works fine.

However I also need the ability to print this table, with ALL of the records,  when the user hits the Print button. I have managed to do several successive queries to obtain all of the records, and set the ELT to use this larger record set, and it takes about 5 seconds to render the complete table.

My problem is I need to somehow do a window.print() after this render is complete, and I have no way of knowing when the ELT table rendering is finished.

Is there an event hook for this? Or an alternate approach to what I am doing? Or a way to speed up the rendering?

Thanks!

**Comment by Techn1x** [comment]
Ok - I solved this pretty much at the same moment I hit post on the issue, sorry!

Essentially after I set the new data for the ELT, I then called;
`scheduleOnce('afterRender', this, () => { window.print(); });`

https://www.emberjs.com/api/ember/2.16/classes/@ember%2Frunloop/methods/scheduleOnce?anchor=scheduleOnce

Feel free to comment if you know any better ways to handle this

**Comment by buschtoens** [comment]
This is what I would do as well, yes. One nitpick: Using `scheduleOnce` for an anonymous (arrow) function does not make sense, just use `schedule`. :wink:

> and it takes about 5 seconds to render the complete table.

I feel your pain. In our app I progressively fetch and insert rows in chunks, while also displaying a progress indicator. This way the main thread stays responsive and the user knows what's going on.

**Comment by Techn1x** [comment]
Nice, thanks for the tips!

**Comment by Techn1x** [comment]
@buschtoens any chance I could see a code snippet of your fetch/insert progress indicator for this? It seems my approach to chunking the inserts still causes the main thread to get locked a fair bit during this process

**Comment by buschtoens** [comment]
Unfortunately I'm not permitted to share code snippets from work. But maybe I can still shoot something up ya. :wink:

But my general advice is: use ember-concurrency tasks for that and `waitForQueue('afterRender')`, where necessary.

**Comment by buschtoens** [comment]
Can't find the time right now to build an example, but with the new [encapsulated tasks](https://twitter.com/machty/status/926123457066225664), you can build an excellent abstract table row loaders including progress indicator. :muscle: 

Let me know, if you still need help with this.

**Comment by Techn1x** [comment]
Thanks, that's alright. I'm having to put some of this print stuff on the back-burner for now, since it mostly works, gotta fix some other things in our site. But hopefully I'll get some time to go over the table printing logic and implement ember-concurrency.... encapsulated tasks look perfect for this, I'm excited to implement them!

**Comment by Techn1x** [comment]
In case anyone visits this issue in the future, I ended up getting this done and it works well. Using ember-concurrency's encapsulated tasks and `waitForQueue('afterRender')` is working super well 💯  ember-concurrency has proved to be awesome for my webapp since coming across it!

Essentially the process is;
1. fetch page from backend
2. render page
3. `yield waitForQueue('afterRender')`
4. update progress bar
5. `yield waitForQueue('afterRender')`
6. repeat steps 1-5 for every page/table of data that needs to be rendered for print
7. wait for all images to be finished loading
```javascript
// Wait for ALL images to be loaded or failed (i.e. complete) - otherwise print page can have missing images sometimes
var allImages = document.getElementsByTagName('img');
for(var i = 0; !isNone(allImages) && i < allImages.length; i++) {
  // While image is not complete, wait for a while, and try the same image again
  if(!allImages[i].complete) {
    yield timeout(100);
    i--;
  }		
}
```
8. wait for all fonts to be loaded (using fontfaceobservers)
```javascript
// Tests to see if the circle icon (fa-circle) is loaded (indicating that the FontAwesome family has loaded).
yield fontAwesome.load('\uf111',5000)
```
9. `yield waitForQueue('afterRender');` just to be sure
10. `window.print();`
11. `window.close();` my print pages are always opened in a separate tab, so closing will release resources

While step 2 is occurring the page is unresponsive but I don't think there's much I can do about that. Turns out this ended up being a big advertisement for ember-concurrency :)
