### ISSUE TITLE
Vertical Collection: Wire up `firstReach`, `lastReached` events to light table's own

### ISSUE THREAD

**Issue by alexander-alvarez** [offirgolan/ember-light-table#508]
See https://github.com/html-next/vertical-collection#actions for reference

And our analgous http://offirgolan.github.io/ember-light-table/docs/classes/t.body.html#event_onScrolledToBottom.

Similar thing goes for `onScroll` assuming that functionality is useful

**Comment by buschtoens** [comment]
Closed in #514. :smile:
