### ISSUE TITLE
Broken Navigation on Demo Page

### ISSUE THREAD

**Issue by konradjurk** [offirgolan/ember-light-table#515]
Sadly the dropdowns don't work

**Comment by buschtoens** [comment]
Are you talking about these dropdowns?

![image](https://user-images.githubusercontent.com/834636/33196015-e9ba5ef2-d0dc-11e7-86ef-9f45c1ee363b.png)

You have to click them. :stuck_out_tongue_winking_eye: 

Or is it really broken? :thinking: 
Then please name your browser and OS. :)

**Comment by konradjurk** [comment]
It is really broken for me, here is the hard evidence 😜 https://youtu.be/Woi6SVa6K0I

Mac OS 10.12, Chrome 62.0.3202.94

No console errors

**Comment by buschtoens** [comment]
I'm on Chrome 62.0.3202.94 myself (CentOS) :frowning: 

Do you have any content blockers installed, like AdBlockers, proxies, etc? We're loading bootstrap for the navigation from `https://maxcdn.bootstrapcdn.com/`, maybe that's blocked?

**Comment by konradjurk** [comment]
No I don't have content blockers but it works now. Did you change something?

I swear it didn't work 7 hours ago and I re-visited the page for the video just minutes ago. Weird

**Comment by buschtoens** [comment]
I assure you I did not even touch my coffee yet. :sweat_smile: 

Well then ¯\_(ツ)_/¯
