### ISSUE TITLE
table.setRowsSynced doesn't seem to update with new content

### ISSUE THREAD

**Issue by Techn1x** [offirgolan/ember-light-table#518]
My understanding of table.setRowsSynced (or using enableSync: true when creating the table) is that I should only have to set the rows' model once, and then I can just modify the model and it should then be reflected in the table. But my current implementation doesn't seem to do this

```javascript
model: <some model of records> ,
sortedModel: sort('model', 'sortBy').readOnly(),

init() {
  let table = new Table(this.get('columns'), A([]), { enableSync: true });
  this.set('table',table);
  table.setRowsSynced(this.get('sortedModel')); 
}

actions: {
  onColumnClick(column) {
    this.set('sortBy','someval:asc');
  }
}
```

The sortedModel gets sorted on the column click, but the table rows don't get updated with the new sorted model

I can add the following code, but then the rows get completely replaced and I lose things like which rows are selected & hidden - so ideally I want to be able to sort while keeping the existing rows in the table

```javascript
setRows: observer('sortedModel', 'sortedModel.[]', function() {
  console.log('sorted the model');
  let sortedModel = this.get('sortedModel');
  let table = this.get('table');

  table.setRowsSynced(sortedModel);
}),
```

Is there something I'm missing here? Thanks!

**Comment by buschtoens** [comment]
The problem is that `sort('model', 'sortBy')` returns a *new* array instance every time the sort definition (`sortBy`) changes.

This really sucks, I know. It's been nagging me for quite some time also. What we'd need is an `ArrayProxy` that is clever enough to diff the underlying `content` array with the new instance and move existing rows around.

But I think that is outside of the scope of this addon and deserves its own project.

**Comment by buschtoens** [comment]
As an immediate remedy, you could compare the old and newly sorted arrays yourself and set the required state, like `selected`, `hidden`, `expanded` yourself.

**Comment by Techn1x** [comment]
Thanks for the explanation! This was bugging me for hours, and explains another ELT issue I was having a few weeks ago haha - at least I have a path forward now!

**Comment by Techn1x** [comment]
For anyone coming to this issue wanting to know more, I used the suggested immediate remedy solution of remembering the old rows' properties of `selected`, `hidden`, `expanded` and applied them to the newly sorted rows.

To do this you'll need to make sure your data records have some kind of unique identifier in order to be able to match them between sorts so you can apply the remembered row properties to the correct new row (this is fine / easy if using ember models directly in ELT, you can just use the `id` attr, - but I was using a raw JSON array for one of my tables)

Here's a sample of what worked for me - there are probably more efficient ways to do this;
```javascript
setRows: observer('sortedModel', function() {
  let sortedModel = this.get('sortedModel');
  let table = this.get('table');

  // Remember old row properties
  let oldSelectedRows = table.get('selectedRows');
  let oldExpandedRows = table.get('expandedRows');
  let oldHiddenRows = table.get('rows').filterBy('hidden',true);
		
  // Set the new rows
  table.setRows(sortedModel);
  let newRows = table.get('rows');

  // Now apply the remembered properties (selected, hidden, expanded) to the new rows, based on their primary key
  let primaryKeyAttr = 'id';
  oldSelectedRows.forEach((oldRow) => {
    let oldRowId = oldRow.get(primaryKeyAttr);
    let matchingNewRow = newRows.findBy(primaryKeyAttr,oldRowId);
    if(matchingNewRow) matchingNewRow.set('selected', true);
  });
  oldExpandedRows.forEach((oldRow) => {
    let oldRowId = oldRow.get(primaryKeyAttr);
    let matchingNewRow = newRows.findBy(primaryKeyAttr,oldRowId);
    if(matchingNewRow) matchingNewRow.set('expanded', true);
  });
  let visibilityChanged = false;
  oldHiddenRows.forEach((oldRow) => {
    let oldRowId = oldRow.get(primaryKeyAttr);
    let matchingNewRow = newRows.findBy(primaryKeyAttr,oldRowId);
    if(matchingNewRow) {
      visibilityChanged = true;
      matchingNewRow.set('hidden', true);
    }
  });
  // If a row visibility changed, need to notify table that visibleRows changed, otherwise the table doesn't update for some reason
  if(visibilityChanged)	table.notifyPropertyChange('visibleRows');
}).on('init'),
```
