### ISSUE TITLE
Implicit creation of rows when new data added to model?

### ISSUE THREAD

**Issue by schickm** [offirgolan/ember-light-table#52]
I've noticed that you have to manually call `table.addRow()` if you'd like a new row to appear in the table.  Is it possible to have the table watch the initial passed in model to the constructor for changes?  Or is adding rows at runtime not really a priority feature for this table addon?

**Comment by rwwagner90** [comment]
@schickm I just use the `didReceiveAttrs` hook to set the rows, so the rows are set anytime the model changes. I think it makes sense to do this rather than relying on the addon to do it.

**Comment by schickm** [comment]
Gotcha, but I was thinking of a scenario where my component receives a RecordArray as the model, and at some point in the future records are added/removed from the RecordArray due to changes in the store.  This would mean that `didReceiveAttrs` wouldn't be triggered since technically the attribute was the RecordArray instance, not it's content.   Hopefully I'm making sense here...  If there was a way to demonstrate this using an ember twiddle I'd love to...but looks like the [ember twiddle folks are still working on addon support](https://github.com/ember-cli/ember-twiddle/issues/395) 

I guess I could use one of those dreaded observers that everyone tells me not to use...

**Comment by rwwagner90** [comment]
@schickm are you sure it wouldn't fire? You may be right, since our model is slightly different, and is a model with an array as just one property inside it, but when we load more records into the store, and they are pulled into that array, the `didReceiveAttrs` hook is called.

**Comment by offirgolan** [comment]
@schickm as of right now, implicit row creation is not on the backlog. Maybe in the future but the current goal of this addon is to focus mostly on the table component rendering and give you all the power on when and how rows/columns are added/removed/modified. Ill leave this open for now so that way I wont forget!

**Comment by schickm** [comment]
@offirgolan makes sense, I got that feeling from looking at the API.  If/when I get a good non-observer based approach to this, I'll post it here for others interested.

**Comment by taras** [comment]
@schickm I create a PR that adds a `table` helper that you can use to automatically update the table when data changes. This will only work for simple tables as the moment. I'm working on some `secret` sauce that'll make this a viable solution for complicated tables. Give it a shot and let me know if it works for you. #79

**Comment by offirgolan** [comment]
Done! (#167) 😸
