### ISSUE TITLE
specifying cellComponent in column results in nested `td`s

### ISSUE THREAD

**Issue by shaunc** [offirgolan/ember-light-table#520]
When I specify a cell component for a column, light-table generates the following structure:

```<td...><td>...</td></td>```

The inner `td` is the element of my component. I thought the cell component should be the actual "td" element, and not the content of the td element? If this were true it would be much easier to style, as well as using less html, which is important for large tables.

**Comment by buschtoens** [comment]
You're looking for `cellType`. I know, this is a bit counter-intuitive. We'll probably change this with the next major version.

**Comment by shaunc** [comment]
Thanks!

**Comment by shaunc** [comment]
Opps ... when I use "cellType" I get a message like `Error: Assertion Failed: Could not find component named "light-table/cells/user-products/cell/text"` -- so whereas "cellComponent" allows an absolute path, "cellType" does not, so I can't use it to use my own components.

**Comment by buschtoens** [comment]
Yeah, personally I don't really like this behavior either. I'd like to change this with the next major version.

You can simply re-export your component or wrap it in the meantime.

**Comment by shaunc** [comment]
@buschtoens -- by re-export, do you mean I can somehow trick ember into thinking its in the "light-table/cells/" namespace? Can you tell me how to do that? (In the meantime I've wrapped it, but I have a large table and want to avoid extra html.)

If you were to start a branch for the next major version, I'd be happy to use it ;). Haven't looked at the code base carefully, and also don't know that the plan is (more specificly than changing this behavior) so it would be hard to sumit a PR.

**Comment by alexander-alvarez** [comment]
@shaunc 
you can make folders in your components directory `components/light-table/cells/<my-cell-name>`
and so forth.
Also we have generators to generate the different ember light table file types https://github.com/offirgolan/ember-light-table/tree/master/blueprints
e.g. `ember g cell-type <component-name>`
you can see all the commands with `ember help g` and look for the generators under the `ember-light-table` heading.

**Comment by shaunc** [comment]
Ah -- right; I must have been sleepy. :) Thanks!
