### ISSUE TITLE
Occlusion not compatible with bootstrap tables

### ISSUE THREAD

**Issue by maxwondercorn** [offirgolan/ember-light-table#530]
First thank you for occlusion rendering.  Occlusion rendering will override Bootstrap classes assigned to tableClassNames. So the following doesn't work

```
 {{#light-table table
   height='60vh'
   tableClassNames="table table-striped"
   occlusion=true
   estimatedRowHeight=50
  as |t|}}

...  

{{/light-table}}
```
which is fixed by creating your own class to mimic bootstrap tables

```
.occlusion-bs-striped {
    table {
      width: 100%;
      max-width: 100%;
      margin-bottom: 1rem;
      background-color: $table-bg;
    }

  td {
    padding: $table-cell-padding;
    vertical-align: top;
    border-top: $table-border-width solid $table-border-color;
  }

  thead > tr > th {
    vertical-align: bottom;
    border-bottom: 2px solid $table-border-color;
  }
      
  tbody tr:nth-of-type(odd) {
      background-color: $table-accent-bg;
  }

  tr {
    height: 25px;
  }
}
```

```
 {{#light-table table
   height='60vh'
   tableClassNames="occlusion-bs-striped"
   occlusion=true
   estimatedRowHeight=50
  as |t|}}

...  

{{/light-table}}
```

A minor issue but it may throw some people off.

**Comment by buschtoens** [comment]
Are you using [Bootstrap v3](https://getbootstrap.com/docs/3.3/css/#tables-striped)? They're using overly restrictive CSS selectors in that version: `.table-striped > tbody > tr:nth-of-type(odd)`

The selectors were relaxed in [Bootstrap v4](https://getbootstrap.com/docs/4.0/content/tables/#striped-rows): `.table-striped tbody tr:nth-of-type(odd)`

Occclusion rendering wraps the `<tr>` elements in another element (`<vertical-collection>`), building this contstruct:

```html
<table class="table-striped">
  <tbody class="lt-body">
    <vertical-collection>
      <occluded-content></occluded-content>
        <tr data-row-id="ember883" colspan="1" id="ember885" class="lt-row">
          <!-- ... -->
        </tr>
        <!-- ... -->
      <occluded-content>And 84 items after</occluded-content>
    </vertical-collection>
  </tbody>
</table>
```

You can upgrade to Bootstrap v4 to fix that. Maybe we can get rid of the `<vertical-collection>` element, but I can't promise anything yet.

**Comment by maxwondercorn** [comment]
Yes, forgot to mention v3.  I'm using ember-cli-bootstrap-sassy which is still on v3, so until the addon author upgrades, I'll be on v3.

I figured the <vertical-collection> element was causing the issue.  To be honest, creating a specific class to solve my problem is fine.  Unless it's breaking something else, I'd not spend time removing it.  I put it up as much to document it, in case someone else ran into the issue.
