### ISSUE TITLE
cellComponent vs cellType

### ISSUE THREAD

**Issue by timmyomahony** [offirgolan/ember-light-table#536]
Hey, this might be a silly question, but what exactly is the difference in use-case between creating a custom `cellComponent` or a custom `cellType`? I assume the latter is when you want to affect the actual functionality of the cell itself, as opposed to just wanting to adjust the formatting or content of the actual cell?

**Comment by buschtoens** [comment]
`cellComponent` is a component that is nested inside a `<td>` that is generated by ELT.

`cellType` is the component that will be used to generate that `<td>`.

https://github.com/offirgolan/ember-light-table/issues/520
https://github.com/offirgolan/ember-light-table/issues/455

**Comment by timmyomahony** [comment]
Thanks for the quick reply.

**Comment by buschtoens** [comment]
You're welcome. :)
