### ISSUE TITLE
Deprecation warning in Ember 3.0 

### ISSUE THREAD

**Issue by nelnico** [offirgolan/ember-light-table#556]
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: site-xxx-> ember-light-table -> ember-in-viewport -> ember-cli-babel

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: site-xxx-> ember-light-table -> ember-in-viewport -> ember-getowner-polyfill -> ember-cli-babel

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: site-xxx-> ember-light-table -> ember-scrollable -> ember-component-inbound-actions -> ember-cli-babel

DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: site-xxx-> ember-light-table -> ember-scrollable -> ember-element-resize-detector -> ember-cli-babel

**Comment by buschtoens** [comment]
Thanks for reporting. As the chain suggests, these are issues with `ember-in-viewport` and `ember-scrollable` and their respective sub-dependencies.

We can fix the deprecation warning for `ember-in-viewport` by upgrading it to `3.0.0`.

For `ember-scrollable` we need a version bump in the upstream repo.

**Comment by buschtoens** [comment]
If you feel like it, you can definitely submit PRs to the repos I linked above.

**Comment by maxwondercorn** [comment]
ember-in-viewport has been updated.  Not sure the update address #555
