### ISSUE TITLE
onScrolledToBottom doesn't get called if the table's horizontal width exceeds 2x table viewport width

### ISSUE THREAD

**Issue by dspigarelli** [offirgolan/ember-light-table#557]
I've implemented horizontal scrolling following the pattern in the docs/cookbook.  The viewport for the table is ~1000px and I dynamically update the columns (via `table.setColumns`) after the first call to `onScrolledToBottom`.  When the new columns take the horizontal size of the table beyond ~2000px, the table stops issuing calls to `onScrolledToBottom`.

I believe the issue is that `ember-in-viewport@2.2.0` requires the `lt-infinity` DOM element to be completely in the viewport (if I understand the [`ember-in-viewport` calculation code](https://github.com/DockYard/ember-in-viewport/blob/v2.2.0/addon/utils/is-in-viewport.js) correctly) before it fires.  The viewport tolerance provides a way to give some wiggle room to that calculation and `ember-light-table` sets this to the table width.  Beyond the 2x-table-width the `viewportEntered` fails to ever be `true` so the `onScrolledToBottom` never gets called.

**Comment by snewcomer** [comment]
@dspigarelli Could you try out this branch and lmk if you still have the same problem? #548 

Just curious before I dig in...

**Comment by dspigarelli** [comment]
Sure I can take a look when I get a sec.

**Comment by dspigarelli** [comment]
@snewcomer That branch works for me.

**Comment by snewcomer** [comment]
Awesome!  closing this issue.
