### ISSUE TITLE
'Undefined length' error caused by ember-composible?

### ISSUE THREAD

**Issue by nmcclay** [offirgolan/ember-light-table#56]
I just pulled down beta5 to see whats new, and I'm getting this error:

```
Cannot read property 'length' of undefined
TypeError: Cannot read property 'length' of undefined
    at CoreObject.module.exports.filterHelpers (/my-project/node_modules/ember-light-table/node_modules/ember-composable-helpers/index.js:40:18)
```

Doing a quick search through the repo, I'm not sure what this sub-module is being used for in ember-light-table?  There doesn't appear to be any addon configuration including the whitelist it appears to be looking for https://github.com/DockYard/ember-composable-helpers#configuration ?

**Comment by nmcclay** [comment]
This might be caused by me pulling ember-light-table into an addon I'm working on.  I can confirm this isn't a problem in ember-light-table beta 4.

**Comment by offirgolan** [comment]
What version of ember-cli are you on?

**Comment by nmcclay** [comment]
Opps, yeah 2.6.1

**Comment by offirgolan** [comment]
Can you try pulling master branch and seeing if you're getting the same error?

**Comment by nmcclay** [comment]
Yeah I pulled git+ssh://git@github.com/offirgolan/ember-light-table.git#d9d23b4644a939897c4e1ed8febc65a257c20af7 and it is still a problem.  Its also a problem with Ember 2.5.1.

**Comment by offirgolan** [comment]
@nmcclay can you validate if this issue still exists with the latest beta?

**Comment by nmcclay** [comment]
I pulled the latest beta 7 and tested, appears to be having the same issue, fails on this line because length is undefined:

```
// exit early if no opts defined
if (whitelist.length === 0 && blacklist.length === 0) {
    return new Funnel(tree);
}
```

**Comment by nmcclay** [comment]
I'm going to setup a reproduction app so you can see this issue more easily.  One thing I encountered while setting this up as a vanilla addon:

```
Addon templates were detected, but there are no template compilers registered for `light-table`. Please make sure your template precompiler (commonly `ember-cli-htmlbars`) is listed in `dependencies` (NOT `devDependencies`) in `light-table`'s `package.json`.
```

Obviously adding 'ember-cli-handlebars` to my own addon's dependencies fixed this, but I wanted to bring it to your attention.

**Comment by nmcclay** [comment]
Ok, I have a repo case isolated now.  Its caused by the included hook when you use ember-light-table within another addon.
```
  // This is the troublemaker, even though it isn't doing anything unique, it will throw an error.
  included: function(app, parentAddon) {
    this._super.included(app);
  }
```
I can confirm this became broken in beta 5 and has continued ever since.

**Comment by nmcclay** [comment]
Probably doesn't come as a surprise, but `ember-composable-helpers` is the culprit.  Adding this package as well as the included line listed above causes the error.  This is probably not caused by ember-light-table in any way, so I'll see what I can learn about fixing it and take any grievances over there instead.

**Comment by offirgolan** [comment]
👍 Sounds good. Keep me in the loop! If needed we can escalate to ember-composable-helpers.

Do you think ember-light-table just needs to add a `whitelist` and `blacklist` to ember-cli-build with all the composable helpers we are using?

**Comment by nmcclay** [comment]
No need, its an obscure nested addon issue and is completely unrelated to ember-light-table.  For anyone interested the issue is solved by using:
```
  included: function(app, parentAddon) {
    this._super.included.apply(this, arguments);
  }
```

**Comment by offirgolan** [comment]
Thats good to hear 😺 ! Thanks for investigating @nmcclay

**Comment by wilsonohyeah** [comment]
I'm using ember-light-table 1.4 and am running into this exact issue 😞
