### ISSUE TITLE
Deprecation warning when `ember s`

### ISSUE THREAD

**Issue by AdminDev826** [offirgolan/ember-light-table#568]
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-in-viewport -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-in-viewport -> ember-getowner-polyfill -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-scrollable -> ember-component-inbound-actions -> ember-cli-babel
DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: bai-ui -> ember-light-table -> ember-scrollable -> ember-element-resize-detector -> ember-cli-babel

"ember-light-table": "^1.12.2",
"ember-cli": "^3.1.4",

**Comment by kevinansfield** [comment]
The number of deprecation warnings has reduced with the recent update, all now point to `ember-scrollable` as the final babel 5.x holdout:

> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ghost-admin -> ember-light-table -> ember-scrollable -> ember-component-inbound-actions -> ember-cli-babel
> DEPRECATION: ember-cli-babel 5.x has been deprecated. Please upgrade to at least ember-cli-babel 6.6. Version 5.2.8 located: ghost-admin -> ember-light-table -> ember-scrollable -> ember-element-resize-detector -> ember-cli-babel
