### ISSUE TITLE
TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNo des[0] error while building

### ISSUE THREAD

**Issue by vishalpareek** [offirgolan/ember-light-table#577]
Hi Team,

I am getting the below error when i am tring to build the ember project after installing ember-cli-jstree,

TypeError: BroccoliMergeTrees: Expected Broccoli node, got undefined for inputNo
des[0]

Any idea why this is happening?

**Comment by fran-worley** [comment]
To investigate we'd need more information about the version of ember, ELT and other key packages you're using.  Please reopen if this is still an issue and provide some more information and someone will take a look. Thanks !
