### ISSUE TITLE
ELT and page breaks

### ISSUE THREAD

**Issue by Techn1x** [offirgolan/ember-light-table#579]
Using Chrome 68 (but can confirm issue exists in Firefox too)

I've noticed that when a page break needs to occur at a position close to an ELT header, the following can happen where it prints the header twice;
![untitled9](https://user-images.githubusercontent.com/1049837/43433961-042b19bc-94bd-11e8-9534-25a519f97e16.png)

I have set the necessary `break-inside: avoid !important;` but it seems like it's not getting followed (perhaps due to my other breaking requirements on the page) - this is a separate issue.

After delving into the CSS it seems that the `<tr>` that holds the `<th>` header's is only 18px in height, while its content (the `<th>`'s) are 37px in height. This is the same as the tables on the ELT demo page

![untitled10](https://user-images.githubusercontent.com/1049837/43434346-9e54f868-94be-11e8-9e29-d62c3073f558.png)

I believe what's happening is the browser thinks there's enough height on the page to put the `<tr>` (i.e. at least 18px) but then the children are too large and get placed onto the next page, causing the double render glitch

A workaround is to set the `<tr>` height to 37px, but
a) this is pretty hacky
b) not sure how this will work with subcolumns / column grouping
c) if a header is too long and the text wraps to next line, height changes
d) with hardcoded pixel height, could be issues if the user decides to scale the content before printing

Is there a way to fix this nicely in the ELT addon?

**Comment by Techn1x** [comment]
Here's what my table looks like with some background colours and CSS
![untitled11](https://user-images.githubusercontent.com/1049837/43434803-a180b25a-94c0-11e8-84c2-6e32c0a40428.png)

Before height fix (all purple - clearly the `<tr>` is split)
![untitled12](https://user-images.githubusercontent.com/1049837/43434807-a57f413c-94c0-11e8-9c4d-4a21d052c1c9.png)

After height fix (header is on next page, now it looks like the split is occurring in table, but at least it's presentable now)
![untitled13](https://user-images.githubusercontent.com/1049837/43434813-aa17c5fc-94c0-11e8-84c2-7f55cfaed178.png)

**Comment by Techn1x** [comment]
Can confirm this is not an issue with grouped/sub columns. The `<tr>`'s are the same height as their children `<th>`'s

**Comment by Techn1x** [comment]
I have a better workaround now. It turns out if the thead.lt-head is set as `display:table-header-group` it does the double render if a page break occurs between the two rows in the header.

My current fix is to do the CSS below. Page breaks still occur incorrectly (due to browser bugs, not ELT), but it stops the double render.
```css
.lt-head {
  display: table-footer-group;
}
```

This is more of an issue with tables & page breaks, rather than ELT itself, but the bug is exposed by ELT because of its implementation of the header.

Hope this helps someone out there, this bug really stole a lot of my time.

**Comment by micstem** [comment]
@Techn1x 
How did you manage to have an additional `<thead>` inside the `.lt-body-wrap` table? This isn't normal ELT behaviour, is it? Help much appreciated.
