### ISSUE TITLE
row.hidden clashes with Ember model

### ISSUE THREAD

**Issue by VaidotasSm** [offirgolan/ember-light-table#585]
**Summary**
If Ember object has property named `hidden` it is being overridden to `false`

**Details**

Long story short: we had issue that some columns with checkboxes remained unchecked even though data was there as `true`. Other columns with checkboxes behaved fine. Then I found out that `hidden` has special meaning and so row it seems cannot have property like that.

I don't know if this is clear issue or "feature" and not sure if fix would exist that wouldn't break things.

**Comment by alexander-alvarez** [comment]
Hey @VaidotasSm  thanks for reporting this and sorry for the trouble it may have caused.

`row.hidden` being a thing is definitely a piece of functionality we offer, though we shouldn't be affecting the object you pass in

On my local, (running on master) I wrote a simple test [row-test.js](https://github.com/offirgolan/ember-light-table/blob/master/tests/unit/classes/row-test.js) to see wha'ts going on
```js
test('create row - object with hidden set', function(assert) {
  let obj = { hidden: true };
  let row = new Row(obj);
  assert.notOk(row.get('hidden')); // false => set to value on proxy
  assert.ok(row.get('content.hidden')); // true (goes to the original object)
  assert.ok(obj.hidden); // still true
});
```

What exactly were you expecting to happen?

**Comment by VaidotasSm** [comment]
@alexander-alvarez thanks for clarifications, yesterday I did actually find out that the problems was that our app was using `{{row.xxx}}` in few templates, rather than `{{row.content.xxx}}`. So all is fine now, no issue.
