### ISSUE TITLE
sendAction deprecation warning

### ISSUE THREAD

**Issue by ajcobo** [offirgolan/ember-light-table#587]
When using the library I'm getting the following warnings

`sendAction("onBeforeResponsiveChange")`
`sendAction("onAfterResponsiveChange")`

`Component#sendAction is deprecated. Please use closure actions instead. [deprecation id: ember-component.send-action]`

I'm using
ember-light-table 1.13.2
ember-cli 3.4.1

**Comment by fran-worley** [comment]
@ajcobo a fix for this has been released in `ember-light-table@2.0.0-beta.1`
