### ISSUE TITLE
Remove jQuery

### ISSUE THREAD

**Issue by donaldwasserman** [offirgolan/ember-light-table#591]
This really isn't an issue _per se_, but more of a question: Would @buschtoens be ok with a PR removing jQuery?

It looks like it's only used in a few spots: 

- Managing some mouse event listeners in `lt-column-resizer`
- Getting some various widths (`.width()`, `.outerWidth()`)
- Class toggling
- Parent/Closest dom traversal
- Outdated blueprint code

 The only someone tricky thing is the usage of the `.closest` and the computed `$column` property used in [lt-column-resizer](https://github.com/offirgolan/ember-light-table/blob/master/addon/components/lt-column-resizer.js#L18)

I'd be happy to do this, just wanted to make sure I wasn't missing any sort of big ticket issues.

**Comment by alexander-alvarez** [comment]
Yes
