### ISSUE TITLE
[Draggable Column] Error when dragging column; "removeObject is not a function"

### ISSUE THREAD

**Issue by msenevir** [offirgolan/ember-light-table#595]
Running into a runtime error when using the draggable columns:

`Uncaught TypeError: _columns.removeObject is not a function`

After looking at the code in `addon/mixins/draggable-column.js`, the `toArray()` method is called on the columns array on line 128: `let _columns = columns.toArray();`.

The `toArray()` method will return a regular javascript array, so lines 137-138 will throw errors because these methods are for Ember Arrays:

```
_columns.removeObject(sourceColumn);
_columns.insertAt(targetColumnIdx, sourceColumn);
```

Also, another reason `toArray()` should not be used is because it does not guarantee the same order. From the [ember docs](https://www.emberjs.com/api/ember/3.5/classes/MutableArray/methods/removeObject?anchor=toArray):
```
Simply converts the object into a genuine array. The order is not guaranteed. 
```

**Comment by fran-worley** [comment]
Closing as this has been merged into master and 2.x (unreleased in both cases).
