### ISSUE TITLE
Sort icon gets mounted when the columns are narrow

### ISSUE THREAD

**Issue by Gorzas** [offirgolan/ember-light-table#600]
I have found that, in tables with a lot of columns or with narrow ones, the sort icon in the header gets mounted by the label like this (you can see it in the last name column):

![screenshot from 2018-11-19 11-14-23](https://user-images.githubusercontent.com/1456562/48700997-b7e7d300-ebed-11e8-96ee-26cfa58414de.png)

What do you think about changing the order of [these lines](https://github.com/offirgolan/ember-light-table/blob/master/addon/templates/components/columns/base.hbs#L4-L9)? It doesn't totally fix the problem but at least the result is prettier than the current solution. Other way is adding the option to allow ellipsis on the headers :smile:.

**Comment by tniezurawski** [comment]
This solution breaks our layout. IMHO it is crafted very much into specific needs now.

We show sorting arrows next to the text by overwriting this style to `float: none`:
```css
.ember-light-table .lt-column .lt-sort-icon {
    float: right;
}
```

After this change, you are forced to use this specific layout where arrows go to the far right. Removing `float: right` leads to arrows shown on the left side, before the label:

![image](https://user-images.githubusercontent.com/4335166/63348914-940f1480-c35a-11e9-9b07-53610b859c63.png)

----

If we could at least target `{{label}}` via CSS :P Would be nice to have it wrapped by `<span>`. We could then apply `float: left;` to that span and have the effect we wanted back.

Another option is to wrap the whole thing (icon + text) and let us style it. Then we could use `flex` and change the `order` of things.
