### ISSUE TITLE
Retain table state over component reloads

### ISSUE THREAD

**Issue by CrushedPixel** [offirgolan/ember-light-table#602]
I've implemented a component using `ember-light-table` similar to the example on the project's website:

```
  init() {
    this._super(...arguments);
    this.get('fetchRecords').cancelAll();
    this.set('model', []);
    let table = new Table(this.get('columns'), this.get('model'), { enableSync: true });
    let sortColumn = table.get('allColumns').findBy('valuePath', this.get('sort'));

    // setup initial sort column
    if (sortColumn) {
      sortColumn.set('sorted', true);
    }

    this.set('table', table);
  },
```

 However, when leaving and re-entering a route with a table, the `init` function is called again, clearing the `model` and thus all rows.
Is there a way to keep the table state, so that the data isn't reloaded every time the route is switched?

**Comment by alexander-alvarez** [comment]
Hi @CrushedPixel -- you could put the state in a service, who's lifetime is over the course of the application, so it won't get erased between route transitions unless you change it explicitly

Feel free to reference https://guides.emberjs.com/v3.5.0/applications/services/ for more info
