### ISSUE TITLE
Is the a way to add css class to table row 

### ISSUE THREAD

**Issue by sepetukas** [offirgolan/ember-light-table#62]
Hi, just wondering is there any simple way to add css class to table row. CSS class should be computed from row data

**Comment by offirgolan** [comment]
Sorry for the late response! Yes it is possible.

```js
const rows = this.table.rows;
const myRow = rows.findBy('someProp', 'someValue');

row.set('classNames', 'foo bar foo-bar'); 

// OR 

row.set('classNames', ['foo',  'foo-bar']); 
```

See [docs](http://offirgolan.github.io/ember-light-table/docs/classes/Row.html#property_classNames
)

**Comment by offirgolan** [comment]
@sepetukas Im gonna go ahead and close this issue. Feel free to reopen if you have any more questions.

**Comment by sepetukas** [comment]
Thank you. Not very familiar with the github work flow :)

**Comment by offirgolan** [comment]
@sepetukas No worries! Glad I can help out 😸

**Comment by AlekzZz** [comment]
is it possible to add row class through template?

**Comment by schickm** [comment]
Yeah, I'm a little confused here too....I'm wondering how to make the row class computed from the row's model.  

I'm guessing you have to subclass `Row` so it computes  `classNames` based on the model...and then override `Table.createRow(..)` to create rows of your subclass?

Or is there some easier way that doesn't involve mucking about in private areas of the code?
