### ISSUE TITLE
Sort icons not compatible with FontAwesome 5

### ISSUE THREAD

**Issue by piloos** [offirgolan/ember-light-table#659]
When using FA5 (in `svg` mode), the sort icons do not toggle anymore.

In FontAwesome (FA) 5, `<i class="fa fa-sort">` style declaration of icons are autoreplaced by `svg`'s

So the rendered HTML looks like this:
```
<svg class="svg-inline--fa fa-sort fa-w-10 lt-sort-icon" aria-hidden="true" data-prefix="fas" data-icon="sort" role="img" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 320 512" data-fa-i2svg=""> 
  <path ..."></path>
</svg>
<!-- <i class="lt-sort-icon fas fa-sort"></i> -->
```
This means changing the class on the `<i>` like attempted here:

`addon/templates/components/columns/base.hbs`
```
  {{else if sortIconProperty}}
    <i class="lt-sort-icon {{get sortIcons sortIconProperty}}"></i>
  {{/if}}
```
won't work anymore.

**Comment by piloos** [comment]
Two workarounds possible:
1. jQuery hack
2. use the built-in custom icon system

**Comment by joelkallman** [comment]
**You can use the `iconComponent` property like so:**

    {{#light-table table height='60vh' as |t|}}

      {{t.head
        iconComponent='light-table-icon'
        iconSortable='sort'
        iconAscending='sort-up'
        iconDescending='sort-down'
      }}

      {{!-- Other table definition --}}

    {{/light-table}}


**Create your component `light-table-icon`**

`light-table-icon.js`

    import Component from '@ember/component';
    import { computed, get } from '@ember/object';

    export default Component.extend({
      tagName: '',
      icon: computed('sortIcons', 'sortIconProperty', function () {
        return get(this.sortIcons, this.sortIconProperty);
      })
    });

`light-table-icon.hbs`

    {{fa-icon icon}}

Looks like this was added on v1.11.0 - https://github.com/offirgolan/ember-light-table/releases/tag/v1.11.0

**Comment by fran-worley** [comment]
I've just managed to do this with an app of mine using the instructions [here](@html-next/vertical-collection) so am marking this as closed.
