### ISSUE TITLE
dragging columns broken on ember-source >= 3.6 

### ISSUE THREAD

**Issue by efx** [offirgolan/ember-light-table#660]
Per [ember deprecations](https://emberjs.com/deprecations/v3.x#toc_use-notifypropertychange-instead-of-propertywillchange-and-propertydidchange), we need to refactor these 2 spots
https://github.com/offirgolan/ember-light-table/blob/master/addon/mixins/draggable-column.js#L141 https://github.com/offirgolan/ember-light-table/blob/master/addon/mixins/draggable-column.js#L135 to use `notifyPropertyChange`.
I can help with a PR too.

**Comment by efx** [comment]
@alexander-alvarez do you prefer I include the polyfill to support ember-source <= 3.1? I would like to get this fixed and hopefully available in a tagged version of ember-light-table so I don't need to maintain a fork.

**Comment by mmadsen2** [comment]
Any chance this could be fixed in an upcoming beta?  This is literally the only thing preventing me from upgrading to the latest Ember LTS (3.8).

**Comment by fran-worley** [comment]
@mmadsen2 if you wanted to help speed this up you could draft a PR.... 😄

**Comment by mmadsen2** [comment]
I gave it a shot @fran-worley.  I hope I did everything correctly, this is my first PR to a third-party addon...

**Comment by fran-worley** [comment]
This has now been merged into 2.x branch and will be shipped in the next beta version - thanks @mmadsen2 !
