### ISSUE TITLE
Deprecation: object.new-constructor

### ISSUE THREAD

**Issue by lechodiman** [offirgolan/ember-light-table#662]
I'm getting the following deprecation on ember-cli@3.7.1

> DEPRECATION: using `new` with EmberObject has been deprecated. Please use `create` instead, or consider using native classes without extending from EmberObject. [deprecation id: object.new-constructor]

This message is thrown when extending the [Table class](https://github.com/offirgolan/ember-light-table/blob/d4673d80c4ea622bf2513358f70e28a06e84b45b/addon/classes/Table.js#L30)

**Comment by gauravjain028** [comment]
I am also having same issue.

**Comment by lypborges** [comment]
@buschtoens any guidance to fiz the warnings on the canary build? I can try to work on a fix this weekend. But look like that we should refactor all the Light Table.js https://github.com/offirgolan/ember-light-table/blob/master/addon/components/light-table.js
To  .  I'm not sure how to fix that without a major release. I would love to help.

**Comment by efx** [comment]
@fran-worley thank you for fixing the deprecation! anything else needed or can we close this issue?

**Comment by fran-worley** [comment]
For anyone still encountering this issue please install ELT from the 2.x. You should find any compile issues have also been resolved. A new beta release should be out soon.

**Comment by alexander-alvarez** [comment]
`ember-light-table@2.0.0-beta.4` is tagged and released
