### ISSUE TITLE
Deprecation: ember-polyfills.deprecate-merge

### ISSUE THREAD

**Issue by AndriesDemeulenaere** [offirgolan/ember-light-table#667]
Getting the following deprecation:

> Use of `merge` has been deprecated. Please use `assign` instead. [deprecation id: ember-polyfills.deprecate-merge]

https://emberjs.com/deprecations/v3.x/#toc_ember-polyfills-deprecate-merge

**Comment by fran-worley** [comment]
Tested locally following merge of #673 in 2-x branch and deprecation warning has gone so this issue can probably be closed @alexander-alvarez .
