### ISSUE TITLE
Support angle bracket invocation

### ISSUE THREAD

**Issue by maxwondercorn** [offirgolan/ember-light-table#668]
ELT does not support angle bracket invocation..  All the sub components - head, body, foot - support angle brackets.

The issue is around assigning table.

Positional parameters aren't supported but trying

```
<LightTable table={{this.table}} as |t|>
...
</LightTable>
```
generates  `Assertion Failed: [ember-light-table] table must be an instance of Table`

**Comment by efx** [comment]
@maxwondercorn shouldn't that snippet specify the table property as `@table={{this.table}}`? What happens when you update the snippet? I think pzuraq has a great write up of the syntax [here](https://www.pzuraq.com/coming-soon-in-ember-octane-part-2-angle-brackets-and-named-arguments/).

**Comment by maxwondercorn** [comment]
I thought I had tried that variation but maybe not. I will verify

**Comment by maxwondercorn** [comment]
@efx that worked.  I thought I had tried that form,  but obviously not.  pzuraq's post is a pretty good reference.  I had referencing the RFC.  I'll see if I can find time to create a PR to document.

**Comment by efx** [comment]
nice @maxwondercorn ! Ah, I'll definitely plug that PR as I think more docs always help reduce confusion.
