### ISSUE TITLE
Fixed header - Show scroll bar all the time

### ISSUE THREAD

**Issue by fran-worley** [offirgolan/ember-light-table#676]
I had assumed that turning off autoHideScrollbar would result in the scroll bar always being visible.

Turning off autoHide seems to ensure it stays visible, but only becomes visible after scroll has occurred.

I’m raising this as a number of our users have complained of being unable to scroll our tables since we adopted Ember Light Table. On closer inspection, the problem appears to be be with users who prefer to click and drag a scroll bar rather than use gestures or a scroll wheel to do so. 

Even so I believe this is a valid issue - it should be possible to display scroll bars at all times and I would expect disabling autoHideScollbard to control this behaviour.

**Comment by alexander-alvarez** [comment]
Hmm....

It seems `autoHide` is working in Ember scrollable as one would expect
https://alphasights.github.io/ember-scrollable/

and it seems wired correctly
https://github.com/offirgolan/ember-light-table/search?q=autoHide&unscoped_q=autoHide

so maybe it has something to do with when we're creating the ember scrollable component.

I don't have much guideance to give in this realm besides acknowledging that yeah it needs more :eyes:  and investigation

**Comment by fran-worley** [comment]
Thanks for the quick reply @alexander-alvarez. I was starting to think that it was to do with how we set `{{#if virtualScrollbar}}` etc.

But I'm really struggling to work out exactly how it's being set...

**Comment by fran-worley** [comment]
@alexander-alvarez it seems to be working fine when rendering a table with an existing set of rows, but when the rows are being fetched from the server the scrollbar doesn't render. 

I wonder if the issue is actually to do with the timing of setting up ember-scrollable. On-load, the table is empty (so no scrollbar is needed and none is rendered 👍) we then fetch some data, and load it into the table at which point we still have no scrollbar even though there should be one (👎). 

Does ember-scrollable know to recheck if a scrollbar should be visible based on a change to the number of rows?

**Comment by fran-worley** [comment]
Possible related to https://github.com/alphasights/ember-scrollable/issues/85 ?

**Comment by alexander-alvarez** [comment]
@fran-worley  great research work... It seems like we're probably encountering that issue. Checking your PR now.

**Comment by fran-worley** [comment]
Closing as MR that fixes the problem has been merged in 2.x branch.
