### ISSUE TITLE
TypeError: Cannot read property 'Symbol()' of undefined when initializing new Table

### ISSUE THREAD

**Issue by muziejus** [offirgolan/ember-light-table#699]
All, I think this is related to #688, as I was having the "instance of Table" problem before. Here is the component:

```javascript
import Component from "@glimmer/component";
import Table from "ember-light-table";

export default class TextEntryListComponent extends Component {
  columns = [
      {
        label: "Attested Name",
        valuePath: "attestedName",
        width: "150px"
      },
    {
      label: "Created On",
      width: "150px",
      valuePath: "createdOn"
    }
  ];

  rows = [
    {
    attestedName: "Belarus",
    createdOn: "2018-01-01"
    },
    {
    attestedName: "Agra",
    createdOn: "2018-01-01"
    },
    {
    attestedName: "Chile",
    createdOn: "2018-01-01"
    }
  ];

  table = new Table(this.columns, this.rows);
}
```

This persistently crashes with the error above as an uncaught error in a promise, and it points to the `super()` invocation in ELT's `Table` class definition's constructor.

If I try to change that line to something like `super(...arguments)`, I get a new error:

> Error: Assertion Failed: An EmberObject based class, (unknown), was not instantiated correctly. You may have either used `new` instead of `.create()`, or not passed arguments to your call to super in the constructor: `super(...arguments)`. If you are trying to use `new`, consider using native classes without extending from EmberObject.

Using the ELT 2.0 beta 3.

**Comment by fran-worley** [comment]
@muziejus Thanks for such a detailed post. The route of the issue I believe is actually (here)[https://github.com/offirgolan/ember-light-table/issues/444] as the way ELT defines it's classes isn't officially supported by Ember. This raises deprecation warnings in ember 3.8 (see #662) and hard errors in Ember 3.10+.

I'm working on fixing this as we speak and it should ship at ELT 2.0 beta 4 hopefully in the next week or two.

**Comment by muziejus** [comment]
Excellent. Thanks!
