### ISSUE TITLE
Multiple tables on the same page

### ISSUE THREAD

**Issue by RKennedy9064** [offirgolan/ember-light-table#703]
Is it currently possible to have two ember light tables on the same page? I tried creating a TableCommon component and extended it so I could reuse the same logic for multiple tables. TableA and TableB both load correctly when they're alone on a page, but as soon as I add more then one table, only the first one works. The rest load with the correct headers, but they're always empty and one of the actions are fired. Am I missing something in regards to more then one table working at a time? Any help would be greatly appreciated.

    // TableCommon
    export default Component.extend({
    store: service(),

    number: 0,
    size: 10,

    isLoading: computed.oneWay('fetchRecords.isRunning'),
    canLoadMore: true,

    init() {
      this._super(...arguments);
      this.set('model', A());
    },

    table: computed('model', function() {
      return new Table(this.get('columns'), this.get('model'));
    }),

    fetchRecords: task(function*() {
      let records = yield this.get('store').query(this.get('modelName'), this.get('queryParams'));
      this.get('model').pushObjects(records.toArray());
      this.set('meta', records.get('meta'));
      this.set('canLoadMore', !isEmpty(records));
    }).restartable(),

    actions: {
      onScrolledToBottom() {
        if (this.get('canLoadMore')) {
          this.incrementProperty('number');
          this.get('fetchRecords').perform();
        }
      },

      onColumnClick(column) {
        if (column.sorted) {
          let dir = column.ascending ? '' : '-';
          this.setProperties({
            sort: dir + column.get('valuePath'),
            canLoadMore: true,
            number: 0
          });
          this.get('model').clear();
        }
      },
    })

    // TableA
    export default TableCommon.extend({
      modelName: 'a',
      layoutName: 'components/light-table/tables/simple-table',

    columns: computed(function() {
      return [{
        label: 'A',
        valuePath: 'A',
      }];
    })

    // TableB
    export default TableCommon.extend({
      modelName: 'a',
      layoutName: 'components/light-table/tables/simple-table',

    columns: computed(function() {
      return [{
        label: 'B',
        valuePath: 'B',
      }];
    })

    {{#light-table table height='65vh' as |t|}}
      {{t.head
        onColumnClick=(action 'onColumnClick')
        iconSortable='fa fa-sort'
        iconAscending='fa fa-sort-asc'
        iconDescending='fa fa-sort-desc'
        fixed=true
      }}

      {{#t.body
        canSelect=false
        onScrolledToBottom=(action 'onScrolledToBottom')
        as |body|
      }}
        {{#if isLoading}}
          {{#body.loader}}
            {{table-loader}}
          {{/body.loader}}
        {{/if}}
      {{/t.body}}
    {{/light-table}}

    //test-page.hbs
    {{table-a}}
    {{table-b}}

**Comment by fran-worley** [comment]
Thanks for getting in touch - can you confirm which version of Ember Light Table you're using? I know we merged a PR to fix closure actions for multiple tables on a page so either you're using the wrong version or our fix isn't 100%!!

**Comment by RKennedy9064** [comment]
Sure no problem.

EMBER: 3.10.1
ember-light-table: 2.0.0-beta.3

I also did a bit more testing and added a call to onScrolledToBottom and a logging message in the onScrolledToBottomAction in init like so.

    init() {
        this._super(...arguments);
        this.set('model', A());
        this.send('onScrolledToBottom');
    }

When I manually call onScrolledToBottom in init, all the tables are loaded with the correct initial data, but only the first table fires the onScrolledToBottom again and fetches the next set of records. When I scroll to the bottom of any other table, it never calls the action.

The other thing I noticed is that if I put logging in onColumnClick, the event is fired for all of the tables, but the tables where onScrolledToBottom doesn't get called correctly just lose all their data and the model in ember inspector becomes []. I'm not sure if this is the same issue you mentioned before, but it seems like it might be related to the onScrolledToBottom even since onColumnClick is called correctly.

Let me know if you need any other information.

**Comment by fran-worley** [comment]
@RKennedy9064 can you try using the 2.x branch from master? The [PR](https://github.com/offirgolan/ember-light-table/blob/2-x/CHANGELOG.md) that should resolve this issue was missed from the beta3 version (see the [changelog](https://github.com/offirgolan/ember-light-table/blob/2-x/CHANGELOG.md) for v2 branch).

If this fixes it we'll try and get a beta 4 release out ASAP!

**Comment by RKennedy9064** [comment]
I tried installing ember-light-table from https://github.com/offirgolan/ember-light-table.git#2-x and received this error.

    Uncaught Error: Compile Error: compute is not a helper
    at opcode-compiler.js:294
    at Compilers.compile (opcode-compiler.js:41)
    at LazyOpcodeBuilder.expr (opcode-compiler.js:1848)
    at LazyOpcodeBuilder.compileParams (opcode-compiler.js:2551)
    at LazyOpcodeBuilder.compileArgs (opcode-compiler.js:2564)
    at LazyOpcodeBuilder.helper (opcode-compiler.js:2363)
    at opcode-compiler.js:292
    at Compilers.compile (opcode-compiler.js:41)
    at LazyOpcodeBuilder.expr (opcode-compiler.js:1848)
    at args (opcode-compiler.js:566)

After that I tried installing it from master using https://github.com/offirgolan/ember-light-table.git and the tables started working correctly. Now each table loads correctly when the page renders and responds to onScrolledToBottom to fetch new data, so it looks like this issue is fixed on the master branch. 

Thanks for taking the time to look into this!

**Comment by fran-worley** [comment]
Ion glad the PR I referred to fixes your issue. We'll need to get you going with the 2.x branch though as that's where we're working on ember 3.4+ compliance. I'll take a look at your compile issue soon and come back to you.

**Comment by fran-worley** [comment]
@RKennedy9064 you should find that the latest 2.0.0.beta4 release fixes this issue and the compile error you were experiencing. Feel free to reopen if you're having issues.
