### ISSUE TITLE
Two header rows and no data rows

### ISSUE THREAD

**Issue by djsegal** [offirgolan/ember-light-table#71]
I'm using the code as described in [the docs](http://offirgolan.github.io/ember-light-table/docs/modules/Home.html) and:
 + I can't get data rows to show up (i.e. the body)
 + Both the `{{t.head}}` and `{{t.foot}}` repeat the same header row

---------

extra info:
+ calling `light-table` inside `{{posts-table model=model.user.posts}}`
+ using `ember v2.5.1` & `ember-data v2.6.0`

**Comment by offirgolan** [comment]
What version of ember-light-table are you on? This is a known in the last couple beta releases that we are working out.

**Comment by djsegal** [comment]
@offirgolan `v1.0.0-beta.6`

**Comment by offirgolan** [comment]
Yeah its a known issue with the last 2 or 3 beta releases. We are working on it :)

**Comment by djsegal** [comment]
confirmed. reverted to `v1.0.0-beta.5` and everything worked properly
