### ISSUE TITLE
`onRowClick` not working in iPhone browser.

### ISSUE THREAD

**Issue by AdminDev826** [offirgolan/ember-light-table#721]
`onRowClick` is works well in the PC, Android, but not working `iPhone`.
No calling `action` but selecting the row.(highlighted the row).

**Comment by fran-worley** [comment]
@AdminDev826 have you ensured that your TR has `cursor: pointer` set in the CSS? There is a long standing (first reported in jQuery back in 2010) 'known bug' with iOS Safari where click events aren't triggered. The simplest workaround is to add `cursor: pointer` to the tr.

If you're still having difficulty then I'll need more information about your app (ember version, ELT version, sample code etc.). I use ELT in a few production apps which have onRowClick working happily on iOS Safari so I'm sure we can get it working for you!

**Comment by AdminDev826** [comment]
Hello @fran-worley 
Thank you for your kind message.
I've added 'cursor: pointer;` but still no luck..
I am going to use `onRowDoubleClick`..

**Comment by fran-worley** [comment]
@AdminDev826 if you need more help I'll need code samples and version numbers... 😃

**Comment by AdminDev826** [comment]
```
{{#t.body onRowDoubleClick=(action 'onRowClick') as |body|}}
      {{#if isLoading}}
        {{#body.loader}}
          {{table-loader}}
        {{/body.loader}}
      {{/if}}
    {{/t.body}}
```
```
onRowClick(row, ev) {
      // Prevent transition if dropdown clicked
      if (!$(ev.target).hasClass('form-control') && !$(ev.target).hasClass('x-option')) {
        localStorage.setItem("detailed_tab", "1");
        this.loading.setLoading(true);
        this.router.transitionTo(this.route, [row.get('content.id')])
          .finally(() => {
            this.loading.setLoading(false);
          });
      }
    },
```

```
"ember-light-table": "^1.13.2",
```

**Comment by AdminDev826** [comment]
I think I may need to add `selectOnClick=false` option also..

**Comment by AdminDev826** [comment]
Finally, it works. :D
Thank you. @fran-worley
