### ISSUE TITLE
It appears that ember-light-table is having lot of issues with ember-octane? are there any solutions for this that i should look into? has anyone else had these issues?

### ISSUE THREAD

**Issue by TheLooseCannon** [offirgolan/ember-light-table#724]
[ember-light-table] table must be an instance of Table

This is the error thats popping up right now

**Comment by richard-viney** [comment]
You'll need to be on the latest 2.0 beta release, and use `Table.create(...)` rather than `new Table(...)`. See https://github.com/offirgolan/ember-light-table/issues/726.

**Comment by fran-worley** [comment]
There are a few issues with Octane, though none should stop you from being able to use the addon providing you're on v2.x as @richard-viney has said.

We're actively working on full support for Octane features as we speak so keep in touch!

**Comment by surekha199** [comment]
> You'll need to be on the latest 2.0 beta release, and use `Table.create(...)` rather than `new Table(...)`. See #726.

am getting below error with Table.create()

 Assertion Failed: [ember-light-table] columns must be an array if defined", …}

**Comment by richard-viney** [comment]
@surekha199 Perhaps double-check what arguments you're passing to `Table.create()`.

**Comment by surekha199** [comment]
import { inject as service } from '@ember/service';
import Component from '@ember/component';
import layout from './template';
import { debounce } from '@ember/runloop';
import moment from 'moment';
import Table from 'ember-light-table';
import { computed } from '@ember/object';
import { task } from 'ember-concurrency';
import Row from 'ember-light-table/classes/Row';
import { A as emberArray, makeArray } from '@ember/array';




export default Component.extend({
    columns: computed(function() {
      return [ {
        label: 'Id',
        valuePath: 'id',
        width: '150px'
      }, {
        label: 'Type',
        valuePath: 'type',
        width: '150px'
      }, {
        label: 'Hit-Points',
        valuePath: 'healthpoints',
        width: '150px'
      }
    ];
    }),
    model: computed(function() {
        return  [{
            id: 'Quarkos',
            type: 'Water',
            healthpoints: 12,
            weakness:'Fire',
            picture: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/3195dialock.png',
          },
          {
            id: 'Gaeas',
            type: 'Earth',
            healthpoints: 15,
            weakness:'Water',
            picture: 'https://upload.wikimedia.org/wikipedia/commons/9/9b/Amelie_300dpi.png',
          }, {
            id: 'Lightos',
            type: 'Fire',
            healthpoints: 9,
            weakness:'Earth',
            picture: 'https://upload.wikimedia.org/wikipedia/commons/1/1c/Devil_cartoon_charactor.png',
          }];
        }),

  //  table: computed('model', function() {
    // return  Table.create(this.get('columns'), this.get('model'));
  //  return Table.create(this.get('columns'), this.get('model'));
    //}),

    init() {
        this._super(...arguments);

//I tried in the below ways
        //let table = Table.create(this.get('columns'), this.get('model'));

        let table = Table.create(emberArray(makeArray(this.get('columns')))
        , emberArray(makeArray(this.get('model'))));

        // , { enableSync: this.get('enableSync') });
        this.set('table', table);
    }    

});
``
this is my component file

**Comment by fran-worley** [comment]
@surekha199 the create method expects an object so you need to pass in

`{ columns: someArray, rows: someOtherArray }`

**Comment by richard-viney** [comment]
As @fran-worley mentioned, when using `Table.create()` you should pass an object with the relevant properties just like you would with any call to create a pre-Octane `EmberObject`:

```js
const table = Table.create({
  columns: this.get("columns"),
  model: this.get("model")
});

this.set("table", table);
```

Also, the `emberArray`/`makeArray` there likely isn't needed, unless you've disabled the array prototype extensions in your app's config, or are making an addon.

**Comment by surekha199** [comment]
Thank you @fran-worley  and @richard-viney ,

I tried both the options mentioned in your comments but I still see the same issue
