### ISSUE TITLE
height:auto

### ISSUE THREAD

**Issue by rwwagner90** [offirgolan/ember-light-table#74]
For some reason, when I set height to auto, the `.tse-scroll-content` div still has a manually set `300px` height, so the table does not size itself to full height.

**Comment by offirgolan** [comment]
This is a known issue in the latest beta that we are currently working on. Please revert back to beta.4.

**Comment by offirgolan** [comment]
@rwwagner90 should be fixed with the just released `beta.7`

**Comment by rwwagner90** [comment]
@offirgolan it is fixed, thanks!
