### ISSUE TITLE
ember-composable-helpers@3.1 addon incompatibility in 2.0 beta

### ISSUE THREAD

**Issue by roberkules** [offirgolan/ember-light-table#740]
I guess it should be fixed in ember-composable-helpers addon, but anyhow, ember-light-table could bump the version to 3.x anyways

see https://github.com/DockYard/ember-composable-helpers/issues/356

**Comment by fran-worley** [comment]
See #737

**Comment by roberkules** [comment]
could you push a new `beta.6`?
