### ISSUE TITLE
Content no longer loads on 1.0.0-beta.6

### ISSUE THREAD

**Issue by rwwagner90** [offirgolan/ember-light-table#75]
Did `setRows` or `addRows` go away or something? I'm not getting any errors that they are undefined, but none of my rows load anymore.

**Comment by offirgolan** [comment]
Nope they didnt go away. This is a rendering issue with ember-scrollable. 

This is a known issue in the latest beta that we are currently working on. Please revert back to beta.4.

**Comment by offirgolan** [comment]
Closing since this is a duplicate of #74
