### ISSUE TITLE
Add special value in valuePath to return the model it self.

### ISSUE THREAD

**Issue by GCorbel** [offirgolan/ember-light-table#81]
I want to use a component to have actions buttons. For the moment, I can pass the id to retrieve the model but it can be useful to have something like this : 

```
  columns: [
    {
      label: 'Actions',
      valuePath: 'self',
      sortable: false,
      cellComponent: 'kh-actions'
    }
  ]
```

What you think?

**Comment by offirgolan** [comment]
Im not sure I follow @GCorbel. Can you give me more information?

**Comment by GCorbel** [comment]
I think it's correct. I finally succeeded by using `row.content`. I did this : 

```
import Ember from 'ember';

export default Ember.Component.extend({
  model: Ember.computed.alias('row.content'),

  actions: {
    delete(model) {
      this.get('tableActions').deleteUser(model);
    }
  }
});
```

I can be useful to have this alias builtin.

**Comment by offirgolan** [comment]
@GCorbel in your template, you can do something like this instead of all the code above:

```hbs
<button {{action tableActions.deleteUser row.content}}>Delete User</button>
```

**Comment by GCorbel** [comment]
You're right, thanks. The alias still a valid suggestion but I close this issue because my problem is solved. Thanks.
