### ISSUE TITLE
Uncaught Error: Assertion Failed: A helper named 'or' could not be found

### ISSUE THREAD

**Issue by masda70** [offirgolan/ember-light-table#92]
Javascript error thrown when loading component.

Based on `ember-light-table`'s example http://offirgolan.github.io/ember-light-table/
- Ember 2.6.2

`ember install ember-truth-helpers` fixes the issue.

**Comment by offirgolan** [comment]
Hmm thats pretty weird since ember-truth-helpers is marked as a dependent. Thanks for opening the issue, ill take a closer look into this.

**Comment by efx** [comment]
FWIW, I am setting the same issue after installing `"ember-light-table": "1.0.0-beta.8"` to my ember-cli project's devDependencies.

**Comment by offirgolan** [comment]
@efx @masda70 I found the issue. Will be releasing a fix soon.
