### ISSUE TITLE
Support options hash when invoking row-related methods like Table.addRow()

### ISSUE THREAD

**Issue by curtisgr** [offirgolan/ember-light-table#93]
Currently, when invoking row-related methods like `Table.addRow()`, the options hash doesn't make it to the Row constructor:

```
this.set('table', new Table(columns = [], rows = []));

this.get('table').addRow({
  key: 'value'
}, {
  classNames: 'some-class-name'
});

// class name is not set on the row
```

To get the options to be set on a row, you currently have to initialize a Row first.

```
let row = new Row({
  key: 'value'
}, {
  classNames: 'some-class-name'
});

this.get('table').addRow(row);
```

Would it not be great if you could pass along the options along with the data when using methods like addRow or pushRow?

**Comment by offirgolan** [comment]
@curtisgr agreed. That functionality should have been there already but I guess I missed it 😝 .
