### ISSUE TITLE
live demo does not work in Safari

### ISSUE THREAD

**Issue by istok20** [offirgolan/ember-light-table#97]
live demo http://offirgolan.github.io/ember-light-table/#/  shows empty table in Safari 8.0.8 from Mac OS X Yosemite 10.10.5

**Comment by blimmer** [comment]
FWIW i can't repro this on 10.11.5 safari 9.x

**Comment by offirgolan** [comment]
Closing as this issue has been abandoned. Feel free to reopen if needed.
